---
title: Ethena Investment Memo DRAFT
---

## Introduction

Ethena Labs provides a solution for crypto-native money.

*v2: Ethena Labs provides an internet enabled, crypto native money.*
*v3: Ethena Labs provides crypto native money for the internet economy.*

Ethena offers a censorship-resistant synthetic dollar, $\$USDe$, which is independent of traditional banking system infrastructure. Backed by a variety of delta-neutral derivative positions against staked Ethereum collateral, $\$USDe$ serves as a censorship-resistant safe haven crypto asset. 

Ethena also enables the 'Internet Bond' - a permissionless dollar denominated savings instrument for users worldwide. $\$sUSDe$ derives yield from both the staked Ethereum collateral as well as the basis in futures markets. 

## Deal

Our proposal is to invest ...

## Context

Turing complete blockchains like Ethereum and Solana have enabled a proliferation of assets and applications to form complex crypto economies that operate in parallel to the traditional financial system. Like all mature economies, the crypto-enabled internet economy requires a liquid and stable *medium of exchange*. 

Today, there is over $\$100$ billion of stablecoins in circulation, serving to enhance liquidity, protect users from volatility, and enable certain financial applications. Despite tremendous growth, however, incumbent stablecoins have failed to address a core tenet of crypto - they [remain](https://decrypt.co/154580/tethers-stablecoin-usdt-has-a-peg-stability-problem-claims-analyst) directly [dependent](https://www.coindesk.com/markets/2023/03/11/circles-usdc-endured-1b-of-net-redemptions-since-silicon-valley-banks-shutdown/) on [centralized institutions](https://dfpi.ca.gov/wp-content/uploads/sites/337/2023/03/DFPI-Orders-Silicon-Valley-Bank-03102023.pdf). 

The crypto industry demands a decentralized stablecoin, one which is independent on traditional banking infrastructure.

## Product

Ethena has created a decentralized stable crypto asset, $\$USDe$. $\$USDe$ is minted against liquid staked Ethereum collateral, which is delta-hedged immediately on issuance with perpetual short position of equal notional size. This mechanism requires just 1:1 collateralization, far more capital efficient than the overcollateralized decentralized designs which fail to increase liquidity in the system.

Ethena Labs has constructed the product operationally to minimize trust at every layer. Starting with the collateral asset, staked Ethereum is diversified across multiple liquid staked token providers including Lido, Rocketpool, and Coinbase. The perpetual future shorts are managed across an array of both centralized and decentralized exchanges, which and can be monitored by anyone with an internet connection in real-time. For custody, Ethena employs a set of third party custodians to transparently secure its staked ETH balances, which are permissionlessly verifiable on Ethereum's public ledger. Participating futures exchanges have agreed to simply mirror these assets on their orderbooks to open the futures positions, so the users assets never leave the designated custodian accounts. The 

The hedged position behind $\$USDe$ is intelligently structured to collect yield on both legs of the trade. Liquid staked Ethereum tokens allow the asset side to capture the ETH-denominated validator yield from the network, while the short futures positions collect funding payments from the basis. This yield unlocks the ability to offer an Internet Bond ($\$sUSDe$), a globally accessible and permissionless savings instrument denominated in the US Dollar. 

Ethena's Internet Bond is scalable, stable, and censorship-resistant. The underlying yield mechanism is [fundamentally different](https://vitalik.eth.limo/general/2022/05/25/stable.html) from [algostable](https://www.aier.org/article/algorithmic-stablecoins/) yields from the past, which were [inherently flawed](https://twitter.com/jp_koning/status/1524343011639013381).

Ethena’s yield naturally scales in harmony with the crypto market, as the issuance increases and decreases with the aggregate Open Interest of the corresponding futures markets.



### Landscape



the most prominent being fiat-backed such as $\$USDC$ and $\$USDT$, both backed by fiat reserves. most of which being  stablecoins circulating 
In 2014, Tether introduced a fiat-backed stablecoin, $\$USDT$, to address this need, offering crypto users a more easily accessible  addressed this need with the introduction of  in 2014
Over $100 billion inFiat-backed stablecoins 
With the introduction of Tether in 2014, stablecoins have become a key building block of decentralized finance (DeFi), 

Several attempts have been made to iterate upon the fiat-backed stablecoins that dominate


## Landscape

The most widely circulating 

There have been many attempts to deliver a decentralized stablecoin to the market. The attempts can largely be indentified in two categories: overcollateralized stablecoins and algorithmic stablecoins.

MakerDAO pioneered the overcollateralized design with DAI, a stablecoin with X billion in circulation. Although generally successful, DAI has suffered several significant complications in the past, and remains certain downsides. 

- [market volatility](https://vitalik.eth.limo/general/2019/11/22/progress.html)

- [dai collateral](https://www.theblock.co/post/236139/makerdao-dai-collateral-usdc)


There have been attempts to address this void. MakerDAO developed a solution DAI to serve this role

The decentralized stablecoin has long been recognized problem in crypto.  Attempts to solve this need include overcollateralized

enabling financial operations In the decade since, incumbent stablecoins have failed to successfully adopt a core tenet of DeFi.

   Despite the tremendous expansion in circulating supply, incumbent stablecoins have failed to adopt the core tenet of crypto: decentralization.



  address the most core requirement of the crypto ethos

 of incumbent stablecoins, primarily 

tremendous growth of stablecoins, 

 enhanced market liquidity, protected traders from volatility, and enabled financial applications such as borrowing and lending protocols.  

Crypto traders had to constantly 
Tether marked the advent first USD stablecoin in 2014, and 

 crypto economies to develop a plethora of assets and applications. assets developed crypto economies spanning financial and gaming applications, Aside from the  With the introduction
Since the [introduction of Bitcoin](https://www.metzdowd.com/pipermail/cryptography/2008-October/014810.html) in 2008, the crypto ecosystem has developed tremendously.  have proliferation


## Problem

As of February 2024, the total cryptocurrency market capitalization sits at approximately $2 billion. 


- Stablecoins within the crypto landscape
- Dependence on fiat backing (USDC & DAI -> treasuries). Highlight SVB USDC events
- Inherently faulty algorithmic stablecoins. Mention Terra and [vitalik's post](https://vitalik.eth.limo/general/2022/05/25/stable.html)





### Extra Scraps

 By utilizing the yield of the staked ETH collateral and the derivatives funding payments, Ethena enables 

  Alongside $\$USDe$, Ethena enables the internet bond 

is addressing one of the most obvious and critical failures of decentralized finance. As billions of dollars of value has entered the crypto economy, identified by   As billions of dollars of TVL independent of traditional banking systems. This solution includes a censorship-resistant, scalable, and stable synthetic dollar   built on Ethereum offering a crypto-native solution for money independent of the traditional banking system.