---
title: Climate
subtitle: Let us not pretend we understand Earth's climate
---

#

*Climate is an NP-complete problem. This can be proven by a reduction to turbulent mechanics. I do not abide by the "general" modern climate-change (Greta) view. However, it's ridiculous to ignore the recent and rapid alterations in atmospheric content as a product of human industrialization.*

## A Collection of Views and Information

NASA \
- [Evidence for Climate Change](https://climate.nasa.gov/evidence/)

Exothermic (Cyclic) Core Theory of Climate Change \
- [The Climate Change Alternative We Ignore (to Our Peril)](https://theethicalskeptic.com/tag/core-exothermic-cycle#:~:text=The%20Exothermic%20Core%20Theory%20of,speed%20up%20in%20Earth's%20rotation.)

The North Atlantic Sea Surface Tempurature Anomoly \
- [We've been accidentally geoengineering for decades... then we stopped](https://twitter.com/hankgreen/status/1687535525169930241?s=20)

IPCC baseline scenarios have over-projected CO2 emissions and economic growth \
- [paper](https://iopscience.iop.org/article/10.1088/1748-9326/abcdd2/pdf)

Hyporthermic Nature of Fungi ("Why Mushrooms are Cold") \
- [paper](https://www.pnas.org/doi/abs/10.1073/pnas.2221996120)

Testosterone histories from tusks reveal woolly mammoth musth episodes \
- [paper](https://twitter.com/pplpleasr1)

Antartica Gained Ice, Not Lost It \
- [article](https://notrickszone.com/2023/06/05/scientists-caught-inflating-antarctic-ice-losses-3000-more-than-observations/)

Anartica Low Ice Winter \
- [article](https://www.iflscience.com/antarcticas-low-ice-winter-should-only-happen-once-every-13-billion-years-69986)

Sea Water Heat Map \
- [website](https://coralreefwatch.noaa.gov/product/5km/index_5km_hs.php)

## Geoengineering

Airforce document on using the weather for power \
- [Weather as a Force Multiplier: Owning the Weather in 2025](https://www.geoengineeringwatch.org/documents/vol3ch15.pdf)

Can Controversial Geoengineering Fix Climate Crisis? \
- [article](https://www.theguardian.com/environment/2022/dec/25/can-controversial-geoengineering-fix-climate-crisis)

Near-term climate risks and sunlight reflection modification: a roadmap approach for physical sciences research \
- [paper](https://link.springer.com/article/10.1007/s10584-022-03446-4)

Reflecting Sunlight: Recommendations for Solar Geoengineering Research and Research Governance
National Academies of Sciences, Engineering, and Medicine \
- [book](https://nap.nationalacademies.org/read/25762/chapter/1#v)

Make Sunsets: Geoengineering Startup \
- [article](https://makesunsets.com/)

Open Letter Against Solar Geoengineering \
- [letter](https://www.solargeoeng.org/non-use-agreement/open-letter/)

Stratospheric ozone changes under solar geoengineering: implications for UV exposure and air quality \
- [paper](https://acp.copernicus.org/articles/16/4191/2016/acp-16-4191-2016.pdf)

Geoengineering could Turn Skies White \
- [article](https://www.scientificamerican.com/article/geoengineering-could-turn-skies-white/)

Washington's New World Order Weapons Have the Ability to Trigger Climate Change  \
- [archive](https://archives.globalresearch.ca/articles/CHO201A.html)