---
title: Cold Exposure
---

## Resources

- [Cold as a Therapeutic Agent](https://link.springer.com/article/10.1007/s00701-006-0747-z)
- [Cold for Centuries](https://doi.org/10.1007/s00421-022-04915-5)
- [Human physiological responses to immersion into water of different temperatures](https://link.springer.com/article/10.1007/s004210050065?noAccess=true)
- [Altered brown fat thermoregulation and enhanced cold-induced thermogenesis in young, healthy, winter-swimming men](https://www.cell.com/cell-reports-medicine/fulltext/S2666-3791(21)00266-4?_returnURL=https://linkinghub.elsevier.com/retrieve/pii/S2666379121002664%3Fshowall%3Dtrue)
- [Impact of Cold-Water Immersion Compared with Passive Recovery Following a Single Bout of Strenuous Exercise on Athletic Performance in Physically Active Participants](https://link.springer.com/article/10.1007/s40279-022-01644-9)
- [Novel Application of Chemical Cold Packs for Treatment of Exercise-Induced Hyperthermia](https://www.wemjournal.org/article/S1080-6032(14)00405-0/fulltext)
- [Short-term cold exposure supports human Treg induction in vivo](https://doi.org/10.1016/j.molmet.2019.08.002)
- [Differences between men and women](https://www.researchgate.net/profile/Marius-Brazaitis/publication/265684623_Gender-specific_cold_responses_induce_a_similar_body-cooling_rate_but_different_neuroendocrine_and_immune_responses/links/5b1e8a82aca272021cf6420a/Gender-specific-cold-responses-induce-a-similar-body-cooling-rate-but-different-neuroendocrine-and-immune-responses.pdf)

### Background

The use of cold-water immersion has a long and rich history. The beneficial effects on human physiology have been recorded as far back as 3500BC [@Wang Et Al.](https://link.springer.com/article/10.1007/s00701-006-0747-z), with the Edwin Smith Papyrus (the most ancient medical text known to date) making references to cold being used for therapeutic purposes. The Ancient Greeks utilized cold-water therapies, as recorded by Hippocrates in the fourth century BC. And even the Golden Age of Rome featured cold-water immersion as treatment for fever, advocated for by Roman Physician Claudius Galen in the second century AD [@Allan Et Al.](https://doi.org/10.1007/s00421-022-04915-5). It was only until recently, however, that modern science began to explore the underlying physiological processes behind the power of the cold. 

### Energy and Focus

Deliberate cold exposure triggers a release of epinephrine (adrenaline) and norepinephrine (noradrenaline) into the bloodstream. These hormones are responsible for the fight-or-flight response, and can make us feel alert and/or agitated [@Huberman](https://hubermanlab.com/the-science-and-use-of-cold-exposure-for-health-and-performance/). This is why many people feel more energized after a cold shower or a cold swim.

### Metabolism

Cold exposure has been shown to increase energy expenditure, which can lead to weight loss and improved body composition. It has been recommended as a healthy and sustainable alternative strategy for increasing energy expenditure [@van Marken Lichtenbelt Et Al.](https://www.ics.uci.edu/~wayne/tmp/Lichtenbelt-CELL-2014-Cold-exposure-increasing-energy-expenditure.pdf).

A core aspect of cold exposure is the activation of [brown adipose tissue](https://www.sciencedirect.com/topics/medicine-and-dentistry/brown-adipose-tissue) (BAT). BAT is a type of fat tissue that is responsible for thermogenesis, or the production of heat. It is found in small amounts in adults, but is more abundant in children. It is also found in higher concentrations in people who are leaner. The activation of BAT is thought to be responsible for the increased energy expenditure that is observed after cold exposure [@Huberman](https://hubermanlab.com/the-science-and-use-of-cold-exposure-for-health-and-performance/).

### Immune Health

A study published in the Journal of Applied Physiology found that cold exposure "induced a leukocytosis and granulocytosis, an increase in natural killer cell count and activity, and a rise in circulating levels of interleukin-6." [@Brenner Et Al.](https://pubmed.ncbi.nlm.nih.gov/10444630/). In other words, this means that cold exposure increases the number of white blood cells, which are responsible for fighting infection, and increases the activity of natural killer cells, which are responsible for destroying cancer cells. It also increases the production of interleukin-6, which is a cytokine that plays a role in the immune response.

A fundamental aspect of cold exposure therapy is the subconcious respiratory response by the sympathetic nervous system. Upon cold immersion, you may find your breathing rate to increase, and your breaths to deepen. It was traditionally believed that the sympathetic nervous system and immune system could not be voluntarily influenced.

In 2011, however, the "Ice Man" Wim Hof participated in a study wherein he was injected with endotoxin, a treated form of E coli bacteria which triggers the same immune response. The study produced groundbreaking results, claiming that through the use of Hof's breathing technique, he voluntarily and significantly increased his immune system response to the bacteria and completely avoided the flu-like symptoms displayed by healthy participants within the control group. In an attempt to discover if this result was reproducable or an anomoly of Wim Hof himself, a study published in the National Library of Medicine in 2014 replicated the methods with individuals who were trained on the breathing technique prior to the injection. It was again found that the breathing technique resulted in an immediate and profound decrease of pCO2 and bicarbonate, and an increase in pH, indicating acute respiratory alkalosis, which normalized quickly after cessation of the breathing techniques. In laymans terms, this means that humans could, through the use of breathing techniques, voluntarily increase immune system activity. 

### Mood 

Cold exposure has been shown to increase the production of endorphins, such as dopmain, which are responsible for the "runner's high" and other feelings of euphoria. It has also been shown to increase the production of serotonin, which is responsible for feelings of happiness and well-being. Increased dopamin release can last for as long as 6 hours after cold exposure, and increased serotonin release can last for as long as 24 hours after cold exposure [@Ootsuka](https://d1wqtxts1xzle7.cloudfront.net/45682221/Dopamine_D2_receptor_stimulation_inhibit20160516-31269-1s2oiw1-libre.pdf?1463445133=&response-content-disposition=inline%3B+filename%3DDopamine_D2_receptor_stimulation_inhibit.pdf&Expires=1676347808&Signature=aHUwPNhyO4PHj5e6f5rSvveE1-Y~LjTqCj3PnucmCAw6WWkIhxalmbFqh1wR~VzD6e89R0t~T0rEQqDSV91KE1LMIDVdQwQ3k0o4Tqj-Lnbn9-siU-Yu-OYXIUe3bYVDkQ91c5XWCklXFzY-cNyetQ6DVCEuZXYdohjYSe0AmhiPHKfvEy0LOyzJ0Gp0qq7ICNnpVBy9-VWG4CMGB0JUkGMM42oMlf7kCpbUZoO0AphhL8OHGvov5hMD9FU285~8dWPt8jZnHgaJnsL782IlJGUiDYRogDPyhDxry-OyzKY5EOjXkkFyH7sXt95u1I~2QlPXPRlW7GU9zQWuFwE7HA__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA).

### Cold Immersion, T-Cells, and NK Cells

Cold water immersion has been reported to increase the level of T-cells (specifically, peripheral T lymphocytes). This has been observed both (1) in the short term after a single treatment/swim, as well as (2) in a longer, sustained manner after a period of multiple treatments per week.

T-cells, also known as T lymphocytes, are a type of white blood cell that are derived from bone marrow stem cells and mature in the thymus gland. They play an essential role in fighting off infection. With an ability to “recognize” and “remember” germs that they have seen before, they can quickly respond if they see that germ again.

In other studies, similar increases have been observed for NK (Natural killer) cells. NK cell activity has been observed to increase both briefly after a treatment and in a sustained manner following consistent and repeated immersions.

Natural killer (NK) cells are a type of white blood cell that can quickly recognize and destroy infected or cancerous cells without prior exposure or activation. NK cells do not require prior exposure to antigens, which are proteins or other molecules that can trigger an immune response. Instead, they use a variety of receptors to detect abnormal cells and then release toxic substances to kill them.

### Cold Immersion & Cancer

Although the science is still developing, there is reason to believe cold water immersion may help prevent the risk of tumors and cancers.

In a study done on lab mice, a “somewhat reduced spontaneous incidence of tumors, especially sarcomas” was observed among the group of mice that endured repeated cold stress (cold swims). It has also been reported that Cold-inducible RNA binding protein (CIRP) may function as a tumor suppressor via suppressing proliferation. Finally, there’s been a clinical review performed by the National Institute of Health (NIH) exploring the cold’s ability to stimulate “anti-tumor immunity”, which concluded this area deserves “more research as a major target for cancer therapies.”

We look forward to the progression of this research.

### The Role of the Breath

Western biomedical research is gradually discovering the significance of the way in which we breathe, in relation to the body and its many physiological processes. Among these discoveries are how deliberate breathing techniques can 
1. increase our tolerance to extremely cold environments and 
2. alter immune function in real time.

Let me highlight the significance of these discoveries: For centuries, modern (Western) medicine considered these processes (circulatory system, immune system, sympathetic nervous system) autonomic or involuntary, meaning they are unable to be controlled consciously. Recent research has slipped this understanding upside down - essentially, deliberate breathing practice is a superpower.

There is *incredible* research on breathing methods/techniques beyond the scope of this article, spanning brain function, enlightened & hallucinogenic states, mood/emotion control, and more. We encourage you to explore it if you’re interested, and we hope to come back to the topic in a future article/series.

The first groundbreaking study was done on Wim “The Ice Man” Hof, himself. In 2011, researchers at Radboud University injected Wim Hof with endotoxin, a treated form of bacteria that triggers a general immune response, as Wim practiced his breathing technique. The results were astounding:

> …levels of inflammatory mediators in Hof's blood were much lower. On average, Hof's immune response was decreased by 50 percent compared to other healthy volunteers. In addition, hardly any flu-like symptoms were observed.

At first, this study was a target of skepticism. With a sample size of 1, it was unclear whether the results were reproducible or simply Wim Hof producing an outlier result as an individual. However, it was enough to encourage further exploration.

In 2014, a study published in the National Library of Medicine sought out to reproduce the 2011 results in average “healthy participants”. The intervention group was trained for just 10 minutes in Hof’s breathing technique, and then both groups were administered with the endotoxin.

> In the intervention group, practicing the learned techniques resulted in intermittent respiratory alkalosis and hypoxia resulting in profoundly increased plasma epinephrine levels. In the intervention group, plasma levels of the anti-inflammatory cytokine IL-10 increased more rapidly after endotoxin administration, correlated strongly with preceding epinephrine levels, and were higher. Levels of proinflammatory mediators TNF-α, IL-6, and IL-8 were lower in the intervention group and correlated negatively with IL-10 levels. Finally, flu-like symptoms were lower in the intervention group.

In summary, the results were successfully reproduced, and the researchers concluded that it is possible to voluntarily activate the sympathetic nervous system and affect immune response through deliberate breathing technique.

Hof’s breathing technique shook the biomedical science industry again in 2018, this time after he showed humans can consciously enhance their ability to survive in extremely cold conditions (beyond what was previously thought possible). The study concluded that deliberate breathing technique resulted in “increased sympathetic innervation and glucose consumption in intercostal muscle, generating heat that dissipates to lung tissue and warms circulating blood in the pulmonary capillaries.”

### Method

The optimal, and most studied, approach entails complete submersion in cold water from the neck down. To sit in water from the chest down, with arms outstretched, for instance, precludes full stimulation of the stress response mechanisms which yield many of the advantages discussed in the previous two sections of this series.

Likewise, although cold showers have demonstrated efficacy, they have not been subjected to the same level of scrutiny as cold water immersion from the neck down. Therefore, it is reasonable to infer that the most optimal results may be obtained through full immersion in cold water. In the event that access to a cold bath is unattainable, cold showers serve as a reasonable alternative.

### How Cold is “Cold”?

The short answer to this question is: uncomfortable but safe. Discomfort means that the beneficial stress hormones discussed in part 1 are being released in your system, thus offering the corresponding benefits. 

If you are getting started, you may find that water temperatures around 45 degrees Fahrenheit is enough to feel uncomfortable. Over time, you are likely to find your cold immersion routine becomes easier. If you want to progress, and continue to extract maximum benefit, you must be honest with yourself to recognize whether you are pushing yourself, and increase intensity (decrease temperature) as appropriate.

### How Often/Long Should I be Cold?

A study done by Scandinavian scientist Dr. Susanna Søeberg suggests the magic number is at least 11 minutes per week, total. This is the threshold needed to increase brown fat thermogenesis and metabolism. This could be done in various ways, such as spreading it out throughout the week or doing it all in one day.

### When Should I Get Cold?

Science suggests that whether cold exposure is done in the morning or at night does not affect the health benefits discussed previously. However, I personally recommend doing your cold exposure first thing in the morning.

The reason why relates to internal body temperature and circadian rhythm. Your body is warm when it is awake, and cold when it is asleep. In fact, studies have shown your body temperature must decrease by 1.5 degrees in order to fall asleep.

Exposure to cold temperatures can cause your body to heat up afterwards, making it more difficult to fall asleep if done late at night. On the other hand, if performed early in the morning, cold exposure may boost your energy levels and start your day off on the right foot.

### The Søeberg Principle

The Søeberg Principle, developed by Dr. Susana Søeberg, posits the following:

To enhance the metabolic effects of cold, force your body to reheat on its own

> End With Cold

Additionally, the act of shivering during or after cold exposure can further activate brown fat thermogenesis and release heat from muscles, resulting in heightened metabolic increases.

To increase shivering and optimize the metabolic benefits of cold exposure, individuals are advised to avoid huddling and wrapping their arms around themselves while in the cold or after exiting it. Likewise, entering a sauna after cold exposure, although relaxing, will limit the metabolic benefits of the cold.

If you want to go further, it is recommended to refrain from towel drying and instead allowing the body to naturally reheat and dry off. Admittedly, this is difficult, especially when it’s cold outside.


