---
title: Ethena Pre-Launch Agreement
---

# Agreement 1 vs Agreement 2

## Agreement 1

#### **Participant Incentives**

- Ethena Labs will allocate 10 percent of all yield generated by the Ethena Protocol during the Guarded Mainnet Pre-Launch to a referral pool paid out to all participants.
- Participant’s Commitment Amount (to the extent actually deployed to mint USDe on the Ethena Protocol) shall be counted towards this incentive and shall accrue its pro-rata portion of the real yield produced by the Ethena Protocol

Additionally, the Company will provide an additional incentive in the form of ENA governance tokens, the native governance token for the Ethena Protocol, to be created and distributed at a later date. The amount of the Governance Token incentive shall equal the greater of

1. The amount of ENA governance tokens such that all incentives equate to a [50]% total APY for the twelve months prior to the date upon which the total incentives are determined.
2. The amount of ENA governance tokens equivalent to a [10]% APY with respect to Commitment Amounts actually deployed within the Ethena Protocol during the Term. The price per ENA token utilized determined by 7-day TWAP of ENA on the final day of the Term, according to coingecko closing prices.

**Payout**

Governnace token transferred to Participant wallet within 7 days of the end of the Term, and shall not be subject to a lockup.

## Agreement 2

#### **Participant Incentives**

- Participant not entitled to receive any fees or other yield from the Protocol.

Allocation shall be determined at the conclusion of the Term by multiplying by

1. a fraction, the numerator of which is the daily average value of assets used by Participant to mint USDe during the Term pursuant to this Agreement and the denominator of which is $10,000,000 
2. 0.6%. 

For the avoidance of doubt, amounts committed to mint USDe during the Term pursuant to separate liquidity participation agreements (or similar) shall not be counted for purposes of this paragraph.

## Comparison

Agreement 2 is an investment at $1.666 billion valuation.