---
title: "Solana"
---

## Sites

- [Solana Beach](https://solanabeach.io/)
- [Stakenet](https://www.jito.network/stakenet/)
- [Solscan](https://solscan.io/)
- [Solana.fm](https://solana.fm/)
- [Shyft Explorer](https://translator.shyft.to/)
- [Solana Stack Exchange](https://solana.stackexchange.com/)
- [Solana Forum](https://forum.solana.com/)
- [Triton Priority Fee Explorer](https://www.triton.one/solana-prioritization-fees/)

## Tech

### Core

- [Visa: A deep dive on Solana, a high performance blockchain network](https://usa.visa.com/solutions/crypto/deep-dive-on-solana.html)
- [Solana: An Auditor's Introduction](https://osec.io/blog/2022-03-14-solana-security-intro)
- [Solana Internals, Part 1](https://medium.com/@metaproph3t/solana-internals-part-1-449ee68cb4f4)
- [Jumping Around the VM](https://osec.io/blog/2023-12-11-jumping-around-in-the-vm)
- [Solana Validator 101: Transaction Processing](https://www.jito.wtf/blog/solana-validator-101-transaction-processing/)
- [Firedancer: A New Client by Jump](https://jumpcrypto.com/jump-crypto-sets-out-to-build-new-validator-client-for-the-solana-blockchain-to-increase-the-throughput-and-reliability-of-the-network/)
- [Validator Economics on Solana](https://medium.com/chorus-one/exploring-validator-economics-on-solana-cb1498a3aef6)
- [Jito Validator Economics Spreadsheet](https://docs.google.com/spreadsheets/d/1JhgBLvZInSGA91GDWYFg_-6CIevCv8RUOe3kgSTm5_M/edit#gid=2134008686)

### Topics

- [Helius Blog: Solana and QUIC](https://www.helius.dev/blog/all-you-need-to-know-about-solana-and-quic)
- [Helius Blog: SWQoS](https://www.helius.dev/blog/stake-weighted-quality-of-service-everything-you-need-to-know)
- [Durable Nonces](https://solana.com/developers/guides/advanced/introduction-to-durable-nonces)
- [Solana Gulf Stream: Helius](https://www.helius.dev/blog/solana-gulf-stream)

### Advanced

- [How will Solana Improve its Stability?](https://medium.com/chorus-one/how-will-solana-improve-its-stability-6d4b0ba41866)
- [Reverse Engineering Solana with Binary Ninja](https://osec.io/blog/2022-08-27-reverse-engineering-solana)
- [What is Stakenet?](https://buffalu.substack.com/p/wtf-is-stakenet)
- [SIMD: Asynchronous Program Execution and Broadcast](https://github.com/solana-foundation/solana-improvement-documents/pull/45)
- [Priority Fees Github Issue](https://github.com/solana-labs/solana/issues/22820)
- [Dune Query: % of Sol Txs with Fee above base](https://dune.com/queries/1111217/1898826)
- [Multiple Concurrent Leaders](https://x.com/aeyakovenko/status/1810222589991583922)

### SVM

- [Anza's new SVM API](https://www.anza.xyz/blog/anzas-new-svm-api)

### Features

#### Actions and Blinks (blockchain links)

- [webpage](https://solana.com/solutions/actions)
- [docs](https://solana.com/docs/advanced/actions)
- [dialect](https://www.dialect.to/)

### FTX Estate Liquidation

- Auction 1: btw 25-30mm SOL @ $64, [Aug 5 2024](https://www.bloomberg.com/news/articles/2024-04-05/ftx-s-solana-sale-galaxy-pantera-buy-tokens-at-64-sol?embedded-checkout=true)
- Auction 2: 1.8mm SOL ~ $100 ($95+), [April 25, 2024](https://www.theblock.co/post/291702/ftx-estate-wraps-up-second-tranche-of-locked-solana-sales-with-bids-around-100)
- Auction 3: unknown amt SOL