---
title: "Project White Hot"
description: "Nearly impossible to confirm validity"
page-layout: full
---


PROJECT
‘WHITE HOT’
Mission Assessment of
Recovered Lenticular Aerodyne Objects

General Nathan Twining
Briefing document for President Eisenhower

PART 1. PROJECT WHITE HOT INTELLIGENCE ESTIMATE (PRELIMINARY)

LANDING ZONE NO, 1
Socorro, New Mexico–the unidentified lenticular-shaped Aerodyne which has been designated ULAT-1, has been evaluated as a non air breathing aircraft of unknown origin. Totally lacking conventional wing, fuselage, nacelle, control, and fuel systems  strongly indicates it is not Russian.

Consultation with Paperclip specialists concur. Aerodynamic features exhibited in ULAT-1 represents a very high degree of engineering and sophistication not seen in this country.

Dimensional homogeneity study cannot explain how this craft sustains load and lift factors necessary for flight.

The power plant does not even remotely resemble any conventional type now in use. Lacking any discernible intake or exhaust features, it is the opinion of AMC and ONR that this craft was designed to operate outside of the earth’s atmosphere.

The unconventional conclusions reached by members of this fact finding mission remain tentative at this time. Some members have expressed the view that ULAT-1 may be the product of an advanced culture from another planet that is much older than ours and has utilized their science and intellect for interplanetary space travel. It is not precisely known if the occupants purposely had the objective of exploration and of curiosity or with the intent of surveying for other reasons. So far, no hostile action or intent has been observed since they made their presence known.

Given the fact that our atomic bomb tests, atmospheric exploration with rockets, and XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXed in New Mexico, could have precipitated the events that led to the incident and subsequent actions taken by the military.

Operating under the assumption that the fallen object was a long-range Russian reconnaissance platform collecting aerial photographic intelligence data military intelligence personnel were a instructed to secure the craft, debris and any occupants as rapidly as possible.

Concerns over possible exposure to civilian of unknown biological and chemical agents dictated the quarantine measures taken.

Radiation hazards were assumed and protective measures were taken as well.

In the interest or National Security priorities it was necessary to detain civilian witnesses for interrogation to satisfy intelligence requirements and quash rumors that could alert potential espionage agents known to be in the vicinity.

Several bodies were discovered.

Because on-site medical personnel were unsure of the physiological make up of the occupants, special preparations and preservation methods were employed. Autopsy information obtained so far suggests that the occupants mimic the features associated with Orientals.

Outwardly, they appear human-like with but one exception, autopsy notes mention a rarely observed XXXXXXXXXXXXXXXXXXXXXXXXXXXXXs present which supports the premise that these beings originate from another planet.

PART TWO
TECHNICAL EVALUATION (PRELIMINARY)
ULAT-1

Upon close examination of the exterior surfaces of the craft’s fuselage, metallurgists found the the skin to be of a ferrous metal white in color. The metal exhibits all the characteristics of high grade steel.  It was determined that the steel was cold-formed and heat created.

1. Tensile strength was estimated in excess of 50,000 pounds per square inch. Shear tests give the metal a durability rating above 175,000 pounds per square inch, making this fuselage extremely strong and heat resistant.

2. Static and pressure flow simulations were impressive.  The low profile ration of 6-1 gives the aerodyne a great advantage in overcoming the restrictions of the boundary layer effect in high performance operations.

3. Span flanges are constructed in unusual kinematic design which is believed to allow strain relief at supersonic speeds.
There were no visible signs of plate-stiffeners, there were no fasteners, weld, rivets, or fittings, holding the fuselage together.

4. Lack of wings, flaps, stabilizers, and surface central features, suggests that the craft is a lifting body.

5.    There are no air intakes for exhaust.

6.    There are no cables

7. There are no identifiable electronics (wiring, ignition, lights, instrument, compartment, engine, motors, vacuum tubes, solenoids, generators, heaters, etc.)

8. The power-plant, (severely damaged) XXXXXXXXXXXXXXXXXx neutronic engine. XXXXXXXXXXXXXXXXXXXXXx detected heavy water and deuterium (light hydrogen) elements appeared  to be the primary ignitor.  A series of coils and heavy magnets connected to the neutronic engine via an oddly arranged group of electrodes (actually not yet identified) appears to be the active force.  One small motor was examined.  It is encased in a pure aluminium capsule  directly underneath the main compartment.  There is a small exhaust aperture attached that was what can only be described as an helicoid mechanism XXXXXXXXXXXXXXXXXXXXX. The auxiliary motor may be articulated.

Advertisement

9.  Navigation and engine controls may be activated by tactile manipulation.  Viewing may have been achieved by form of television imagery.  Symbolic notation appears to be the form of flight  and control indicators.  Flat panels of unknown metal has been suggested as a device associated with the operation of the aerodyne was discovered and analyzed.  It’s mode of operation and purpose is unknown.

10. The absence of provisions, berthing compartments and storage areas, suggest the notion that this craft may be a short range reconnaissance platform.  The only recognizable features XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

11. Mode of operation of operation is believed to be instrumentation and suggests that the aerodyne from reconstruction from available wreckage XXXXXXXXXXXXXXXXXX biosensory and optical stimuli for these reasons:

absence of indicator signals
Absence of any circular dials
Absence of linear dials or moving pointers
Absence of counters
Absence of scopes
No mechanical signal indicators
12. There were identifiable control types found among the assortment of artefacts that would indicate the operation of the propulsion unit was manually activated – no knobs, push buttons, toggle switches, levers, balls, handwheels, hand-cranks, or foot pedals were observed in the interior space of the flight cabin.

13. The apparent lack of additional clothing and equipment reinforces the belief that the occupants were engaged in a purely exploratory flight.

14.  It is not presently known if electromagnetic radiation effects from the   power plant had contributed to pilot error or death before impact.  If inadequate shielding was the primary cause of pilot error XXXXXXXXXXXXXXs detected.

15.  It is believed by some of the crash inspection personnel that sudden decompression and change in atmospheric pressure may have contributed to pilot error.  Clothing removed from occupants do not resemble any pressure suit currently being tested by the Army or the Navy for high altitude experiments.  Since temperature and humidity factors for the occupants is unknown, it is impossible to determine if decompression and temperature changed affected circulatory and dexterity functions.  Although it is believed the occupants may have been overcome by some yet undiscovered pollutant or noxious fumes originating inside the craft.

16.  Rotation or rapid oscillation could have been a contributing factor in pilot error.  It is not known if organic effects played a part  either since medical data is non-existent in which to make any judgment as to exact cause of   death or machine failure.

17.  The most probable cause of the crash is believed to be excessive acceleration combined  with steep descent. The seating arrangement was transversely designed about the vertical axis of the occupants in a positive direction of flight.  The panels removed from the craft resemble the ones taken from the occupants, suggesting a symbionic relationship between operator and the function of the aerodyne’s operation. A very tentative working theory was expressed by the scientific members of the inspection team that pilot-aerodyne interaction may occur via electronic-nonword symbols perceived through the tactile manipulation of the fingers feeding impulses to the brain and visa versa.  All of which may suggest a non-inert quality or the materials existent as being a product or artificial intelligence.

18. The following elements were analyzed and found to exist in the small neutronic power plant that was found inside ULAT-l:

a.    UF6 in metallic form;
b.    hydrogen-fluoride gas;
c.    water and uranium tetra fluoride;
d.    powdered magnesium and potassium chlorate,
e.    metal similar to lead with a chocolate brown color;
f.   U-235 in metallic form;
g.   plastic-like material similar to NE 102,
h.    Beryllium,
i.    Pure aluminium;
j.   Thorium isotope material;
j.   Plutonium powder.

19. Scientists from Los Alamos and Sandia Base were alarmed that the power plant could possibly function as a bomb if the elements described above were processed in similar fashion as was done for the lens and shot-gun detonators. This originally was the first conclusion. After further evaluation, it was determined that since no recognizable firing circuits were identified, the threat or detonation did not exist.

20. The only evidence or circuitry found on the motor was thin plastic-like sheets fashioned like platters embossed on the exterior of the spherically-shaped casing coated by a thin film or pure silver. Under high power magnification it was observed a series of fine grid-like lines intersecting groups of dots arranged in circular patterns.

PART III
SCIENTIFIC PROBABILITIES

1. Based on all available evidence collected from recovered exhibits currently under study by AHC, AFSWP, NEPA, AEC, ONA, NACA, JBDB, RAND, USAAF SAG. and MIT, are deemed extraterrestrial in nature. This conclusion was reached as a result of comparisons of artifacts XXXXXXXXXXXXXXXXXX discovery in 1941. The technology is outside the scope of US science, even that of German rocket and aircraft development.

2. Interplanetary space travel is possible provided adequate funding, necessary resources are made available, and national interest is piqued.

3. Our solar system is not unique. Chances are favorable for intelligent life on other planets notwithstanding similar development not unlike our own.

4. Being that our culture is relatively young (in relation to the cosmic scale), it is possible that other cultures may have developed faster, or are much older and have avoided the pitfalls common in our historical and scientific development.

5. Human origins may not be constrained to one planet. Our genus may be found among solar systems similar to our own.

6. The laws of physics and genetics may have a genesis in a higher, structured order than once previously thought.

PART IV
POLITICAL CONSIDERATIONS

Given the existing political climate in the US and the unstable conditions in Europe, it is the considered opinion of the members, that if the Administration went public with the information as found in this report now, the results would be damaging, even fatal to the world Political structure as it now exists. The following considerations were reviewed and debated, which led the mission to the following opinions:

1.    Public trust of the political institutions may be eroded and possibly be held in disrepute.

2.    A complete revisioning make take place as institutions of higher learning thus calling into question the certainty of scientific knowledge.

3.    The ability of the Armed Forces to secure National Security would be put in jeopardy and possibly lead to undue public fear and disorder.

4.    History and religion in the political context would probably suffer the most damage causing unprecedented upheaval in social and psychological well-being.

5.    Political repercussions may occur in our diplomatic efforts of containing the Communist threat to our democratic interests.

6. If such an announcement were made by the current Administration, it could be perceived by opposing party as a trick, laying open to accusations of unethetical (sic) posturing and manipulation of the public’s mind.

PART V
NATIONAL SECURITY STRUCTURE

With the passage of the National Security Act of 1947 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXas presented an unprecedented situation regarding maintaining secrecy  related to the information contained in this report.

In the early months of 1942, up until the present, intrusions of unidentified aircraft have occasionally been documented, but there has been no serious investigations by the intelligence arm of the Government. Even the recovery case of 1941 did not create a unified intelligence effort to exploit possible technological gains with the exception of the Manhattan Project. We now have an opportunity to extend our technology beyond the threshold that we have achieved, XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX.  Aside from technological gains, we face an even  greater challenge, that of learning the intent of such a presence. There are questions that remain unanswered, such as: What forces face us? What kind of defense do we have? Where do they come from and what kind of weapons do they possess?  Where can we stage our forces in advance, XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX How wide a front? How many craft can we expect?  And XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

The members of the mission are prepared to submit a separate report on just this problem alone. And it would take a dozen volumes to explain how these problems should be met.

Our only point, however, is that a combined intelligence and research operation would be a vast, intricate, covertly
planned marshaling of resources, human and material, to solve a specific, clearly defined problem.

We have to find effective methods of persuasion with other government agencies without creating a sense of impending doom. The first task is to carefully appraise the problem. The second is to evaluate the known resources and probable strategy of the visitors. The third is to inventory our own ways and means, ascertain how much resources we can bring to bear, and how fast. The third is to devise our strategic plan. And last is to work out with infinite pains the tactical details and the myriad secondary problems of funding and security.

It is the unanimous opinion of the members that Operation MAJESTIC TWELVE be a fully funded ant operational TOP SECRET Research and Development intelligence gathering agency. It is also recommended that a panel of experts be appointed to chair and oversee the functions and operations of said agency. It’s members  should have appropriate security clearances and full cooperation XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX the National Security Council, the Pentagon, XXXXXXXht, XXXXXXXXXXXXXXXXXXXXX
Joint Intelligence Committee, Joint Intelligence Objectives Agency, Central Intelligence Agency, Atomic Energy Commission, Joint Research and Development Board, Army Security Agency, and the National Advisory Board on Aeronautics.

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXgy are highlighted:

1. Propeller driven bomber aircraft and jet engines, armed with conventional and atomic bombs.

2. Jet fighter aircraft, including some of super­sonic speed, armed with rockets and guns.

3. Propeller-driven aircraft, valued for their endurance.     .

4. Guided anti-aircraft missiles, and radar-guided anti-aircraft guns.

5. Short and medium-range guided missiles. Drone  aircraft.

6. Atomic charges, in bombs, missiles and torpedoes.

In the arena of nuclear weapons we feel there is a certain advantage to be gained XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.  It is speculated by some that if reduced size and miniature circuitry were introduced into the proposed hydrogen bomb program, it would give US Strategic Air Forces a great deterrence capability over the Russians.  Current studies at MIT of micro-electronics taken from ULAT-1 may give us the strategic advantage so desired. It is strongly recommended that funding be allocated in this area.

There is a good chance that the Russians may try to make use of the flying saucer scare by public news media and diplomatic means of a technological breakthrough in aircraft and missile development. We feel that such a disclosure would certainly cause great embarrassment to our elected officials and to the military, not to mention the panic felt by the citizenry. To counter such a threat, it is recommended that a counterintelligence program be drawn up and held in abeyance if at such time the situation should present itself. It might be suggested that we should make a preempted use of these objects for the purpose of psychological warfare once the true nature of these objects are known and understood.

To further assist and aid all MAJCOM in the US and overseas, it is recommended that a standard intelligence reporting system be implemented through standard reporting channels with technical data forwarding instructions. At present, there are no specific intelligence guidelines available to military commanders in dealing with sightings and material evidence collection. It would be advisable for the respective Secretaries of the Armed Forces to devise a security policy of plausible denial, if and when the public becomes aware of the reality of these objects and the interest of the military of such incidents.

In conclusion, for reasons of national security and the public well being, the US must be perceived as being the top of the heap and every effort must be made to insure that there is, and never has been, a threat to the country.

