project:
  type: website
  resources: 
   - "apple-touch-icon.png"

format:
  html:
    theme: simplex
    css: styles.css
    # toc: true

website:
  title: "bmac.ai"
  favicon: media/favicon.ico
  site-url: "https://bmac.ai"
  # google-analytics: "UA-XXXXXXXX"
  twitter-card: 
    image: "media/bg.jpeg"

  navbar: 
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: library
        text: Reads
      - href: writes
        text: Writes
    right:
      - icon: github
        href: https://github.com/brendan-mccaffrey
      - icon: twitter 
        href: https://twitter.com/0xbmac
  
  sidebar: 
    search: true
    style: docked
    collapse-level: 2
    alignment: left
    logo: media/athenaeum.png
    contents: library/*/

  search: 
    location: sidebar
    type: textbox
    

  page-footer: 
    left: "Copyright 2023, Brendan McCaffrey"
    center: "$x^{14}$" 
    right: 
      - icon: github
        href: https://github.com/brendan-mccaffrey
      - icon: twitter 
        href: https://twitter.com/0xbmac



# Fav Themes
# - litera
# - simplex
# - header of lux
# - morph interesting
# - spacelab


