---
title: Starknet
---

## Resources

- [Starknet Docs](https://docs.starknet.io/)
- [Starknet Book](https://book.starknet.io/)

## Cairo

Cairo is a programming language designed for a virtual CPU of the same name. The processor was created for cryptographic constraints, making it capable of efficiently proving the execution of any program running on it. This means that you can perform time consuming operations on a machine you don't trust, and check the result very quickly on a cheaper machine. While Cairo 0 used to be directly compiled to CASM, the Cairo CPU assembly, Cairo 1 is a higher level language. It first compiles to Sierra, an intermediate representation of Cairo which will compile later down to a safe subset of CASM. The point of Sierra is to ensure your CASM will always be provable, even when the computation fails.

- [Cairo Programming Language Book](https://book.cairo-lang.org/ch00-00-introduction.html)
- [Cairo: a Turing-complete STARK-friendly CPU architecture](https://eprint.iacr.org/2021/1063.pdf)
- [Cairo, Sierra, and CASM](https://medium.com/nethermind-eth/under-the-hood-of-cairo-1-0-exploring-sierra-7f32808421f5)

- **[Getting Started](https://book.cairo-lang.org/ch01-00-getting-started.html)**