---
title: Ethereum
description: All things related to Ethereum Mainnet, the world's first Turing-Complete distributed state machine
page-layout: full
table-of-contents: true
---


## Forums / Resources 

- [Ethereum Research Forum](https://ethresear.ch/)
- [Eth R&D Discord](https://discord.com/invite/qGpsxSA)
- [Flashbots Collective Forum](https://collective.flashbots.net/)
- [Ethereum Youtube: Community calls and such](https://www.youtube.com/@EthereumProtocol/videos)
- [Protocol Guild](https://protocol-guild.readthedocs.io/en/latest/)


### Ethereum Virtual Machine (EVM)

- [Eth2Book: A lot of Good Info on Ethereum](https://eth2book.info/)
- [The Hitchhiker's Guide to Ethereum](https://members.delphidigital.io/reports/the-hitchhikers-guide-to-ethereum/)
- [Ethereum Data Structures](https://arxiv.org/pdf/2108.05513.pdf) by Vitalik Buterin (EF)
- [Ethereum Data Structures](https://arxiv.org/pdf/2108.05513.pdf)
- [Solidity Lang Docs](https://docs.soliditylang.org/en/v0.8.21/)
- [EIP-1153: Transient Storage](https://eips.ethereum.org/EIPS/eip-1153)
- [Merkle Patricia Tree: storage proof Implementation](https://github.com/mixbytes/zkllvm-mpt-proofs)
- [Rust Implementation of the EVM](https://github.com/bluealloy/revm)
- [REVM gitbook](https://bluealloy.github.io/revm/)
- [Brontes: blockchain analytics pipeline on top of Reth](https://github.com/SorellaLabs/brontes)

#### **Other**

- [fhEVMs: How do they work?](https://medium.com/@whaleslee/fhevms-how-do-they-work-c13ea8a4d4c0)


## Events / Issues

- [Blob Issue Postmortem](https://gist.github.com/benhenryhunter/7b7d9c9e3218aad52f75e3647b83a6cc)






## General Research

- [Absolute Essentials of Ethereum, Excerpt](https://www.routledge.com/Absolute-Essentials-of-Ethereum/Dylan-Ennis/p/book/9781032334189)
- [Updated Ethereum Roadmap, by Vitalik](https://twitter.com/VitalikButerin/status/1466411377107558402?s=20)
- [A Rollup Centric Ethereum Roadmap](https://ethereum-magicians.org/t/a-rollup-centric-ethereum-roadmap/4698)
- [Vitalik: the roads not taken](https://vitalik.ca/general/2022/03/29/road.html)
- [Endgame, by Vitalik](https://vitalik.ca/general/2021/12/06/endgame.html)
- [State of Testnets](https://twitter.com/TimBeiko/status/1628819200696516608?s=20)
- [Intent Based Architectures and Their Risks](https://www.paradigm.xyz/2023/06/intents)
- [Client Bootnode Concerns](https://ethresear.ch/t/execution-consensus-client-bootnodes/14588)
- [Proof of Solvency](https://ethresear.ch/t/snarked-merkle-sum-tree-a-practical-proof-of-solvency-protocol-based-on-vitaliks-proposal/14405)
- [How to Raise the Gas Limit](https://www.paradigm.xyz/2024/03/how-to-raise-the-gas-limit-1)
- [Multidimensional Gas Pricing](https://vitalik.eth.limo/general/2024/05/09/multidim.html)
- [Ethereum has blobs. Where do we go from here?](https://vitalik.eth.limo/general/2024/03/28/blobs.html)
- [Encapsulated vs ystemic complexity in protocol design](https://vitalik.eth.limo/general/2022/02/28/complexity.html)
- [The near and mid-term future of improving the Ethereum network's permissionlessnes and decentralization](https://vitalik.eth.limo/general/2024/05/17/decentralization.html)

### Proof of Stake

- [100 Days After the Merge](https://www.galaxy.com/research/insights/100-days-after-the-merge/)
- [Withdrawals after Shanghai](https://dataalways.substack.com/p/partial-withdrawals-after-the-shanghai)
- [Official Merge Announcement](https://blog.ethereum.org/2022/08/24/mainnet-merge-announcement/)
- [Exploring Inequality in Proof of Stake](https://ethereum.github.io/beaconrunner/notebooks/naiveurn.html)
- [What Happens After Finality in eth2](https://hackmd.io/@prysmaticlabs/finality) by Raul Jordan (Prysmatic)
- [Rocketpool Post-Merge research](https://github.com/rocket-pool/rocketpool-research/tree/master/Post%20Merge)

### Scaling

- [How do layer 2s really differ from execution sharding?](https://vitalik.eth.limo/general/2024/05/23/l2exec.html)
- [L2s as cultural extensions of Ethereum](https://vitalik.eth.limo/general/2024/05/29/l2culture.html)

## Preconfirmations

- [Based Preconfirmations with Multi-round MEV-Boost](https://ethresear.ch/t/based-preconfirmations-with-multi-round-mev-boost/20091)
- [Strawmanning Based Preconfirmations](https://ethresear.ch/t/strawmanning-based-preconfirmations/19695)
- [Bolt Protocol](https://boltprotocol.xyz/)
    - [Documentation](https://chainbound.github.io/bolt-docs/)
    - [Github Repository](https://github.com/chainbound/bolt)

### Data 

- [A note on data availability and erasure coding](https://github.com/ethereum/research/wiki/A-note-on-data-availability-and-erasure-coding)
- [PeerDAS: a simpler DAS approach using battle-tested p2p components](https://ethresear.ch/t/peerdas-a-simpler-das-approach-using-battle-tested-p2p-components/16541)
- [Verkle Trees for Statelessness](https://verkle.info/)
- [EIP-4444: Bound Historical Data in Execution Clients](https://eips.ethereum.org/EIPS/eip-4444)

## Consensus

#### **Design**

- [Ethereum Consensus Spec](https://github.com/ethereum/consensus-specs)
- [Casper the Friendly Finality Gadget](https://arxiv.org/abs/1710.09437)
- [Combining GHOST and Casper](https://arxiv.org/abs/2003.03052)
    - [elopio's annotations](https://elopio.keybase.pub/papers/2020-combining_ghost_and_casper.pdf)
- [Beacon Chain Casper Mini-Spec](https://ethresear.ch/t/beacon-chain-casper-mini-spec/2760/17)
- [zkCasper: SNARK based scheme for verifying the Ethereum's Casper FFG consensus proofs](https://research.polytope.technology/zkcasper)
- [Beacon Chain Casper Mini-Spec](https://ethresear.ch/t/beacon-chain-casper-mini-spec/2760/17)
- [Ethereum Inactivity Leak](https://eth2book.info/capella/part2/incentives/inactivity/)
- [Don't overload Ethereum's consensus](https://vitalik.eth.limo/general/2023/05/21/dont_overload.html)

#### **Attacks**

- [Long Range Attacks on PoS](https://www.youtube.com/watch?v=-uxHoEfxXC4)
- [Two Attacks on Proof-of-Stake GHOST/Ethereum](https://arxiv.org/pdf/2203.01315.pdf)
- [Three Attacks on Proof-of-Stake Ethereum](https://arxiv.org/abs/2110.10086)
- [Balancing Attack on Gasper](https://ethresear.ch/t/a-balancing-attack-on-gasper-the-current-candidate-for-eth2s-beacon-chain/8079)
- [Mitigating Balancing Attacks on LMD GHOST](https://notes.ethereum.org/@vbuterin/lmd_ghost_mitigation)
- [Discouragement Attacks](https://eth2book.info/capella/part2/incentives/rewards/#discouragement-attacks)
- [Vitalik on Discouragement](https://github.com/ethereum/research/blob/master/papers/discouragement/discouragement.pdf)

#### **Discussions**

- [Vitalik: Sticking to 8192 signatures per slot post-SSF](https://ethresear.ch/t/sticking-to-8192-signatures-per-slot-post-ssf-how-and-why/17989)
- [Solo Stakers: The backbone of Ethereum](https://blog.rated.network/blog/solo-stakers)
- [Collecting Signatures for Faster Finality](https://ethresear.ch/t/horn-collecting-signatures-for-faster-finality/14219)
- [Maximum Viable Security: A New Framing for Ethereum Issuance](https://ethresear.ch/t/maximum-viable-security-a-new-framing-for-ethereum-issuance/19992)

**May 12, 2023, Ethereum Consensus Issues**

- [tweet one](https://twitter.com/potuz1/status/1657031082749861891?s=20)
- [tweet two](https://twitter.com/TaylerUSA/status/1656840323392208899)




## Block Production

- [Proposer Boost Considerations](https://notes.ethereum.org/@casparschwa/H1T0k7b85) by Caspar Schwarz-Schilling (RIG/EF)
- [Ethereum Builder API Specs](https://ethereum.github.io/builder-specs/)
- [Proposer/block builder separation-friendly fee market designs](https://ethresear.ch/t/proposer-block-builder-separation-friendly-fee-market-designs/9725) by Vitalik Buterin (EF)
- [Two-slot proposer/builder separation](https://ethresear.ch/t/two-slot-proposer-builder-separation/10980) by Vitalik Buterin (EF)
- [Concurrent Block Proposers in Ethereum](https://ethresear.ch/t/concurrent-block-proposers-in-ethereum/18777)
- [Time to Bribe: Measuring Block Construction Markets](https://eprint.iacr.org/2023/760.pdf)
- [Retroactive Proposer Rewards](https://notes.ethereum.org/@casparschwa/S1vcyXZL9) by Caspar Schwarz-Schilling (RIG/EF)
- [Single Secret Leader Election](https://eprint.iacr.org/2020/025.pdf) Boneh et al. (2020)
- [Current CrList Proposal](https://notes.ethereum.org/@fradamt/H1ZqdtrBF) by Francesco D'Amato
- [(Un-)Timeliness in PoS Ethereum](https://notes.ethereum.org/@casparschwa/ByHu1XZUq) by Caspar Schwarz-Schilling (RIG/EF)
- [ePBS: Bypassing Relayer](https://hackmd.io/@ttsao/bypassing-relayer)
- [ePBS Annotated Validator Spec](https://hackmd.io/@ttsao/epbs-annotated-validator)

### Censorship (Resistance)

- [PBS Censorship Resistance](https://notes.ethereum.org/@vbuterin/pbs_censorship_resistance)
- [State of research: increasing censorship resistance of transactions under proposer/builder separation (PBS)](https://notes.ethereum.org/@vbuterin/pbs_censorship_resistance) by Vitalik Buterin (EF)
- [PBS Censorship-Resistance Alternatives](https://notes.ethereum.org/@fradamt/H1TsYRfJc) by Francesco D'Amato (EF)
- [Current crList Proposal](https://notes.ethereum.org/Dh7NaB59TnuUW5545msDJQ)







### EIP-3675: Proof of Stake

- [EIP-3675: Upgrade consensus to Proof-of-Stake](https://eips.ethereum.org/EIPS/eip-3675)
- [Eth Withdrawals FAQ](https://notes.ethereum.org/@launchpad/withdrawals-faq#ETH-Withdrawals-FAQ)
- [100 Days After the Merge](https://www.galaxy.com/research/insights/100-days-after-the-merge/)
- [Withdrawals after Shanghai](https://dataalways.substack.com/p/partial-withdrawals-after-the-shanghai)
- [Official Merge Announcement](https://blog.ethereum.org/2022/08/24/mainnet-merge-announcement/)
- [Exploring Inequality in Proof of Stake](https://ethereum.github.io/beaconrunner/notebooks/naiveurn.html) by Barnabe Monnot (RIG/EF)
- [What Happens After Finality in eth2](https://hackmd.io/@prysmaticlabs/finality) by Raul Jordan (Prysmatic)
- [Understanding Eth2 Slashing Preventative Measures](https://www.bloxstaking.com/blog/ethereum-2-0/understanding-eth2-slashing-preventative-measures/)

### (Dank)Sharding

Danksharding is how Ethereum becomes a truly scalable blockchain, but there are several protocol upgrades required to get there. Proto-Danksharding is an intermediate step along the way. Both aim to make transactions on Layer 2 as cheap as possible for users and should scale Ethereum to >100,000 transactions per second.

- [Ethereum Roadmap: Danksharding](https://ethereum.org/en/roadmap/danksharding/)
- [Danksharding](https://notes.ethereum.org/@dankrad/new_sharding)
- [Polynya on Danksharding](https://polynya.medium.com/danksharding-36dc0c8067fe)
- [Nightshade: Near Protocol Sharding Design](https://near.org/downloads/Nightshade.pdf)
- [The Tie: Danksharding](https://research.thetie.io/danksharding-ethereums-scalability-killer/)
- [Proto-Danksharding FAQ](https://notes.ethereum.org/@vbuterin/proto_danksharding_faq) by Vitalik Buterin (EF)
- [“Dude, what’s the Danksharding situation?” Workshop](https://youtu.be/e9oudTr5BE4) by Dankrad Feist & Vitalik Buterin (EF)

**EIP-4844 Proto-Danksharding**

- [EIP-4844](https://eips.ethereum.org/EIPS/eip-4844)
- [EIP-4844: Shard Blob Transactions](https://eips.ethereum.org/EIPS/eip-4844)
- [4844 Readiness Checklist](https://github.com/ethereum/pm/blob/master/Breakout-Room/4844-readiness-checklist.md#client-implementation-status)

### Account Abstraction

- [EIP-2938: Account Abstraction](https://eips.ethereum.org/EIPS/eip-2938)
- [ERC-4337: Account Abstraction Using Alt Mempool](https://eips.ethereum.org/EIPS/eip-4337)
- [Account Abstraction in a Multichain Landscape - Part 1: Addresses](https://safe.mirror.xyz/4GcGAOFno-suTCjBewiYH4k4yXPDdIukC5woO5Bjc4w)
- [What's in an Account?](https://erc4337.mirror.xyz/vYwclVbG6CR1o8DOCWDj8cFVfFSJ07FhWTDgQ5NQROY)
- [EIP-7702](https://github.com/ethereum/EIPs/blob/9e04cf1094eae64172ce04e0a04ec40f1edbdc5d/EIPS/eip-7702.md)
- [EIP-7702 Discussion](https://ethereum-magicians.org/t/eip-set-eoa-account-code-for-one-transaction/19923)


### Chain Abstraction

- [Chain abstraction landscape](https://newsletter.asxn.xyz/p/chain-abstraction-landscape)
- [ERC-7683: Cross Chain Intents](https://www.erc7683.org/)
- [Keystore Rollup](https://safe.global/blog/keystore-rollup-smart-account-interoperability)




 




## TEEs

- [Build FHE Coprocessor on TEE](https://collective.flashbots.net/t/build-fhe-coprocessor-on-tee/3697)