---
title: "Fusion"
description: "Nuclear Fusion, second generation nuclear energy source (and weapon)"
page-layout: full
---


## Fusion Weapon: Overview

A thermonuclear weapon, fusion weapon or hydrogen bomb (H bomb) is a second-generation nuclear weapon design. Its greater sophistication affords it vastly greater destructive power than first-generation nuclear bombs, a more compact size, a lower mass, or a combination of these benefits. Characteristics of nuclear fusion reactions make possible the use of non-fissile depleted uranium as the weapon's main fuel, thus allowing more efficient use of scarce fissile material such as uranium-235 $(^{235}U)$ or plutonium-239 $(^{239}Pu)$

The first full-scale thermonuclear test was carried out by the United States in 1952; the concept has since been employed by most of the world's nuclear powers in the design of their weapons.

Modern fusion weapons consist essentially of two main components: a nuclear fission primary stage (fueled by $^{235}U$ or $^{239}Pu$) and a separate nuclear fusion secondary stage containing thermonuclear fuel: the heavy hydrogen isotopes deuterium and tritium, or in modern weapons lithium deuteride. For this reason, thermonuclear weapons are often colloquially called hydrogen bombs or H-bombs.

## Energy Sources

### Breakthroughs

#### December 5, 2023 (announced Dec. 13)

- [Press Conference: Secretary Granholm & DOE leaders Announced Fusion Breakthrough by DOE National Lab](https://www.youtube.com/watch?v=K2ktAL4rGuY)
- [LLNL Release](https://www.llnl.gov/news/igniting-future-hundreds-gather-celebrate-historic-fusion-achievement)
- [LLNL Video](https://www.youtube.com/watch?v=71gqaFoix1w)

The U.S. Department of Energy (DOE) and DOE’s National Nuclear Security Administration (NNSA) today (Dec. 13) announced the achievement of fusion ignition at Lawrence Livermore National Laboratory (LLNL) — a major scientific breakthrough decades in the making that will pave the way for advancements in national defense and the future of clean power. On Dec. 5, a team at LLNL’s National Ignition Facility (NIF) conducted the first controlled fusion experiment in history to reach this milestone, also known as scientific energy breakeven, meaning it produced more energy from fusion than the laser energy used to drive it. 

#### August 6, 2023 

[US scientists repeat fusion ignition breakthrough for 2nd time](https://www.reuters.com/business/energy/us-scientists-repeat-fusion-power-breakthrough-ft-2023-08-06/)