---
title: Cosmology
description: Astrophysics and Cosmology
---

## Projects

- [NASA Radio Telescope on dark side of the moon](https://www.jpl.nasa.gov/news/lunar-crater-radio-telescope-illuminating-the-cosmic-dark-ages)

## General Research

- [The Pseudo-Conformal Universe: Scale Invariance from Spontaneous Breaking of Conformal Symmetry](https://arxiv.org/abs/1106.1428)
- [Einstein, Barcelona, Symmetry & Cosmology: The Birth of an Equation for the Universe](https://arxiv.org/pdf/2309.02477.pdf)
- [Seeing the Gravitational Wave Universe](https://arxiv.org/abs/2211.05148)
- [NASA Selects 5 Missions for 2024 Total Solar Eclipse](https://www.nasa.gov/feature/goddard/2023/sun/science-in-the-shadows-nasa-selects-5-experiments-for-2024-total-solar-eclipse)
- [James Webb Images](https://esawebb.org/images/)
- [Planck 2018 Results, Cosmological Parameters](https://arxiv.org/abs/1807.06209)
- [Webb Telescope finds surprising evidence of well-formed early galaxies](https://twitter.com/WKCosmo/status/1629868261490737153?s=20)
- [Holography of the Photon Ring](https://arxiv.org/abs/2205.05064)
- [Sun blasts out highest-energy radiation ever recorded, raising questions for solar physics](https://www.space.com/sun-blasts-highest-energy-radiation-ever-recorded-raising-questions-solar-physics)
- [Discovery of Gamma Rays from the Quiescent Sun with HAWC](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.131.051201)
- [10 galaxies that existed just 830 million years after the Big Bang](https://esawebb.org/images/aspire1/)
The seven galaxies highlighted in [this image](https://esawebb.org/images/protocluster-1/) from the NASA/ESA/CSA Telescope have been confirmed to be at a distance that astronomers refer to as redshift 7.9, which correlates to 650 million years after the big bang. This makes them the earliest galaxies yet to be spectroscopically confirmed as part of a developing cluster.

## Dark Matter and Dark Energy

- [Interacting Dark Matter - Phenomenology and Implications for Cosmology](https://www.youtube.com/watch?v=lzUNr-0E8Us)
- [New shape of parity-violating graviton non-Gaussianity](https://arxiv.org/abs/2303.05178) | [Explainer](https://twitter.com/MMylova/status/1634015492775002112?s=20)
- [Cosmic Dark Matter Web Detected in Coma Cluster](https://subarutelescope.org/en/results/2024/02/07/3367.html)

## Big Bang

- [Mathematicians Attempt to Glimpse Past the Big Bang](https://www.quantamagazine.org/mathematicians-attempt-to-glimpse-past-the-big-bang-20240531/)
- [On the initial singularity and the extendability of flat quasi-de Sitter spacetimes](https://link.springer.com/article/10.1007/JHEP10(2023)182)