---
title: Series 65
---

## Notes

Under the Uniform Securities Act, an investment adviser does not need to register in a state if the adviser has no place of business in the state and only has clients in the state that are certain entities such as broker-dealers, other investment advisers, federal covered advisers, banks, insurance companies, and employee benefit plans with assets no less than $1,000,000. Such an adviser may also have up to five clients not among these entities without registering.

A broker-dealer who has no place of business in a state is allowed to have institutional clients in the state without having to register in that state. Institutional clients include other broker-dealers, banks, pension trusts, and other financial institutions.

In general, advisers managing an investment portfolio should be compensated as a percentage of assets under management over a specified time period. However, an adviser is allowed to charge certain "sophisticated" investors an advisory fee based on portfolio performance vs. an index. Among these investors are people or businesses with over $1,000,000 in assets under management, and registered investment companies, such as mutual funds.

The formula for the Capital Asset Pricing Model (CAPM) is given by the following: 
$ Return on Stock = Risk Free Rate + Beta of Stock x (Return on Market - Risk Free Rate) $

Several arrangements can lead to an adviser being deemed to have custody of an account, including having signatory power over a client's checking account, serving as a trustee of a client's trust fund, and obtaining advisory fees by directly billing client custodians without effective oversight by the client or an independent party.

The Securities Exchange Act of 1934 allows the SEC to require corporations to file financial information on a regular basis.  The SEC currently requires an annual report, known as a 10-K, to be filed within 60 to 90 days of the end of each company's fiscal year.  The SEC also requires quarterly reports, known as 10-Q's, to be filed within 40 to 45 days of the end of each fiscal quarter (three-month period). 