---
title: Silent Weapons for Mass Destruction
---

## Context

This document was discovered in a surplus copier purchased from Boeing Aircraft in 1986. Reveals details of a plan, hatched in the mebryonic days of the Cold War, which called for the control of the masses through manipulation of industrym peoples' pastimes, education and political leanings. It called for a quiet revolution, pitting brother against brother, adn divertng the public's attention from what is really going on.

A link to the full text will be made available in due time. For now, I will record particuallry notable excerpts from the document, and perhaps some commentary throughout.

### Security

> you have qualified for this project because fo your ability to look at human society with cold objectivity, and yet analyze and discuss your observations and conclusions with others of similar intellectual capacity without a loss of discretion or humility. Such virtues are exercised in your own best interest. Do not deviate from them.

## Historical Introduction

Silent weapon tech evolved from Op Research (O.R.), a strategic and tactical methodology developed under the military management in England during WW2. The original purpose of OR was to study the strategic and tactical problems of air and land defense with the objective of effective use of limited military resources against foreign enemies (i.e. logistics).

It was soon recognized that the same methodology might be useful for totally controlling a society. but better tools were necesary.

Social engineering requires the correlation of a great amount of constantly changng economic data, so a high speed computerized data processing system was necessary which could race ahead of society.

- 1946: The electrnic computer invented in 1946 by J. Presper Eckert
- 1947: Simplex method of linear programming developed by George B. Dantzig
- 1948: Invention of the transistor by Bardeen, Brattain, and Shockley promised expansion of computer field by reducing space and power requirements.

These three inventions conviced the elite thay were capable of controlling society.

Rockefellar Foundation started with a 4-yr grant to Harvard, funding a study of the structure of the American economy. A year later, the USAF joined in.

## Energy

> Methematics is the primary energy source.

> The bookkeeper can be king if the public can be kept ignorant of the methodology of the bookkeeping.

> A nation or world of people who will not use their intelligence are no better than animals who do not have intelligence. Sucha  people are beasts of burden and steaks on the table by choice and consent.

> ... it was decided to privately wage a quiet war against the American public with an ultimate objective of permanently shifting the natural and social energy (wealth) of the undisciplined and irresponsible many into the hands of the self-disciplined, responsible,and worthy few.

> yet is makes an unmistakeable 'noise', causes unmistakeable physical and mental damage, and unmistakably interferes with daily social life. 1.o. unmistakable to a trained observerm one who knows what to look for.
> The public cannot comprehend this weapom, and therefore cannot believe that they are being attacked and subduod by a weapon.
> The public might insticively feel that something is wrong, but because of the technical nature of the silent weapon, they cannot express their feelings in a rational way, or handle the problems with intelligence Therefore, they do not know how to cry for help, and do not know how to associate with others to defend themselves against it.

$\dots$

> The silent weapon is a type of biological warfare,

> Give me control over a nation's currency, and I care not who makes its laws. - Mayer Amschel Rothschild (1743-1812)

Page 4: 1952: high level meeting of the elite was held to determine the next phase of of social operations research.

Harvard project 1953 suggested the feasability of of economic social engineering.

### Page 4

- unlocking unlimited sources of fusion atomic energy from the heavy hydrogen in sea water and the consequent availability of unlimited social power became a possiblity only decades away.

*The combination was irresistable. The quiet war was wuietly declared by the international elite at a meeting held in 1954.
Page 6, important.

### Disruptive Introduction of the Silent Weapom



### Mr. Rothchild's Energy Discovery

Influence, and control of over people as applied to economics:

> When you assume the appearance of power, people soo give it to you.

- Excss paper energy credits - (paper inductance/inflation)

## Breakthough


Energyy is a the key to all activity on the face of the earth. It followd that in order to attain a monolpoly of energym raw materials, goods, and services and to establish a world system of slave labor, it is necssary to to have a first strike capablity in the field of economics.

### The work begun a Harvard in 1948 (page 8)

The speed at with which they can communicate their warning to the public will largely depend upon how effective we have been at controlling the the media, subverting education, and keeping the public distracted with matters of no real importance.

## The Economica Model