---
title: UAP 
---

- [slide deck](https://docs.google.com/presentation/d/1p0OU3k0EM4z7wFYwadJHMudykwMgPzO3B8qgoPjb3sg/edit#slide=id.gf6bde983ec_0_200)

## 1947 Project Paperclip 

- General George F. Shulgen send a memo to General Nathan Twining in October 1947 stating that the saucers may be made with materials "of composite construction" that used "various combinations of metals" and that were fabricated by "unusual methods" to achieve "extreme lightweight." He also recommended collecting intelligence on the current whereabouts of the Horton Brothers, missing NAZI aeronautical engineers and aircraft designers.

- National Security Act: War Department > DoD, creation of CIA and NSA

- Roswell: Captain Robert B. McLaughlin US Navy "It was a metal-like fabric that was indestrucable"

- Roy Plunkett invented Teflon accidentally at DuPont Deepwater Facility 1938 

- Shape Retention Alloys 1959: Nitinol Wire

- Mylar aka BoPET; Polyester Film; developed mid 1950s DuPont, Imperial Chemical Industries and Hoechst
    - [dupont](https://en.wikipedia.org/wiki/DuPont#History)
    - [imperial checmicals](https://en.wikipedia.org/wiki/Imperial_Chemical_Industries)
    - [Hoechst](https://en.wikipedia.org/wiki/Hoechst_AG)