---
title: Firearms
---

## Resources

**NFA Gun Trust**

- [advantages](https://www.nationalguntrusts.com/products/buy-nfa-gun-trust?gad_source=1&gclid=Cj0KCQiA5fetBhC9ARIsAP1UMgGXp71z9fdlgEjk4iS1n0_pHQH27Cn0WpmoiEQpEyhnfmw174K5MQoaAhZqEALw_wcB)
- [how to register](https://www.nationalguntrusts.com/pages/how-to-submit-your-nfa-gun-trust-and-your-atf-paperwork-to-the-atf?gad_source=1&gclid=Cj0KCQiA5fetBhC9ARIsAP1UMgEj3hJz5sHKn-sUa9feYkcL9p8cRCgeJmQvfhwNtRyFjpm5SXSgBLEaAipoEALw_wcB)

### Ammo

#### **Subsonic**

- [link](https://www.usacarry.com/subsonic-ammo-self-defense-concealed-carry/)

## My Setup

#### **Host**: 

FN 509 (compact or midsize?) tactical

- The muzzle is target-crowned with a 1/2×28” thread cap and readily accepts most suppressors and muzzle devices.

### Silencer

**Top Pick**

- [silencerCo Spectre 9](https://silencerco.com/silencers/spectre-9/) 

Others

- obsidian rugged silencer
- silencerCo Octane 9
- [silencerCo omega 9k](https://silencerco.com/silencers/omega-k/) [video](https://www.youtube.com/watch?v=cHMmMwakhRM)
- [silencerCo product lineup (including spectre)](https://www.youtube.com/watch?v=jN58QI8V274)

#### **Silencer Info**

- [Silencer Customer Info]
    - can purchase as an individual or under an NFA trust
- [Silencer Legality](https://silencerco.com/yes-silencers-are-legal/)
- [How to buy](https://silencerco.com/how-to-buy/)
- need an FFL for it to be shipped [info](https://freedom-weapons.com/checkout)
- [do so here](https://eforms.atf.gov/login;referrer=%2Fhome)

> You have purchased an item that must be shipped to a Federal Firearms License holder (FFL). Before making a selection, contact the FFL and verify that they can accept your shipment prior to completing your purchase. [source](https://freedom-weapons.com/checkout)

### Accessories

Supressor Cover (to protect from heat). Though neither of the below look to fit the 

- [SilentCo high temp cover](https://silencerco.com/shop/high-temp-suppressor-cover/)
- [SilentCo Extreme high temp cover](https://eforms.atf.gov/)

Order Silencer to Dealer, Need to fill out an [ATF Form 4](https://www.silencercentral.com/blog/atf-form-4-understanding-nfa-transfers/#:~:text=The%20ATF%20Form%204%20is,dealer%20selling%20to%20a%20customer.) for dealer to sell to you.

ATF Form can be complete [here](https://eforms.atf.gov/)

- subsonic 9mm ammo