---
title: Geometry
---

## Reads

- [New approaches to Circle Packing in a Square](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=e5bde5f6ca9eb85435908376d63d5f7f634f9309)
- [Introduction to Homotopy Theory - Martin Arkowitz](https://www.researchgate.net/publication/251415308_Introduction_to_Homotopy_Theory)
- [Differential Forms in Algebraic Topology](https://www.maths.ed.ac.uk/~v1ranick/papers/botttu.pdf)
- [Quaternion Algebras - John Voight](https://math.dartmouth.edu/~jvoight/quat-book.pdf)
- [Perfectoid Spaces](https://arxiv.org/abs/1111.4914)

### Donaldson Theory

Donaldson theory is a branch of mathematics that is concerned with the topology of four-dimensional manifolds. It is named after Simon Donaldson, a British mathematician who made significant contributions to the field in the 1980s.

The central problem in Donaldson theory is to understand the topology of four-dimensional manifolds using differential geometry and algebraic topology. Specifically, the theory focuses on the study of vector bundles and connections on these manifolds, and how they can be used to classify different types of four-dimensional manifolds.

One of the key results in Donaldson theory is Donaldson's theorem, which states that the intersection form of a smooth, closed, simply-connected four-dimensional manifold can be recovered from its Seiberg-Witten invariants. The Seiberg-Witten invariants are a set of numbers that can be associated with a four-dimensional manifold and its spin-c structure. They were introduced by Edward Witten and Nathan Seiberg in the mid-1990s and have proven to be a powerful tool in the study of four-dimensional manifolds.

Donaldson theory has applications in a variety of fields, including physics, where it has been used to study the topology of spacetime in string theory and other areas of theoretical physics. It has also had significant impact in pure mathematics, inspiring further research in the fields of algebraic geometry, topology, and differential geometry.