---
title: Blockchain != Privacy
author: Brendan McCaffrey
date: 2022-07-24
categories: [crypto, blockchain, privacy]
---

## Introduction

There exists a common misconception that privacy is an inherent feature to blockchain protocols. Below, I explain how current blockchain implementations do *not* guarantee privacy. In fact, today's blockchain protocols introduce an *unprecedented* ability for the powerful to surveil the weak.

## Cypherpunks

The commonality of this misconception may be explained, at least in part, by the founding culture associated with blockchain technology. Blockchain technology emerged in the late 20th century from several key innovations in the field of cryptography, the same field from which the manifestation of informational privacy (encryption), was pioneered. 

The *Cypherpunks* were a group of cryptographic enthusiasts who advocated for the use of cryptography and similar methods as ways to achieve societal and political change. Founded in the early 1990s, the movement has been most active during the 1990s “cryptowars” and following the 2011 internet spring. The Cypherpunks forecasted the coming age of digital information, and saw cryptography as a means of preserving fundamental individual rights, such privacy and self-sovereignty. Members of this group include Roger Dingledine, co-founder of the Tor Project, Julian Assange, founder of Wikileaks, and perhaps most notably, Satoshi Nakamoto, the pseudonymous creator of Bitcoin. 

Many of the protocols, algorithms, and applications developed by the Cypherpunks were centered around privacy. Bitcoin was not.

## The Genesis Case Study, Bitcoin

#### Pseudonymity != Anonymity

In October of 2008, an [email](https://www.metzdowd.com/pipermail/cryptography/2008-October/014810.html) from Satoshi Nakamoto was sent to the [cypherpunk](https://en.wikipedia.org/wiki/Cypherpunk#:~:text=For%20a%20time%2C%20the%20cypherpunks,referred%20to%20as%20a%20mailbomber.) email list, titled "Bitcoin P2P e-cash paper".

Participation in the Bitcoin network only requires a public/private keypair (ECDSA for Version 1). There is no support for "accounts" or "profiles" which include other metadata, such as name, email, address, etc. Thus, the Bitcoin network is inherently pseudonymous, where the pseudonyms are Bitcoin addresses (smaller hashed versions of the public key). On the Bitcoin network, all transactions are published to and stored on the public ledger (this allows for Bitcoin's distributed consensus), making intra-network forensics trivial. I.e. it is trivial to retreive the entire financial history of `1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa`, and verifiably gather information on all transactions involving this address, neighboring addresses, etc.

Still, it remains theoretically possible to use Bitcoin anonymously. A Bitcoin user may rely on proper operational security (OpSec) techniques to ensure his/her Bitcoin pseudonym remains entirely disjunct from his/her "real" or government identity. In the early days of Bitcoin, the majority of participants did successfully maintain anonymity through proper OpSec - accessing the network through VPNs, public WiFi hotspots, remote SSH tunneling, etc. 

One factor contributing to the early success of anonymity was the fact that the earliest users of Bitcoin were often well-versed in digital OpSec. Early users generated and custodied their keypairs on a local and/or secure machine because they were familiar with ECDSA encryption, and they executed Bitcoin payments under anonymous identities on secure e-commerce platforms, accessed through secure dark-web browsers, like Tor. 

Another factor contributing to Bitcoin's early privacy, however, is that the technology remained siloed in it's earliest years, segregated from regulated financial infrastructure, and "under the radar" of intelligence organizations. For example, the creator and operator of one of the most prolific darknet Bitcoin marketplaces, the Silk Road, was identified and arrested in 2013, after just two years of successfully maintaining anonymity through pseudonymity.

The key realization here is that Bitcoin offers a *permissionless* and *censorship-resistant* method of transacting value - nothing else. In order to protect one's identity in the applications of Bitcoin, one must rely on the other components of the technology stack to provide the privacy guarantees to maintain anonymity. Any if any *single* OpSec mistake were to be made, *everything* about the user's pseudonym could be revealed.

The consequences of Bitcoin's intra-network transparency were difficult to identify in its early life - Bitcoin *seemed* privacy-preserving. Fast-forward 13 years, however, and the ability to surveil couldn't be more clear. 

According to recent reports, approximately 46 million Americans (~22% of US population) own some form of Bitcoin. Out of this, it's estimated that at least 8/10 purchased and/or hold their Bitcoin through a KYC'd account on a custodied platform, such as Coinbase, Crypto[dot]com, or Robinhood. From this alone, the Bitcoin-specific financial information off nearly all US persons (not just the ones with KYC'd accounts) is effectively public. These entities are obligated to release Customer data if provoked on legal grounds, and sophisticated players can retreive this information even in the case Coinbase were to remain non-compliant.

The Bitcoin protocol, when integrated with 3rd party KYC applications (as it is today and will be throughout the foreseeable future), is a near-perfect protocol for financial surveillance.

## Turing-Complete Blockchains

#### Turing-Complete Computation + Weak Privacy = Infinite Surveillance

In the section above, I have only discussed the (lack of) privacy offered by Bitcoin - I have not argued for whether these facts are "good" or "bad". Perhaps this was all part of Satoshi's grand vision, and it is ethically optimal for financial settlement infrastructure to offer complete transparency. I will continue to avoid the question of good or bad as it pertains to Bitcoin, because I, myself, am not certain in my stance.

When the question extends to Turing-Complete networks, however, I have enough convinction to argue that zero-privacy guarantees are suboptimal.

In 2014, a novel smart contract based, Turing-Complete blockchain protocol called Ethereum was [introduced](https://ethereum.org/669c9e2e2027310b6b3cdce6e1c52962/Ethereum_Whitepaper_-_Buterin_2014.pdf). Ethereum allowed for arbitrary code executions, enabling application development beyond just the transfer of the native asset. Over the past several years, there has been an explosion of Ethereum application development. From domain name services to gaming/social apps, these applications span beyond just payments - logging data, provoking external program executions, developing on-chain reputation/identity, and establishing organizational structures of accounts. 

> Power tends to corrupt; absolute power corrupts absolutely

Just like Bitcoin, all data associated with Ethereum transactions, by default, are stored on the public ledger in plaintext for anyone to view. With countless "decentralized" profile-based applications, the connection between an on-chain pseudonym and corresponding government identity is increasingly inevitable. Additionally, every action, transaction, and application interaction performed on Ethereum further develops the user's on-chain reputation, permanently documented on Ethereum's immutable global ledger. Even if the goal was not to maintain a distinction between on-chain and "real" identities, a lack of privacy for the on-chain identity inevitably approaches a lack of privacy in real life.

- Calling an Uber
- Buying an engagement ring (or organizing a surprise party)
- Any healthcare-related activites

Upon meditating on the consequences of an extension of this paradigm, one may encounter a seemingly endless array of dystopian scenarios.

## Conclusion

As Vitalik Buterin [voiced](https://blog.ethereum.org/2016/01/15/privacy-on-the-blockchain), the "Holy Grail" blockchain technology would allow users to benefit from the security of a blockchain, using a decentralized network to process the transactions, but "encrypting" the data in such a way that even though everything is being computed in plain sight, the underlying "meaning" of the information is completely obfuscated.

Today's blockchains lack privacy because distributed consensus mechanisms rely on the verifiability of blockchain data, which currently requires plaintext data. There exist exciting fields of cryptographic research in pursuit of solving this issue - my personal favorites are Zero Knowledge Proofs (ZKPs) and Fully Homomorphic Encryption (FHE).

However, the integration of privacy-enabling primitives is time-sensitive. Deferring essential features to later appensions to the technology often results in [weaker guarantees](https://cryptoslate.com/circle-blacklists-all-tornado-cash-eth-addresses-effectively-freezing-usdc/) of the respective features. Additionally, as societal adoption increases over time, the community is more likely to [become distanced](https://www.theglobeandmail.com/canada/article-if-you-dont-know-youre-a-slave-how-do-you-fight-to-be-free/) from [the ethos](https://web.cs.ucdavis.edu/~rogaway/papers/moral-fn.pdf) from which the technology was birthed.


> From my earliest days I had a passion for science. But science, the exercise of the supreme power of the human intellect, was always linked in my mind with benefit to people. I saw science as being in harmony with humanity. I did not imagine that the second half of my life would be spent on efforts to avert a mortal danger to humanity created by science.

I hope the topic of privacy remains at the forefront of blockchain research. We must actively ensure that the innovation of distributed computing serves to benefit society: for this is not guaranteed.