---
title: ZK/FHE
table-of-contents: true
---

## General



## ZK Blockchain Projects 

- [Modulus](https://www.modulus.xyz/)
- [EZKL](https://ezkl.xyz/)

### Nil Foundation

- [zkLLVM Circuit Compiler](https://github.com/NilFoundation/zkLLVM)
- [zkLLVM Template](https://github.com/NilFoundation/zkllvm-template)

### Succinct

- [SP1: Open Source zkVM by Succint Labs](https://blog.succinct.xyz/introducing-sp1/)
- [SP1 Book](https://succinctlabs.github.io/sp1/)
- [SP1 Github](https://github.com/succinctlabs/sp1)
- [awesome SP1 repo](https://github.com/gakonst/awesome-sp1)

### Reef: A system for generating zero-knowledge proofs that a committed document matches or does not match a regular expression

- [github](https://github.com/eniac/Reef)
- [paper](https://eprint.iacr.org/2023/1886)

### Axiom: A zk coprocessor for Ethereum

- [Twitter](https://twitter.com/axiom_xyz)
- [Website](www.axiom.xyz)
- [Demo](demo.axiom.xyz)
- [Docs](docs.axiom.xyz)

### RiscZero: Making generalizable computer architecture for ZK 

- [website](https://www.risczero.com/)
- [docs](https://dev.risczero.com/)
- [github](https://github.com/risc0/risc0)

### Bonsai: A zk blockchain project

- [docs](https://dev.bonsai.xyz/)
- [starter template](https://github.com/risc0/bonsai-foundry-template)

### ZKPoEx: Zero knowledge proof of exploit 

- [twitter](https://twitter.com/zkpoex)



## FHE Blockchain Stuff

- [Vitalik on FHE](https://vitalik.ca/general/2020/07/20/homomorphic.html)
- [Exploring the Recent Rise of FHE in the Blockchain Industry](https://medium.com/@mustafa.hourani/explaining-the-recent-rise-of-fully-homomorphic-encryption-in-the-blockchain-industry-c7081fa05458)
- [fhEVMs: How do they work?](https://medium.com/@whaleslee/fhevms-how-do-they-work-c13ea8a4d4c0)
- [ArkStream Capital: Why we invest in the FHE track](https://www.coinlive.com/news/arkstream-capital-why-we-invest-in-the-fhe-track)

### Zama

- [website](https://www.zama.ai/)
- [documentation](https://docs.zama.ai/homepage/)
- [github](https://github.com/zama-ai)

**Zama Concrete, FHE Compiler**

- [documentation](https://docs.zama.ai/concrete)
- [The architecture of concrete](https://www.zama.ai/post/the-architecture-of-concrete-zama-fully-homomorphic-encryption-compiler-leveraging-mlir)

**Zama fhEVM**

- [fhEVM](https://github.com/zama-ai/fhevm/blob/main/fhevm-whitepaper.pdf)
- [TFHE.sol](https://github.com/zama-ai/fhevm/blob/main/lib/TFHE.sol)
- [Fhenix Blockchain](https://twitter.com/FhenixIO)


