---
title: 9/11
description: Never forget
---

## Overview 

**Hijackers** 

American Airlines Flight 11: One World Trade Center, North Tower

Mohamed Atta (Egyptian), Abdulaziz al-Omari (Saudi Arabian), Wail al-Shehri (Saudi Arabian), Waleed al-Shehri (Saudi Arabian), Satam al-Suqami (Saudi Arabian).

United Airlines Flight 175: Two World Trade Center, South Tower

Marwan al-Shehhi (United Arab Emirates), Fayez Banihammad (United Arab Emirates), Mohand al-Shehri (Saudi Arabian), Hamza al-Ghamdi (Saudi Arabian), Ahmad al-Ghamdi (Saudi Arabian)

American Airlines Flight 77 (into the Pentagon)

Hani Hanjour (Saudi Arabian), Khalid al-Mihdhar (Saudi Arabian), Majed Moqed (Saudi Arabian), Nawaf al-Hazmi (Saudi Arabian), Salem al-Hazmi (Saudi Arabian)

United Airlines Flight 93: Shanksville, Pennsylvania

Ziad Jarrah (Lebanese), Ahmed al-Haznawi (Saudi Arabian), Ahmed al-Nami (Saudi Arabian), Sa'id al-Ghamdi (Saudi Arabian)

A 4 minute overview of the insanity of the official story, on [twitter](https://twitter.com/libertyblitz/status/1701252432360337712?s=46&t=mKfMvA9kDRr3LdnI-MLdig)


## Resources

[9/11 Comission Report](https://govinfo.library.unt.edu/911/report/911Report_Exec.htm)

[Saudi Arabia Faces the Missing 28 Pages](https://www.wilsoncenter.org/sites/default/files/media/documents/publication/saudi_arabia_faces_the_missing_28_pages.pdf)

[Joint Inquiry unto Intelligence Community Activities Before and After the Terrorist Attacks of September 11, 2001: 28 Pages](https://28pagesdotorg.files.wordpress.com/2016/08/declasspart4.pdf)

[A Review of the FBI's Handling of Intelligence Information Prior to the September 11 Attacks](https://oig.justice.gov/sites/default/files/archive/special/0506/chapter5.htm) 
Special Report
November 2004 (Released Publicly June 2005)
Office of the Inspector General

[9/11 and the Saudi Connection](https://theintercept.com/2021/09/11/september-11-saudi-arabia/)

[2012 10-5 FBI Report](https://www.scribd.com/document/461114769/2012-10-5-FBI-Report)
    - Focused on two individuals: Fahad al-Thumairy, a Saudi Islamic Affairs official and radical cleric who served as the imam of the King Fahd Mosque in Los Angeles and Omar al-Bayoumi, a suspected Saudi government agent who assisted two terrorists, Khalid al-Mihdhar and Nawaf al-Hazmi, who participated in the hijacking of the American Airlines plane that flew into the Pentagon, killing 125. After the two hijackers flew to Los Angeles on Jan. 15, 2000, al-Bayoumi found them an apartment, lent them money and set them up with bank accounts. A redacted copy of a three-and-a-half page October 2012 FBI “update” about the investigation stated that FBI agents had uncovered “evidence” that Thumairy and Bayoumi had been “tasked” to assist the hijackers by yet another individual whose name was blacked out, prompting lawyers for the families to refer to this person as “the third man” in what they argue is a Saudi-orchestrated conspiracy.

[Canestro Declaration](https://www.floridabulldog.org/wp-content/uploads/2023/04/Canestraro-Declaration-dated-20-July-2021.pdf)
    - 21-page declaration by Don Canestraro, a lead investigator for the Office of Military Commissions, the legal body overseeing the cases of 9/11 defendants

[Documents Responsive to Executive Order 14040 2(d) Part 2](file:///Users/brendanmccaffrey/Downloads/Documents%20Responsive%20to%20Executive%20Order%2014040%202-d-%20Part%202.pdf)

## The Saudi Connection, Summary

### People

**Omar al-Bayoumi**

The FBI has received numerous reports... dating back to 1999, alleging that al-Bayoumi may be a Saudi intelligence officer. FBI files suggest that al-Bayoumi provided substantial assistance to hijackers Khalid al-Mihdhar and Nawaf al-Hazmi after they arrived in San Diego in 2000. During this same timeframe, al-Bayoumi had extensive contact with Saudie Government establishments in the United States and received financial support from a Saudi company affiliated with the Saudi Ministry of defense. That company reportedly had ties to Osama Bin Ladin and al-Qa'ida.

Al-Bayoumi was receiving substantial sums of money from the Saudi Embassy in Washington, DC prior to the 9/11 attacks... this money was being funneled from accounts at Riggs Bank belonging to Haifa bin Faisal, the wife of the Saudi Ambassador to the United States, Bandar bin Sultan.

**Fahad Al-Thumairy**

A Saudi government official who was assigned to the Saudi Consulate in Los Angeles prior to 9/11. "... worked for the Saudi government in the Department of Religious Affairs". Al-Thumairy was later deported from the U.S. on suspicion of links to terrorism.

**Osama Bassnan**

Bassnan may have been in contact with al-Mihdhar and al-Hazmi during their time in San Diego. He was a close associate of al-Bayoumi and Omar Bakarbashat, another one of the hijackers' close associates. He told another individual that he met al-Hazmi through al-Bayoumi and later that he met two of the hijackers through al-Bayoumi. Bassnan has many ties to the Saudi government, including past employment by the Saudi Arabian Education Mission. FBI received reports from individuals in the Muslim community alleging that Bassnan might be a Saudi intelligence officer. According to a CIA memo Bassnan reportedly received funding and possibly a fake passport from Saudi Government officials. He and his wife received financial support from the Saudi Ambassador to the United States and his wife. He met with a member of the Saudi Royal Family in Houston in 2002 and received a significant amount of cash. FBI information indicates that Bassnan is an extremist and supporter of Osama Bin Ladin.

**Abdullah Bin Ladin** 

Abdullah Bin Ladin claims to work for the Saudi Embassy in Washington, D.C. as an administrative officer. He is identified by the FBI as Osama Bin Ladin's half brother.


**Khalid al-Mihdhar** and **Nawaf al-Hazmi**

Hijackers on the pentagon flight. 

**Musaed A. Al-Jarrah**

**Abdullah Al Ajroush**

"...not aware of any contact Al Ajroush has had with the FBI"

"PENTTBOM Investigation"


### Facts

Several of the phone numbers found in the phone book of Abu Zubaida, a senior al-Qa'ida operative captured in Pakistan in March 2002, could be linked, at least indirectly, to phone numbers in the United States. One of those numbers is subscribed to by the ASPCOL Corporation. A November 18, 2002 FBI respoonse to the Joint Inquiry states that "CIA traces have revealed no direct links between numbers found in Zubaida's phone book and numbers in the United States." The number of a bodyguard at the Saudi Embassy in Washington, DC, was also found in Zubaida's possesion.

