---
title: McCaffrey
---

## Research

Some Irish families are known for poetry, or medicine, or religion. The McCaffreys are known for war. The family has staked out a position in Irish history as being at the forefront of all the major wars of the Irish on the English. Each time the Irish rise in a major revolt the McCaffreys are at the beginning of the war fighting for the Irish against the English overlords. The record of the McCaffreys speaks for itself and is nearly unmatched in the Annals of Irish history.

### Mac Gafraidh Origins

The McCaffrey, or McCaffrey family originated with the first kings of the northern Irish county of Fermanagh. The first McCaffrey was a son of Donn Mor Maguire, ancestor of all the Maguire kings of Fermanagh. Gafraidh in the Gaelic, means Godfrey hence the clan name Mc (son of) Caffrey means son of Godfrey. The first McCaffreys took hold of their parcel of south-east Fermanagh around 1302, the year old King Donn Mor died. The name McCaffrey is prevalent throughout southern Fermanagh to this day.

The county of Fermanagh is situated on the south-western border of the northern Irish province of Ulster. Fermanagh is distinctive in that it is roughly bisected by the Loughs or Lake Ernes, Upper and Lower. In the middle of the county between the Upper and Lower Lough Erne is the town of Enniskillen, the county seat. The county today is known for its ancient monuments and scenic vistas. The green hills and blue waters have enticed travelers for centuries. The actual McCaffrey homeland in Fermanagh is at BallyMacafry which lies in the Clogher Valley, north-east of Enniskillen near Fivemiletown on the Tyrone border.

### The Norman Invasion

In 1170, the Norman conqueror of England, King Henry II or Strongbow, with the approval of the new English Pope, Nicholas Breadspeare (Adrian IV), invaded Ireland. This event began two movements in Ireland that would set the pattern of events for centuries. The most important was that this was the first time that the Irish nation would be claimed by the rulers from across the Irish Sea. The second pattern set was resistance of the province of Ulster to rule by the claimants and their local lords.

The first instance of Ulster's distinctive resistance to England was witnessed by the counter attack by the two most powerful Ulster clans, the O'Donnells of Donegal and the O'Neills of Tyrone on the English in 1171. O'Neill, the commander of twenty thousand Irish soldiers, swept south through Meath and prepared to march on Dublin, the Norman capitol in the spring of 1172. O'Neill stopped short of taking the city and sought to make peace with the invaders. O'Neill agreed to allow for King Henry's overlordship of all of Ireland except the province of Ulster. Effective English rule was limited to a strip of land along the eastern coast called the Pale. Small wars and disputes between Irish and Norman continued on a local scale through much of the island while Ulster remained independant and aloof. In the 1190s John de Courcy, a Norman under the same papal initiative to 'reign in the church of Ireland', invaded and took over the eastern half of Ulster, Down and Antrim [1]. The Maguires arrived to find a Fermanagh with a strong Celtic tradition and untroubled by outside affairs.

### The Rising of the Maguire Clan

In the early thirteenth century Donn Maguire consolidated and expanded the Maguire estates in eastern Fermanagh County. With powerful neighbors such as the O'Donnell tribe in Donegal to the west and the mighty O'Neills in Tyrone to the north, the kingdom of Fermanagh was beset by wars and competing claims of title. Donn Maguire (1260?-1302) was the first native to ascend to kingship in the county. His reign, and that of his sons, was marked by poets and historians for its devotion to culture, the church, and learning [2]. The first Maguire had three sons, Donn Og, Gafraidh, and Lochlainn. Donn's second son, Gafraigh moved his family to the east of the royal capitol of Lisnankea to the Townland of Ballymacaffry to populate the western Clogher Valley up to the Tyrone border.

For four hundred years during Ireland's golden age, the clan Mac Cafraigh were known as 'Valiant' and performed in many battles as the standard bearer of the kings of Fermanagh [3]. The clan jealously protected the small kingdom's eastern borders from the powerful O'Neills and, later, the English invaders. This was not an easy task. Fermanagh was claimed by both the O'Donnells and the 'Ui Neill', who alone invaded five times during Fermanagh's formative years (1319, 1327, 1355, and 1358) [4]. By 1395 the Maguires finally had established hegemony over the entire county under the fifth Maguire king, Pilib (Philip of the Battle Axe).

### Philip the Battle Axe and the Maguire Feuds

In Fermanagh, Philip the Battle Axe Maguire consolidated the Maguire hold on the county by 1395 at the royal Maguire town of Lisnaskea. Philip was able to keep the competing neighbors out of the county through his ability in wartime on land and with his white-sailed ships on the waterways of Lough Erne. This is a period of stability and peace in Fermanagh.

The kin of the Maguires, the Mac Gafraidhs are told of in The Annals of Ulster, an ancient manuscript of the times. The first reference to a Mac Gafraidh is about a woman when the Annals state that 'Sabia, daughter of MacGafradh, that is, wife of Cathal Mor Mac maghnusa, to wit, an excellent woman without defect, died this year (1452) on the 8th or 7th of the Ides [8th, or 9th] of May. [5]

It was about this time (1465) that King William ordered that all Irish names be anglicised. This would have the eventual effect of changing Mac Gafraidh to McCaffrey. The name change was not comprehensive as the Annals maintained the Irish form of Mac Gafraidh or Mac Gafraigh.

Things did not remain peaceful in Fermanagh after Philip's death in _____. The next Maguire king was Thomas, Philip's son. His reign benefited from his father's ability and he enjoyed peace. His brother Aedh or Hugh the Hospitable overshadowed Thomas as a wise and generous lord. Hugh was the next in line for the throne but lived amiably with his brother the king until his death in 1428. Hugh had established a castle in Enniskillen (which can be visited today with it's restoration of the first two floors) which began to rival the traditional Maguire seat of power in Lisnaskea.

Thomas' son, Thomas the Younger's reign experienced many squabbles and internal fights by rival branches of the Maguire clan. The Maguires split during this period between Thomas and his brother Philip and the Annals reflect numerous Maguire raids and killings among the Maguires over land and booty. Hugh the Hospitable's sons and grandsons were active in securing significant territory for themselves.

The McCaffreys apparently remained loyal to Thomas, the Maguire king of the old line at Lisnaskea. The family got caught up in the feuds of the Maguires and did not fare well during this period as the Annals shows. The next mention of the MacGafradh is 1468 when the MacGafradh chief, Donnchadh (son of Donnchadh the Luckless), his son Feidhlime and brother John and his son, John, Diarmait, along with three others are slain by Aedh, the grandson of King Philip the Battle Axe MagUidhir (Maguire) (see p.3). 6]This decimation of the McCaffrey hierarchy results in the diminishment of the McCaffrey power in their stronghold of south-east Fermanagh, which was taken by Donall Ballach and Turlach Maguire. [7]

The killing of Maguires by their kinsman, the warrior Mac Gafraidhs, takes its toll on the county in the 1470s and 80s when the entire kingdom is plundered by the MacMahons from neighboring Monaghan. In 1471 Eamonn, son of Thomas, became the king at Lisnaskea but was so unpopular that Eamonn's son, Giolla Patrick, is slain at the Maguire Royal church at Aghalurcher in 1484. A portion of the church still stands to this day just south of Lisnaskea. The church and its sponsors the Maguires of Lisnaskea were diminished at this point and John of Enniskillen and the descendants of Hugh the Hospitable take the mantle of King of Fermanagh in the newer castle in the growing town of Enniskillen.8 [8]

The McCaffreys seem to make the transition from the 'old line' of Maguires at Lisnaskea to the 'new line' at Enniskillen. The Annals mention William MacGafradh passing away on the 5th of March in 1474. William is counsel to the tribal assembly (probably the clan chieftain) of the sons of Philip Maguire. 9 [9]

By 1486 the Maguires are reunited under John, when the son of the inept Eamonn agrees to acknowledge and pledge loyalty to John as king in order in exchange for the release of his sons, who had been taken hostage by the new line of Maguires [10]. The peace was not all inclusive, however, as the Annals show. In 1495 Maghnus the Bald Maguire was slain 'treachorously' by another Philip Maguire and the freckled Gillie McCaffrey, son of Cu-Cunnacht McCaffrey.[11]

The McCaffreys died from natural disasters too. In 1505 a Maguire prince, Toirdelbach, son of John of Enniskillen, was boating on Lough Erne with two sons of Tadhg Mac Gafraidh and sixteen others who were all drowned in a storm when their cot sank.[12]

Family ties often meant less to the people of that period than relationships of convenience. The Annals relate that in 1518 a son of Aodh Mac Gafraidh was sent by Philip Maguire to the island of Clabach to deal with Henry O'Neill on a business transaction. The Mac Gafraidh and another O'Neill on the trip Aodh the Stammerer, Henry's own uncle, were taken hostage on the trip. Philip was enraged and came to the island to fight. He did not gain back the hostages but was able to slay his nephew, Cathal, a friend of Henry. The hostages were released and Aodh O'Neill died a free man at the end of the year.[13]

By 1532 tensions with the O'Neills to the north were at their height when a major skirmish erupted. The Maguire king sent his cavalry under his son, Cormac, into battle with the O'Neills. A sharp battle ensued where many O'Neill princes, including the heir Feidhlimidh, were mortally wounded. Cormac was taken hostage and two captains of the Maguire host, namely William (son of Diarmaid) and freckled Gillie (son of Henry) Mac Gafraidh were slain in battle.[14]

The McCaffreys seem to be a tightly knit clan. They acted as a group and they could be vengeful when necessary. In 1533 Redmond Maguire insulted the wife of Cormac Mac Gafraidh. The Annals tell us that the Clann MacGafraidh refused to let the insult pass and hunted down and slew Redmond.[15]

The killing of Redmond did not create lasting animosity between the MacGafraidhs and the royal Maguires. Just two years later, in 1535, Cu-Connacht Maguire and the MacGafraidh men went on a raid of O'Neill country in Tyrone's Clogher Valley. The Fermanagh men got away with quite a bit of booty that day but that night a raiding party sent by the O'Neills to punish the Maguires and Mac Gafraidhs came upon Feidhlime MacGafraidh on the slopes of Slieve Beagh getting ready to feast upon some of the stolen beef. Caught red-handed and virtually alone, Feidhlime did not stand a chance and was killed on the spot.[16]

Also in 1535 Cormac, son of Donnchadh MacGaffraigh, was slain by the sons of Eogan O'Neill the Red and Giolla-Padruig, his brother, died that year.[17] This event was one which led up to a general feud between a faction of the O'Neills and the Maguires. On January 5th, 1536 the three sons of Maguire (Cormac, Brian, and Domnall, along with the descendants of John and James and Ruaidhri Blind-eye Maguire joined Niall O'Neill of Tyrone in a war on King Maguire. The McCaffreys remained loyal to their king and fought the rebel Maguire and O'Neill invaders. The rebel Maguires with their O'Neill friends invaded Fermanagh and carried off many spoils until they invaded the McCaffrey lands. When the Cuil-Mic-Tigharnan (McCaffrey lands in eastern Tirdennedy between the Tempo River and it's tributary in Co. Tyrone) Cormac Maguire slew many of his Maguire kin in a great battle. Many on both sides died and in the end the McCaffreys stopped the invasion.[18]

This is the last of the major Irish brush wars in the area. The McCaffreys, Maguires, O'Neills, and O'Donnells of Donegal were soon to become united against the English as the Nine Years War approches. This war was the first major revolt by the Irish against the English. The revolt was begun by the Maguires with the McCaffreys at the front.

### The Nine Years War

With the ascension of the Tudor dynasty in England following the English Civil War (the War of the Roses) there came renewed interest in English claims to Irish soil. When Henry VIII broke with the Church of Rome he had the Irish Parliament name him the head of the Church of Ireland. The Irish rebelled again in a short-lived war in which they were defeated in 1539 at Ballyhoe. At this point most of the Irish chieftains submitted to Henry VIII and surrendered their lands to the English monarch in exchange for his granting them back as royal, and taxable, land grants. The Maguires, with the McCaffreys (now the fifth most populace family in Fermanagh[19] ), again refused to submit. As a result, the O'Neills invaded Fermanagh in 1566 in order to win the tribute of the Maguires for the Ui Neill clan. After fending off the O'Neills, King Cuchonnacht II of the Maguires kept the peace in Fermanagh. The price of that peace was to allow the English to divide the county into shires using the English system in 1585 after he finally, formally surrendered Fermanagh to the English. King Cuchonnacht received the county back, minus sizable church lands, in 1586 "for himself and his descendants to hold forever as long as they did not rebel." Cuchonnacht died in 1589 and was succeeded by his son, Hugh, who was crowned the fifteenth king of Fermanagh at Lisnaskea in 1589. The stage was now set for the final collapse of the Irish nobility and total submission to English overlordship [20].

The English overlords appointed a sheriff to look after their interests and enforce the king's peace in Fermanagh. In 1593 the sheriff killed unarmed men, women and children in the county. Hugh immediately took up arms. With McCaffreys at the front, the Maguires attacked the English beginning the Nine-Years War. Hugh was so successful that he was able to send men south to Connaught where they surprised the English at Tulsk and earned a great victory for the Irish. It was at Tulsk that the chief of the McCaffreys was slain. [21] The McCaffrey chief was succeeded and they continued to fight with the Maguires as the revolt spread. A large English force invaded Fermanagh and Hugh fled, under the orders of his secret ally, the Hugh O'Neill from Tyrone. Eventually, Hugh was driven out of Enniskillen in 1593 but he was back in 1594 to besiege the invaders. The force sent by the English to relieve the siege under Sir Henry Duke was defeated and such was the plunder that the battle was called the "ford of the Biscuits". Hugh raised the siege and now had the O'Donnells and the mighty O'Neills on his side. In May 1595, he retook his castle at Enniskillen [22].

The year 1596 was spent by both sides in negotiating peace to buy time. The English were reorganizing their forces while the Irish were waiting for help from Spain. Early in 1597 the English sent two parallel invading forces into rebellious Ulster. The one in the east was defeated by O'Neill. In the west, the McCaffreys and Maguires helped Red Hugh O'Donnell defeat the army under Sir Conyard Clifford. Later that year the McCaffreys and Maguires (who led the Irish cavalry) were involved in the greatest Irish victory on Irish soil, the Battle of the Yellow Fords. The victory was such that the Ulster Chiefs again advanced as far south as Clare in Connaught [23].

The great chieftain Hugh Maguire, with his standard bearer McCaffrey, was finally killed on a raid in Munster. The powerful O'Donnells successfully nominated Cuchonnacht, Hugh's half brother, to the Fermanagh throne. Meanwhile, the Spanish had finally arrived at Kinsale with 4,000 infantry to help the Irish. The battle of Kinsale ensued in 1602 with terrible losses for the Irish. Later that year, the O'Neills and O'Donnells gave in to the English overlords. Cuchonnacht Maguire was the last to give in to the English. Once he did, Cuchonnacht found he was unable to live with the English exercising ownership over his lands. He then helped organize the famous 'Flight of the Earls' on September 14, 1607. The great northern chieftains of the Maguires, O'Neills, and O'Donnells were to die in obscurity in Italy in the coming years, never to return to Ireland. [24] Cuchonnacht was the last Maguire king of Fermanagh. Thereafter, Fermanagh and Ireland would be ruled either directly by the invaders or through English sponsored chiefs. There is no record that the chief of the McCaffreys left his homeland behind.

With the troublesome northern Irish native leadership conveniently disposed of, the English planned what came to be known as the Jacobean plantation of Ulster, to include Fermanagh. In 1603 they met at Devenish, an ancient island in Lower Lough Erne with the local Irish lords who remained to parcel out the county. Included in the Irish commission to divide the county was the chieftain of the McCaffreys. This commission was unsuccessful in planning the English division of Fermanagh, it took three more commissions to complete the plantation of Ulster. The chief of the McCaffrey clan never again attended the meeting but the McCaffreys were successful in preventing the planters from taking Magerstephana, the area of McCaffrey control [25]. In November, 1612, Ballymacafry and much of the barony of Magerstephana, was incorrectly listed as a part of Tyrone and parceled to Conn O'Neill. O'Neill was made a servitor of the loyalist, Conor Roe Maguire. [26] This area is unusual in that the natives maintained the land and the McCaffreys kept much of their traditional areas and were allowed to stay.

### The Irish Rising of 1641 and the English Plantation

The McCaffreys do not reappear until 1641 when the Irish again rebelled. The great revolt was started by the McCaffreys at the village of Lisnarick:

"Rory (Maguire) himself took Necharney (or Irvinestown). His brother-in-law, Richard Nugent, with the McCaffreys, took Archdalestown" [27]

In this revolt, the Maguires were able to rid Fermanagh of the English entirely and the greatest English rallying cry for revenge was born. The Maguires had besieged and taken the Castle Monea, killing 15 men and 60 women. The actual transcript of Brian Maguire of Tempo's informing of his kinsman's revolt reads as follows.

" ...upon the same day (Oct 10) Richard Nugent, ...Patrick McCaffrey and Phelim McCafferie, by the appointment of the said Rorie (Maguire), took possession of Mr. Hugh Dairs, his house and Town in the said countie of ffermanagh-called Archdalestowne and pillaged the said house & Towne, and afterwards placed a ward therein..." [28]

The Maguire success across Fermanagh prompted the mighty O'Neill and O'Donnell clans in Ulster to again join the growing fight. Eventually most of Ireland joined the revolt, including the old Norman-English planters who were still Catholics. These men were left over from the Norman invasion by Strongbow but defied the Tudor, Henry VIII, when he embraced the Protestant faith.

In 1642 the Irish bishops endorsed the revolt and appointed a lawyer, Patrick D'Arcy to draw up a constitution.

### Cromwell's Invasion

In the wake of purported reports of Catholic massacres of Protestants in Ireland (including the Maguires/McCaffreys at Castle Monea), Elizabeth I and the English Parliament decided to send Ireland it's greatest oppressor, Oliver Cromwell. Cromwell arrived at Dublin in the summer of 1649. His men commenced on a tour of slaughter unseen in the British Isles. According to an Oxford Historian, Arthur Wood, whose brother served with Cromwell, the soldiers held children in their arms as protection while in the attack. They slaughtered 3000 at Drogheda and an additional 2000 at Wexford, including 300 defenseless women begging for their lives. Cromwell himself sanctioned the killing of defenseless citizens as he attests, "I thought it not right or good to restrain off the soldiers from their right of pillage, or from doing execution on the enemy." [29]

The McCaffreys almost certainly fought along side the Maguires in the Army of Eoghan Rua O'Neill and his nephew, Rory Maguire, king of Fermanagh. When both of these generals died, the Ulster Army was led, at first successfully, by Heber MacMahon. Unfortunately for the Irish, MacMahon was no general, and he lost half his army at Letterkenney, and the other half at Enniskillen in Fermanagh (thanks in part to Brian Maguire's treachery), thereby ending resistance to Cromwell in the North. [30]

### The Williamite Wars and the Battle of the Boyne

The victory of Cromwell began thirty years of depression, famine, and repression of the Irish. The first measure taken by the victorious English was to banish the entire native Catholic populace of Ireland to the rough lands along the west coast, in Connaught. Parliament declared a penalty of death on any Irish man, woman, or child east of the river Shannon after May 1, 1654. Catholic priests were killed on sight and any person turning them into authorities earned a bounty of five pounds. The land was turned over to the victorious Cromwellian soldiers and their benefactors. [31]

Many of the laws and regulations instituted by the Cromwellians proved unenforcable as the new landlords needed the natives to do the work which made them rich landlords. In Fermanagh, the remaining McCaffreys preferred to stay and become serfs to provide critical labor to the incoming landlords. Eventually the repressions were eased. When, in 1660, King Charles II, himself a secret Catholic, succeeded the Tudors religious freedom again prevailed.

The last great rising of Catholic Ireland occurred under the reign of James II. James ascended to the throne in 1685 and appointed the Duke of Tyrconnell, a Catholic, as his Lord Lieutenant of Ireland. Tyrconnel overturned many of the English measures and allowed Irish soldiers to form a separate army. While Tyrconnell was busy rebuilding Catholic Ireland, James was deposed in the Glorious Revolution of William and Mary. William of Orange came from the Netherlands and the significance of that color remains today in Ireland. James first fled to France. Then he brought a French army to Ireland where he was welcomed by his appointee Tyrconnell and his Irish army. James swiftly mustered an Irish Parliament and prepared the Irish-French army to fight William, who landed in June 1690. [32]

The leader of the Fermanagh contingent of the Irish was Cunnought Mor Maguire. Giolla Padraig Modartha McCaffrey was the chief of the McCaffrey Clan and led his men in Maguire's regiment [33]. Cunnought Mor was one of the few Irish to own lands in Fermanagh. He owed his holdings near Tempo in Magersteffana, Fermanagh to his grandfather, Brian who alerted the English to the Irish risin in 1641, fifty years earlier. Now the son was breaking with his grandfather to make war on the English.

The war went well at first with the Earl of Tyrconnell and the French marquis of St. Ruth leading the Irish-French. The English Catholic King James began the war to tumultuous support from the Irish but until he ran up against William of Orange at the Battle of the Boyne on July 1, 1690. Although the English victory was not decisive, King James fled back to France that day. This is the event which is still commemorated throughout Northern Ireland by Protestants with politically charged marches and parades every year.

The Irish and St. Ruth continued the war with some success until the battle of Augrim on July 12, 1691. There the Fermanagh forces of Maguire, to include the McCaffreys under Giolla Padraig, were so decimated that "no correct list of the officers of this regiment can now be made. They were nearly all cut to pieces at the Battle of Augrim, and, besides, their brave colonel being slain (Cunnought Mor Maguire), their Lieutenant-Colonel was taken prisoner." [34] At Augrim the left side of the Irish line, held by Luttrell's Irish Cavalry, crumbled about the time St. Ruth was killed by an English cannonball to the head. This situation made the Irish position untenable and, without overall command from St. Ruth, lead to a rout. The Fermanagh men stood and fought, losing both Cunnought and Giolla Padraig McCaffrey in the process [35]. The battle was decisive in the war and the effective end of the last organized Irish resistance for the next 250 years.

The defeat of the Irish forces led to the third and final plantation of Ireland. In Fermanagh, the Protestants who held land, kept it. Most of the Catholics who still held land were supplanted by Protestants, in particular Presbyterians from Scotland. Many of these Scots composed the first migration of Irish to America as Scots-Irish. They included the parents of President Andrew Jackson and the ancestors of President Wilson. McCaffrey lands were subject to the local imported landlord at Cranbrooke Manor just outside Fivemiletown. The manorhouse and grounds still exists just off the Fivemiletown-Enniskillen road.

### The Penal Laws

The victorious English, with their Protestant allies, commenced to impress loyalty to the crown on all Irish via the Penal Laws of the early 18th century. The purpose of the laws, according to one Professor Lecky, "to make them poor and keep them poor, to crush in them every germ of enterprise and degrade them in to a servile race who could never hope to rise to the level of their oppressor." [36]

Native Irish Catholics were subject to the following laws in their own country by the Protestant minority:

they could not receive an education, enter a profession, hold public office, engage in a trade, live within five miles of a corporation (Protestant) town, vote, keep or bear arms, buy life insurance, inherit anything from a Protestant, or educate a child. In an effort to divorce the people from their faith, the Protestants legislated that Catholics had to attend Protestant worship. Catholic clergy was banned in the entire country after a set date. Catholic clergy found after that date would be banished. If they returned the state would "draw, quarter, then hang the papist criminal".37

To ensure the Catholics could never amass wealth the following prohibitions were installed. Catholics could not purchase land, lease land, inherit land, accept a mortgage on land as security for a loan, own a horse worth more than five pounds, rent land worth more than thirty shillings a year, or reap profit from land worth more than one-third of his rent.38 If any Catholic was found to have wealth in excess of one-third of his rent the 'finder' would reap the excess as personal gain.

The Catholic family was also a target. Wives who were unfaithful could convert to Protestantism and expect an annuity from the cuckolded husband. If a child converted, he/she would be the sole beneficiary of his family's inheritance regardless of other or older children. [39]

This English-Scottish effort to destroy the Irish Catholic identity again failed to extinguish the Irish spirit. The cumulative effect of the laws was to drive a wedge permanently between English and Irish people. Although there was widespread flouting of the laws, sometimes with dire consequences, most of these acts remained the law of the land for the entire 18th Century. The laws were maintained by an Irish Parliament in Dublin which represented the Protestant landlord class.

### Irish Risings

The Irish refused to submit to many of the English laws. The Irish resorted to 'hedge schools' and 'midnight masses' to clandestinely keep the faith alive and pass on some of the Irish culture from generation to generation. The McCaffreys stayed in Fermanagh and figure prominently in the abortive efforts to overthrow the English establishment.

In 1796, the United Irishmen, founded by Theobald Wolfe Tone, began a rising which sputtered out when the ringleaders were identified through a network of spies and arrested beforehand. Wolfe Tone himself surrendered when he arrived on a French ship at Lough Swilly, too late to lead the French-Irish force. The center of the revolt in Fermanagh was Roslea, a nationalist town to this day. One Felix McCaffrey was among the United Irishmen who were informed upon by one William Whiteside. Felix escaped arrest and fled Fermanagh. [40]

In 1801 the British Prime Minister William Pitt, with an eye towards Catholic Emancipation, enticed the heavily oppressive Irish Parliament to vote itself out of existence and thus create the United Kingdom, with direct rule of Ireland from Westminster. The strategy failed when the English monarch, George III, refused any new rights for Irish Catholics.

In the early 1800s secret societies sprang up across Ireland, to include Fermanagh. The Ribbonmen were a group dedicated to the eventual overthrow of the Protestant rule. They pledged to 'be true to fellow Roman Catholics until death and to be ready, at five minutes' notice, to wade knee deep in Protestant blood' [41] The original Molly Maguires were a group that defended a catholic widow from Tyrone who was evicted. Their success led them to form a secret society which defended Catholics against eviction. The Ribbonmen eventually became the Feinians, the precoursers to the modern Sinn Fein. One James McCaffrey of Lisnaskea was the leader of the Feinians in Manorhamliton. [42]

The Penal Laws were eventually repealed, many through the efforts of Daniel O'Connell (the liberator). He managed to get Catholics the vote, then was the first Catholic to win a seat in Parliament from County Clare. This breadthrough led to a reassessment of Irish law and a new attitiude towards Catholics in Ireland and England.

### The Famine

The famine lasted four years and ruined the potato crop from 1845 through 1847. The initial English reaction was to 'let the natural economy take it's course'. One problem with the situation was that the potato was the most important staple of the Irish worker. It was estimated that the average Irish worker ate fourteen pounds of potatoes daily (with cabbage and salt. [43] With the Irish population on the rise, the potato was the only vegetable with enough starch to support the peasantry on small plots of land.

The first year Parliament authorized one hundred thousand pounds for famine relief. The same year double that amount was allocated to the refurbishment of Battersea Park in London. Parliament was preoccupied with maintaining Irish exports of beef and grains, which the landlords were able to do throughout the famine years. The British eventually set up poor houses and soup kitchens for the Irish. They also sponsored work programs but much of the work commissioned by the English work relief plan was purposely unproductive. This was to ensure that cheap, relief labor in Ireland did not compete directly with English companies.

Many of the landlords in Fermanagh acted in the absence of assistance from London.

### Modern Ireland

Modern history in Ireland has few references to the McCaffrey clan. It seems clear that areas where McCaffreys are still prevalent remain polarized between Gaelic Irish Catholic and Anglo-Saxon Irish Protestant. One Charlie McCaffrey, an IRA man, was killed in 1936 when a faulty mine exploded. The three men were planning to blow up a customs hut on the border to protest an impending visit by King George VI. Charlie lived with his injuries in the hospital for two days before passing away. Witnesses quoted McCaffrey as saying over and over, "stand back John Joe, there's a wee thing wrong" while in and out of a coma [44].

In recent years, Enniskillen, the hub of Fermanagh, has seen several IRA actions. In 1987, the IRA bombed the Cenotaph during a British Serviceman's memorial ceremony, killing and injuring scores of innocent bystanders. In 1992, they bombed a prominent hotel just outside town on the shores of Upper Lough Erne, this time with no injuries or loss of life but thousands of pounds in damages.

The latest McCaffrey of note is Brian McCaffrey of Tempo, a Sinn Fein counselor and local activist.


### Sources

[Web Archive, McCaffrey](https://web.archive.org/web/*/https://www.dave-woody.com/mccaffrey/*)

[Blance McCaffrey Jorden bc 1902-1932](https://web.archive.org/web/20211204163210/https://www.dave-woody.com/mccaffrey/blanchemccaffrey.htm)

[John and Delila McCaffrey, Married 1845](https://web.archive.org/web/20211027165719/https://www.dave-woody.com/mccaffrey/John&delilamccaffrey.htm)

[1990 McCaffrey Surname Distribution](https://web.archive.org/web/20220819112515/https://www.dave-woody.com/mccaffrey/1990_mccaffrey_surname_distribut.htm)

[1940 Census Thomas McCaffrey](https://www.ancestry.com/1940-census/usa/New-York/Thomas-Mccaffrey_g8bfn/amp)

- Education
    - In 1940, Thomas was attending school. The census worker recorded the highest grade Thomas had completed as: elementary school, 4th grade.
- Residence
    - Thomas lived at 9113 35 Avenue in New York, Queens, New York.
    - Thomas was born in J Hg.


Richard Mccaffrey, Sergeant, Distinguished Service Cross Recipients, World War II