---
title: "UAP People"
description: "A directory of people within or adjacent to the UAP stuff"
page-layout: full
---

## Jim Simons


## Hal Puthoff

Dr. Harold E. Puthoff is the co-founder and Vice President of Science and Technology of TTS Academy. Since 1985, Dr. Puthoff has served as President and CEO of EarthTech International, Inc. (ETI), and Director of the Institute for Advanced Studies at Austin (IASA). He has published numerous papers on electron-beam devices, lasers and space propulsion and has patents issued in the laser, communications, and energy fields. Dr. Puthoff’s professional background spans more than five decades of research at General Electric, Sperry, the National Security Agency, Stanford University and SRI International. Dr. Puthoff regularly advises NASA , the Department of Defense and intelligence communities, corporations and foundations on leading-edge technologies and future technology trends. He earned his Ph.D. from Stanford University in 1967 and won a Who’s Who Lifetime Achievement in 2017 that recognizes individuals that have achieved greatness in their industry and have excelled in their field for at least 20 years.

Lecture 2018

- [video](https://www.youtube.com/watch?v=Q72TK4Fpze0)
- [writeup](https://paradigmresearchgroup.org/2018/06/12/dr-hal-puthoff-presentation-at-the-sse-irva-conference-las-vegas-nv-15-june-2018/)
- [IRVA-SSE 2018](https://vimeo.com/ondemand/halputoff2018)

2021 SCU AAP Conference Keynote by Hal Putoff

- [video](https://www.youtube.com/watch?v=PQ5Dobxnw8c)

## Salvatore Pais

- [Dr. Salvatore Pais | Intuitive Science, Conscious Universe & The Philosophy of Physics](https://www.youtube.com/watch?v=7aCrznDR6mw)

## Richard Griffiths

Richard Griffiths serves as [Affiliate Faculty](https://www.astro.uhh.hawaii.edu/faculty.php#griff) at University of Hawaii at Hilo, Physics and Astronomy. He leads the team that solved a gravitational lens phenomenon.

- [article](https://manoa.hawaii.edu/news/article.php?aId=11578)
- [paper](https://academic.oup.com/mnras/article/506/2/1595/6276726?login=false)