
## Good Reads

- **The Intelligent Investor**
- **Flash Boys**: History of HFT, frontrunning, etc
- **Liars Poker**: Solomon Brothers and the real start of bond trading
- **Beat the Dealer**
- **Alchemy of Finance**: Soros' Reflexivity theory of markets
- **When Genius Failed**: The rise and fall of Long Term Capital Management
- **Exotic Options and Hybrids**: Vol. models, correlation, barriers, ATRs, etc.
- **The Smartest Guys in the Room**: The massive fraud of Enron
- **Reminiscences of a Stock Operator**: An absolute classic on stock trading
- **More Money than God**: On the hedge fund industry
- **The Changing World Order**: Ray Dalio's macro book
- **The Black Swan**
- **Beat the Market**: Highly coveted book by some iconic quants
- **The Art of Currency Trading: A Professional's Guide to the Foreign Exchange Market**
- **The Disciplined Trader**
- **Trader Vic II: Principles of Professional Speculation**
- **Learn to Trade Momentum Stocks**
- **The Bond and Money Markets**
- **Trading in the Zone**
- **Bollinger on Bollinger Bands**
- **Adventures of a Currency Trader**
- **Ace the Trading Systems Developer Interview (C++ Edition)**
- **Professional Automated Trading: Theory and Practice**
- **Trading Systems Performance Unleashed: Mastering Latency and Efficiency in High-Frequency Trading**
