---
title: Cash Management
description: You have a large amount of cash. How do you get it into the traditional banking system?
---

## The Legality of Wiring Money for Cash

Generally, it is a crime to engage in virtually any type of financial transaction if a person conducted the transaction with knowledge that the funds were the proceeds of “criminal activity” and if the government can prove the proceeds were derived from a “specified unlawful activity”.  Criminal activity can be a violation of any criminal law – federal, state, local, or foreign.  Specified unlawful activities are set forth in the statute and include over 200 types of U.S. crimes, from drug trafficking, terrorism, and fraud, to crimes traditionally associated with organised crime, and certain foreign crimes, as discussed below in question 1.3.

The government does not need to prove that the person conducting the money laundering transaction knew that the proceeds were from a specified form of illegal activity.

Knowledge can be based on wilful blindness or conscious indifference – failure to inquire when faced with red flags for illegal activity.  Additionally, knowledge can be based on a government “sting” or subterfuge, where government agents represent that funds are the proceeds of illegal activity. 

Under Section 1956, the transaction can be: (1) with the intent to promote the carrying on of the specified unlawful activity; (2) with the intent to engage in U.S. tax evasion or to file a false tax return; (3) knowing the transaction is in whole or in part to disguise the nature, location, source, ownership or control of the proceeds of a specified unlawful activity; or (4) with the intent to avoid a transaction reporting requirement under federal or state law.

Section 1956 also criminalises the transportation or transmission of funds or monetary instruments (cash or negotiable instruments or securities in bearer form): (1) with the intent to promote the carrying out of a specific unlawful activity; or (2) knowing the funds or monetary instruments represent the proceeds of a specified unlawful activity and the transmission or transportation is designed in whole or in part to conceal or disguise the nature, location, source, ownership or control of the proceeds of the specified unlawful activity.

Under Section 1957, it is a crime to knowingly engage in a financial transaction in property derived from specified unlawful activity through a U.S. bank or other “financial institution”, or a foreign bank (in an amount greater than $10,000).  Financial institution is broadly defined with reference to the Bank Secrecy Act (“BSA”) statutory definition of financial institution (31 U.S.C. § 5312(a)(2)), and includes not just banks but a wide range of other financial businesses, including securities broker-dealers, insurance companies, non-bank finance companies, and casinos.

## What to do with a lot of cash


### The ATM Approach

**Step 1 | Buy an ATM**

ATM Global 
Phone: (877) 286-1755
https://atmglobal.net/ 
*We got permission from Douglas to use the call for this video. 

National ATM Systems
Phone: (803) 786-1900
https://www.nasatm.com/

Ocean ATM
Phone: (877) 538-2860
https://oceanatm.com

America’s ATM
Phone: (877) 475-1104
https://americanatm.com

ATM Money Machine
Phone: (609) 641-7300
https://www.atmmoneymachine.com


These companies deliver a machine to your location (machines ~$2,500), and have installers come to set it up ($350 for installation). This takes about 2 weeks. 

Put it at a friends restaurant or something.

**Step 2 | Set it up**

All ATMs must be connected to the processing server and have a power outlet. There are three optional connections:
1. Hardwire Internet Line
2. Phoneline
3. Purchase an ATM Wireless Box

You can not connect to wireless internet in the business, you must hardwire into the internet via an ethernet jack or run an ethernet cord from the modem to the ATM. 

**Step 3 | Paperwork**

Then you fill out some forms with the ATM company ("Exhibit 2, Exhibit 3, W9") that do basic background checks: if you have any fraud in your past, etc.

The paperwork will give you your own unique merchant ID, which allows you into the processing server. We handle getting this licensing done for you. 

Connect your account with them to a (business) bank account. The ATM company sets up an interface for you to monitor transactions, get notifications that the cash balance is low, etc.
 