---
title: ION Protocol
---

## What is Ion Protocol?

### Overview

- Ion Protocol is a price-agnostic lending platform that leverages provable validator-backed data to allow users to borrow ETH and other staked/restaked assets against their LSTs and re-staking positions.
  - All loan positions in Ion are price-agnostic, and their parameters (interest rates, LTVs, position health, etc.) are determined by consensus layer data and secured with ZK data systems.
  - This means liquidations are triggered by **changes in consensus layer state, not by price oracles.**
  - This verifiable Proof-of-Reserve system is enabled by a network of oracles running our ZKML (zero-knowledge machine learning) framework which enables trustless verification of consensus layer state and robust validator credit ratings.
- The above investments in trustless infrastructure enable us to support a wide plethora of assets without sacrificing on capital efficiency as all of our launch markets will you 90%+ LTVs.
- Users in Ion can deposit any combination of the following collateral types into the protocol's lending markets at scale:
  1. LSTs
  2. LST LP Positions
  3. Re-staking Positions
  4. Liquid Re-staking Positions (LRTs)
  5. Staked LST LP Positions (e.g. Aura Finance’s ERC-4626 positions)
  6. LST Index Products (e.g., IndexCoop’s dsETH, UnshETH and more)
- Depositors are able to borrow ETH and other LSTs to use in the greater DeFi ecosystem or to compound their staking yield.
- By participating in these ETH loans, users can leverage, hedge, and perform a variety of financial strategies with their staked and re-staked assets.

---

## Product Overview — LST<>LRT Market

A lending market supported by Ion Protocol enabling borrowers to compound their exposure to EigenLayer points and LRT points while lenders earn 2-3x the staking yield.

### Lenders

### Process:

Deposit $stETH into the market, earn the staking rate + up to 7% additional yield from borrowers looking to leverage their EigenLayer points.

### Yield Calculations

$lenderRate = currentUtilization*borrowRate$

Lowest Lender rate = 3.2% APR (0.8 \* staking yield)

Highest pre-kink Lender Rate = 7.0% (0.8 \* 8.75%)

Total yield for lenders = 11.0% APR in ETH — No leverage needed

| \* All yields in ETH | Yearly APR                      | Ion % Difference From Other Protocols |
| -------------------- | ------------------------------- | ------------------------------------- |
| Ion Protocol         | 11.00% APR + Boosted Ion Points | +7.50% APR                            |
| Manta                | 3.50% APR + Airdrop             |                                       |
| Blast L2             | 3.50% APR + Airdrop             |                                       |
| Morpho               | 2.50% APR                       |                                       |
| Aave                 | 1.75% APR                       |                                       |
| Compound             | 1.74% APR                       |                                       |

### Borrowers

### Process:

Deposit one of the below LRTs and forego your staking rate (at minimum) or pay up to 5.75% (real yield) APR to leverage up your EigenLayer airdrop

- Supported LRTs:
  - KelpDAO (rsETH)
  - Renzo (ezETH)
  - [Ether.fi](http://Ether.fi) (eETH)
  - Swell (rswETH) — TBD on deadlines

### Yield Calculations

$borrowRate=6.56x*3.5$

$x = currentUtilization$

Lowest Borrow Rate = 3.5% (Staking Rate)

High Borrow Rate (pre-kink) = 8.75%

### EigenLayer Airdrop Calculator View

[https://docs.google.com/spreadsheets/d/11hv10CCOWFiqzcnE1RcqKQsWk5A0FYMXWYu6pjllePs/edit?usp=sharing](https://docs.google.com/spreadsheets/d/11hv10CCOWFiqzcnE1RcqKQsWk5A0FYMXWYu6pjllePs/edit?usp=sharing)

### Loan Cost Calculator View

[https://docs.google.com/spreadsheets/d/1LPxMQH9Cdwa9-tR2ExkGbN6PPqYaVxBCSWHkwbO55pk/edit#gid=0](https://docs.google.com/spreadsheets/d/1LPxMQH9Cdwa9-tR2ExkGbN6PPqYaVxBCSWHkwbO55pk/edit#gid=0)

---

## **Yield Projections**

### **Lending:**

- Lending Yield: 10% ETH\* _— Guaranteed_
- Ion Points: ~12% Ion
- **_Total Est. Yield: 22% APR_**

### **Borrowing:**

- Borrowing Cost: -5% ETH
- EigenLayer Yield (Points): 72% EL Airdrop
- LRT Yield (Points): 20% LRT Asset Airdrop
- Ion Points: ~6% ION
- **_Total Est. Yield: 93% APR_**

_Assuming:_

- Base Case EL Airdrop — See table in borrowing
- Ion Early Contributor Allo in TGE = 3%
- Borrowers earn 20% of allo — deposits capped at 25M
- Lenders earn 80% of allo — deposits capped at 50M
- Ion FDV = 250M
- LRT FDV = 500M, Airdrop = 10% of supply

---

## Additional Details/Perks

- **Whitelist Access**
  - To ensure the security of the protocol — all users will must be whitelisted to gain access to the protocol.
  - For all early contributors, we will whitelist addresses directly and only introduce users that we have interacted with directly.
- **Allocation Min/Max**
  - Minimum Allocation:
    - Phase 1 (10M Lender Liquidity)
      - $1M in size
    - Phase 2 (50M Lender Liquidity)
      - $1M in size
  - Maximum Allocation:
    - Phase 1 (10M Lender Liquidity)
      - $2.5M in size
    - Phase 2 (50M Lender Liquidity)
      - $7M in size
- **Launch Timelines**
  - Launch Market: Live Security Review Period, lending limits $1M (2 weeks) — End of Feb/Early March
  - Expand Market: Increase lending limits to $10M, borrowing limits to 4-5M (2 weeks)
  - Increase Limits: Increase lending limits further, amt pending market stability, (weekly)
- **Direct Access to a Private Telegram GC Support Team**
  - Every single individual user in the Ion Beta Group will have a personalized tg group directly with the core members of the team. You can reach out to this group to ask questions, talk about your position, and more.
- **Access to More Investment Opportunities (User tg Group)**
  - We host a specialized private tg group that has all of our users in it. This group gains access to advanced news, information, and access to _user-curated deals_ from our protocol partners in the ecosystem.
  - This can include everything from venture deal allocations to specialized product access, and more.
