---
title: Shogun
---

## Resources

- [notion](https://shogunfi.notion.site/Shogun-Deep-Dive-a9130d7d87a444928a6c0255d2f096b0)
- [deck](https://docsend.com/view/basiq4b9zes6k9cc)

### Round

- Shogun was incubated by [Binance Labs](https://labs.binance.com/en) (pre-seed round)
- Investors will have a 6-month cliff and 24-month linear vesting period
- Structured as a SAFE + Token Warrant
- Additional tokenomics details are available below
6.9m for 69m fdv
polychain leading: ansem, hayes, avi feldman, delphi

### Team

- Rahul CEO  - tampa
- Roland cofounder/lead reasearch quant: worked with binance, chainlink, quant firms - toronto
- Brandon Comer: CTO. Background fintech/web3, amazon, td ameritrade, cosmos - LA
5 other engineers, mostly US; do offsites; get a place in ny post Series A

Rahul and brandon met at umi

### Problem

Onchain trading is difficult for ave users

## Product Summary

- Traders on Shogun initiate gas-less trades on their given L1/rollup of choice, regardless of which chain the trade will actually execute on
- single sdk/api: moveVM, evm, sol, cosmos
- account abstraction: use socials to log in, google, x, farcaster, etc
- can do tg bot out of the gate

- short term loan between trader and solver

2 products: 
- smart order routing, cctp using bridges, limited to bridge time
- intent centric model

V2 is L2 as a solver
    - decentralize the solver role

## Questions

- how arer assets managed? user with eth on mainnet wants solana, do u create a keypair for them or do they need to give u one? do u give them gas?
    - depends on what users want
    - generic v1 use your own wallets
    - chain sigs on near is closest comp to their account

- do users specify exactly how much they want
- are you guys using skip api for cosmos ecosystem or building ground up / competing
- who can participate in the solver network?
    - v1, small set of solvers: flowdesk, market makers, etc  
    - v2: very wide decentralized solver network

- do u anticipate most interactions going through your frontend, other frontends plugging in ur api, or tg bot?
    - miniapp tech in tg

## Shogun | Investment Memo 

Shogun is an intent-centric infrastructure protocol for modular blockchains, designed to radically improve the multi-chain user experience. By leveraging cross-chain intents, Shogun enables traders to execute gas-less, cross-chain trades seamlessly, abstracting away the complexities of wallets, bridges, and gas tokens. Shogun’s execution layer batches trades across multiple blockchains and optimizes for maximum trader surplus through off-chain solvers. This approach eliminates slippage, price impact, and MEV, enabling efficient, one-click trading across diverse ecosystems. The protocol’s modular architecture and Shogun-SDK further extend its utility, allowing seamless integration into various DeFi applications, initially compatible with EVM, Celestia/IBC, and Axelar-compatible blockchains.

Selected as part of Binance Labs’ Season 6 Incubation Program, Shogun was among the few projects to receive a pre-seed investment. In addition to a strong working relationship with Binance, Shogun has developed strategic partnerships with Celestia, Berachain, Movement Labs, and Neutron.

User experience has long been one of the primary pain points in crypto. With the proliferation of modular blockchains and various layer rollups, there is a tremendous opportunity for a protocol that can abstract underlying components to offer seamless and liquid interoperability. Shoku believes Shogun is well-positioned to capture this role.

We are excited to offer Shoku’s Shokudo allocation in Shogun’s seed round, where you will be investing alongside Polychain, Cobie, Arthur Hayes, Ansem, and Shoku himself. The structure is a SAFE + Token Warrant at a $69mm FDV with 10% carry. Investors will have a 1-month cliff and a 24-month linear vesting period.

