---
title: "Library"  
# page-layout: full
---

___

‎


Welcome to my library.

This is a digital brain trust developed slowly and perpetually, intended to serve as a growing knowledge base across topics spanning from cultural history to quantum field theory.

Portions of this collection are particularly sloppy and incomplete, as it's been a low-priority side project to which I tend infrequently. As a result, particularly for the extremely new/underdevelop subsections, readers may develop a misrepresentation of my perspective, expertise, and/or opinion on the respective topic.



For these reasons, this directory will remain password protected for the forseeable future. If you are accessing this, it means I entrusted you to respect my preference to keep this private in the near future. 

If you are curious to see what my vision for this is in the future, I would recommend viewing my more developed topics. These include:

## Areas to explore

**[Ethereum](./natural-sciences/crypto/blockchain/ethereum/index.qmd)**

**[Physics](/library/natural-sciences/physics/index.qmd)**

**[AI](/library/natural-sciences/ai/index.qmd)**




