---
title: Hypersymmetria LLC
---

## Progress

- [Zenbusiness](https://www.zenbusiness.com/r2/registration-pbf/review)

## Resources

- [Wharton School: Business Structures](https://www.youtube.com/watch?v=2bmSA5jufVc&list=PL0470F4C2DCEB689A&index=40)

Where to incorporate

- [NY vs Deleware](https://www.olshanlaw.com/Real-Estate-Law-Blog/Delaware-LLCs-vs-NY-LLCs)

## Overview & Research

I am looking to create an LLC under which I can expense various costs associated with my work operations.

For example I would be looking to expense things like:
- Trip to Japan (since purpose is meetings with crypto founders/teams)
- My phone bill (phone line was acquired for the sportsbook trading operations)
- Dinners with VCs, founders, etc.

A few questions I have:

1. From my understanding, Delaware LLC is probably the best choice?
2. What are the costs associated with maintaining an LLC? 
    - Particularly curious about the recurring costs: legal, accounting, etc? 
    - Are there any smart approaches I should be aware of, for example may I simply use turbotax or something for the accounting side to avoid these costs?
3. Would you suggest I create the LLC through one of the simple online platforms (e.g. ZenBusiness or LegalZoom) - or can it be done more intelligently another way?
4. Are there any "unknown unknowns" - things I haven't asked and should be considering?

## Progress

Incorporating in New York

**Requirements**

- New York State requires all LLCs to publish their name in 2 New York newspapers for 6 weeks straight, in the county they formed.
    - Meet New York State’s requirement to send a certificate to the county within 120 days of forming your LLC.

- Appoint Registered Agent