---
title: Dev Tools
description: Resources and tooling for EVM development
---

## Clients

- [Helios: Ethereum light client](https://github.com/a16z/helios)
- [Reth 1.0 Release](https://www.paradigm.xyz/2024/06/reth-prod)

## EVM Tools 

**Multichain**

- [Mesc](https://paradigmxyz.github.io/mesc/what_is_mesc.html)

**Testnet Resources**

- [ERC-20 Faucet](https://github.com/bokkypoobah/WeenusTokenFaucet?tab=readme-ov-file)
- [Goerli ETH Bridge](https://testnetbridge.com/)

**Useful Modules**

- [ZkDrop, A ZK Airdrop Scheme](https://github.com/a16z/zkdrops)
- [Uniswap Merkle Distributor](https://github.com/Uniswap/merkle-distributor)

**Ether Deck Mk2**

A Reasonably optimized, extensible smart account.

- [github repo](https://github.com/jtriley-eth/ether-deck-mk2)
- [helper scripts for ether deck mk2](https://github.com/jtriley-eth/decktools-mk2?tab=readme-ov-file)

#### **Backend**

- [Solidity Decompiler (interface)](https://ethervm.io/decompile)
- [Heimdall-rs](https://github.com/Jon-Becker/heimdall-rs): An advanced EVM smart contract toolkit specializing in bytecode analysis
- [WhatsABI](https://github.com/shazow/whatsabi)
- [go-selfcompile](https://github.com/shazow/go-selfcompile)
- [scope-eth](https://marketplace.visualstudio.com/items?itemName=popular.scope-eth): Remix-like foundry VSCode plugin
- [arbiter](https://github.com/primitivefinance/arbiter): Simulation driven development via an EVM emulator
- [Echidna](https://github.com/crytic/echidna): Fast smart contract fuzzer
- [Medusa](https://github.com/crytic/medusa): Parrellizable fuzz testing through CLI or Go API
- [Simple Serialization](https://simpleserialize.com/): A serialization and merkleization standard created specifically for Ethereum consensus
- [MergeMock](https://github.com/protolambda/mergemock)
- [EVM.codes](https://www.evm.codes/?fork=shanghai)


#### **Full-Stack**

- [Scaffold Eth](https://github.com/scaffold-eth/scaffold-eth-2)

## Resources

- [Solidity Lang Docs](https://docs.soliditylang.org/en/v0.8.21/)
- [Solving a CTF](https://x.com/vinami/status/1728482477965213760?s=20)
- [Rareskills Blog](https://www.rareskills.io/blog)


### fhEVM

- [fhEVM: Confidential EVM Smart Contracts using Fully Homomorphic Encryption](https://github.com/zama-ai/fhevm/blob/main/fhevm-whitepaper.pdf)

## Security

- [Trapdoor Tokens on Uniswap](https://twitter.com/0xflashmine/status/1781417942954938526)