---
title: Ukraine Psyop
description: Ukraine is a critical component within a larger story
---

Below I will explain a controversial, perhaps “conspiracy”-like opinion, with which I do not necessarily support. At this point, I recognize I do not know enough about the situation to confidently and firmly stand behind a particular side. However, I believe a disregard of the below content at face value, without genuine thought, is objectively wrong. With that, I ask you read the below content with an open mind, regardless of the seeming absurdity of the claims.

## Thesis

The Russia x Ukraine conflict is a military-grade, organized psyop by global elites. 

### The War in Iraq: A Comparison

To appreciate the ability of economic incentives to motivate psychological operations aimed towards international conflict, I would like to bring up the a case study: the War in Iraq. much like the false claims of weapons of mass destruction which led to the previously unpopular invasion of Iraq. 

### WEF New World Order: A Global Pandemic, then International Conflict

On March 27, 2018, the NIH-EcoHealth Alliance submitted a proposal to DARPA, requesting $14,209,245 in funding for *Project DEFUSE: Defusing the Threat of Bat-borne Coronaviruses.*

*Excerpt from **Executive Summary, Technical Approach 1***

> We will sequence their spike proteins, reverse engineer them to conduct binding assays, and insert them into bat SARSr-CoV (WIV1, SHC014) backbones (these use bat-SARSr-CoV backbones, not SARS-CoV, and are exempt from dual-use and gain of function concerns) to infect humanized mice and assess capacity to cause SARS-like disease.
> 

In an email to a US Marine Corps Captain (unidentified), Major Joe Murphy of the Office of Naval Research outlined some concerns that arose after he “came across additional incriminating documents and produced an analysis shortly after leaving DARPA last month.”

In the email to his superior, Major Joe Murphy explained the following.

> I’m unsure whether the significance of what I communicated is understood by those that received the report. Decisions with regards to the vaccines do not appear to be informed by analysis of the documents. The main points being that SARS-CoV-2 matches the SARS vaccine variants the NIH-EcoHealth program was making in Wuhan; that the DOD rejected the program proposal because vaccines would be ineffective and because the spike proteins being inserted into the variants were deemed too dangerous (gain-of-function); and that the DOD now mandates vaccines that copy the spike protein previously deemed too dangerous. To me, and to those who informed my analysis, this situation meets no-go or abort criteria with regards to the vaccines until the toxicity of the spike protein can be investigated. There’s also information within the documents about which drugs effectively treat the program’s SARS-CoVs.
> 

Major Joe Murphy was correct. On August 13, 2021, the Defense Advanced Research Projects Agency (DARPA) unclassified a document with subject: *SARS-CoV-2 Origins Investigation With US Government Program Undisclosed Document Analysis.*

In this document, the Commandant of the Marine Corps Fellow, DARPA, states the following.

*Excerpt from Page 1*

> SARS-CoV-2 is an American-created recombinant bat vaccine, or its precursor virus. It was created by an EcoHealth Alliance program at the Wuhan Institute of Virology (WIV), as suggested by the reporting surrounding the lab leak hypothesis. The details of this program have been concealed since the pandemic began. These details can be found in the EcoHealth Alliance proposal response to the DARPA PREEMPT program Broad Agency Announcement (BAA) HR00118S0017, dqted March 2018 - a document not yet publicly disclosed.
> 

*Excerpt from Page 2*

> Because of its (now) known nature, the SARs-CoV-WIV’s illness is readily resolved with early treatment that inhibits the viral replication that spreads the spike proteins around the body (which induce a harmful overactive immune response as the body tries to clear the spikes from the ACE2 receptors). Many of the early treatment protocols ignored by the authorities work because they inhibit viral replication or modulate the immune response to the spike proteins, which make sense within the context of what EcoHealth was creating. Some of these treatment protocols also inhibit the action of the engineered spike protein. For instance, Ivermectin (identified as curative April 2020) works throughout all phases of illness because it both inhibits viral replication and modulates the immune response. Of note, chloroqine phosphate (Hydroxychloroquine, identified April 2020 as curative) is identified in the proposal as a SARSr-CoV inhibitor, as is interferon (identified May 2020 as curative).
> 

> The gene-encoded, or “mRNA,” vaccines work poorly because they are synthetic replications of the already-synthetic SARSr-CoV-WIV spike proteins and posses no other epitopes. The mRNA instructs the cells to produce synthetic copies of the SARSr-CoV-WIV synthetic spike protein directly into the bloodstream, wherein they spread and produce the same ACE2 immun storm that the recombinant vaccine does.
> 

> The massive, “Manhattan-Project”-level of information suppression executed by the government and the Trusted News Initiative indicates that it would be covered-up if something bad happened. The lab-leak hypothesis and squabbling between Senator Paul and Dr. Fauci indicated that the cover up would be more disciplined in its paperwork. So I presumed that unclassified files would be concealed on a higher network and found them where I expected them to be. I understood what they were and their content, pushed the files off-site, and compiled this report.
> 

 “

The proposal was rejected by the Department of Defense (DOD) in 2018 “because vaccines would be ineffective and because the spike proteins being inserted into the variants were deemed to dangerous (gain-of-function)...” 

In November 2019, a Sars-COV-2 virus was identified just outside the Wuhan Institute of Virology. In 2018, 

Below is an article wherein a member of the SPI-B, a subcomittee that advises the cientific Advisory Group for Emergencies (SAGE), admits a regret of the use of fear as a dystopian measure of population control.

[The Telegraph 20210514 Use of fear to control behaviour in Covid crisis was ‘totalitarian’, admit scientists - Document PDF.pdf](Russia%20x%20U%2092279/The_Telegraph_20210514_Use_of_fear_to_control_behaviour_in_Covid_crisis_was_totalitarian_admit_scientists_-_Document_PDF.pdf)