---
title: "mRNA Vaccine"
description: "SARS-CoV-2"
page-layout: full
---

## Resources

- [Australia Senate Hearing: Pfizer representative admits that they don't understand the mechanism by which the vaccine causes myocarditis](https://twitter.com/DrEliDavid/status/1687533886816067584?s=20)

## "Horse Dewormer", A necessary Narrative for FDA emergency Authorization

FDA emergency authorization of a vaccine/medicinal treatment, by law, cannot be administered if an existing medication is provably effective in reducing the risks associated with the disease/virus. 

TODO


## mRNA Vaccine x Myocarditis/Pericarditis

---

Different virus vs vax myocarditis mechanisms isn't just theory. Here's why you're correct in real life.

### TIMING
a. Virus myocarditis
As Offit said, SARS2 viral myocarditis most often manifests as *post-viral myocarditis* due to *molecular mimicry*.

This means a *few to several weeks* after covid infection (ie symptoms/viral load were already gone weeks or 1-2 months ago), there is Ab/T crossreactivity (mimicry) to self-antigens in heart cells.

This mechanism is most often mild, good prognosis.

To clarify, SARS2 viral *fulminant myocarditis*, which can occur in *days to a week* after covid infection, is *very rare*. Initial covid presentation with fulminant myocarditis is so rare and unusual, it's a case report. Almost all SARS2 viral myocarditis is post-viral and mild.

b. Vax myocarditis
Most often occurs *days to 1 week* after 2nd vax dose. Also occurs after *1st vax dose* or booster.

This timing is *atypical* of mimicry. Rather, this timing is textbook for a primary or secondary *direct immune cell attack* on mRNA-transfected heart cells.

Offit knows all this. He's obviously pulling a "limited hangout". Pfizer will copy what Offit says.

If politicians were honest, they'd ask if mechanisms are the same (mimicry) for both virus and vax myo, then why are the timing and severity distinctly different for virus vs vax myo?

### SERUM VAX SPIKE
There's a high correlation of vax spike found in serum (blood) of vax myocarditis. Vax controls showed no serum vax spike.

Importantly, Ab/T immunoprofiling of vax myocarditis patients were *indistinguishable* from vax controls (ie no unusual autoantibodies or autoreactive T cells (no mimicry signs)).

This is more evidence that in vax myo, your immune cells are killing your own heart cells that look virus-infected.

There's more vax myo mechanisms like inflammasome or apoptosis. But you said the main vax myo mechanism perfectly."

[Circulating Spike Protein Detected in Post–COVID-19 mRNA Vaccine Myocarditis](https://www.ahajournals.org/doi/10.1161/CIRCULATIONAHA.122.061025#:~:text=We%20discovered%20that%20individuals%20who,immune%20activation%20with%20cytokine%20release)

---