---
title: 9/11 Canspiracy
---

## Components

- Tower could not have completed collapsed without bombs

- FOX freelancer "Mark Walsh" is actor mark humphrey; did an interview day of

- “I have seen first-hand what Israel has achieved. The desert is blooming again, and we can be so proud of the role that America has played in this success.” — Hillary Clinton @ AIPAC 2008

- “I'm gonna be dead, Matt, when they finally figure it out.” — George Bush @ NBC 2010

## Practice Drills on 9/11

Operation northern vigilance
- global guardian
- vigilant guardian
- vigilant warrior
- national reconnaissance officer drill
- operation tripod

### Insider Trading

- 2000 "contracts betting stock would go down" in United the day before; 90x more than previous 3 weeks

- 180,000 to 2.4mm in trade on United
- 337,000 trade on Monday, on American Airlines becomes 1.8mm
- Increase in bets against Morgan Stanley

**Larry Silverstein**

- 99 yr lease on twin towers 6 weeks before 9/11
- insures both for 3.2b against acts of terrorism and ensures he can buy new WTC complex if destroyed
- wife convinces him to attent dermatology appointment on morning of 9/11 instead of scheduled meeting in North tower
    - doctors appointment was cancelled, so he walked around nyc instead of getting breakfast at top of tower like normal
- he also owned WTC 7 which collapsed for unknown reason
- files claim for 7b saying it was 2 separate events
- settles for 4.5b
- builds new WTC
- larrys daughter also missed work in the towers that day
- larrys son was running late to work that day
