---
title: "Overview"
description: "An overview of miner extractable value"
page-layout: full
---

## Dashboards & Tools

- [ZeroMEV Explorer](https://zeromev.org/)
- [EigenPhi: Arbitrage Dashboard](https://eigenphi.io/)
- [MEV Boost](https://boost.flashbots.net/#block-6163a685d84444a9be309d26f18b4b2f)
- [Manifold Freelay](https://github.com/manifoldfinance/mev-freelay)

## Research

### Early Research

- [Enter the Hydra](https://eprint.iacr.org/2017/1090.pdf)
- [The Cost of Decentralization in 0x and EtherDelta](https://hackingdistributed.com/2017/08/13/cost-of-decent/)
- [Flash Boys 2.0](https://arxiv.org/pdf/1904.05234.pdf)
- [Order-Fairness for Byzantine Consensus](https://eprint.iacr.org/2020/269)
- [Themis: Fast, Strong Order-Fairness in Byzantine Consensus](https://eprint.iacr.org/2021/1465.pdf)
- [MEV... Wat Do?](https://pdaian.com/blog/mev-wat-do/)
- [Ethereum is a Dark Forest](https://medium.com/@danrobinson/ethereum-is-a-dark-forest-ecc5f0505dff)
- [Flashbots: Frontrunning the MEV Crisis](https://medium.com/flashbots/frontrunning-the-mev-crisis-40629a613752)

### General

- Studying Flash Loan Attacks | [paper](https://t.co/PpoqupGAe1)

- MEV by Galaxy Digital | [Blog Pt 2](https://www.galaxy.com/research/whitepapers/mev-the-rise-of-the-builders/)

- Modular MEV [Write-up](https://t.co/4mHc6NuVtm)

- [Performant routing and latency benchmarking for Ethereum RPC and Relay Service Providers](https://hackmd.io/@manifoldx/draft-perf-relay)

- High Granularity Cex Data | [tardis.dev](https://docs.tardis.dev/api/getting-started)

- MEV in Fixed Price Auctions | [paper](https://arxiv.org/abs/2303.04242) | [tweet](https://twitter.com/facu_zeta/status/1633860626773671936?s=20)

- MEV Boost Capella Upgrades | [article](https://flashbots.notion.site/MEV-Boost-Capella-Upgrades-00cea01704794f6eb4f792c55b69c441)

- Frontier Research | [website](https://frontier.tech/)

- [So you want to run a builder?](https://github.com/flashbots/mev-boost/issues/145)

- [How to Fix Ethereum's MEV Problem](https://www.coindesk.com/markets/2021/07/27/how-to-fix-ethereums-mev-problem-and-give-traders-the-best-price/)
- [MEV in ETH2 - An Early Exploration](https://hackmd.io/@flashbots/mev-in-eth2)
- [Improving PoS Economic Security via MEV Redistribution](http://people.eecs.berkeley.edu/~ksk/files/MEV_Redistribution.pdf)
- [Towards a Theory of MEV I](https://people.eecs.berkeley.edu/~ksk/files/MEV_CFMM.pdf)

- [Flashbots Research Repository](https://github.com/flashbots/mev-boost/wiki/Research#open-questions)

### MEV-Boost / Proposer-Builder Separation

- [Proposer Boost Considerations](https://notes.ethereum.org/@casparschwa/H1T0k7b85)
- [MEV-Boost Plan](https://github.com/flashbots/mev-boost/wiki/The-Plan-(tm))

### Videos & Talks

- [MEV Day](https://flashbots.notion.site/flashbots/mev-day-836f88806995412dabc1c7bb7ce4e830)
    - [Video Recap](https://www.youtube.com/playlist?list=PLRHMe0bxkuel3w3C7P_WVvp9ShLi3HKRI)

- [Encode x Wintermute: MEV with Robert Miller](https://youtu.be/W3GOGesPKlw)
- [Stanford MEV Workshop Recording](https://www.youtube.com/watch?v=5JmER64a0Xk)

- MEVconomics Playlist | [youtube](https://www.youtube.com/playlist?list=PLXzKMXK2aHh7bW0j2dhpnLNiIJIMnPgsD)



### Protocols, and Implementation Resources

Uniswap V3 Book
- [docs](https://uniswapv3book.com/docs/milestone_4/factory-contract/) 

Automated Market Making and Arbitrage Profits in the Presence of Fees
- [paper](https://moallemi.com/ciamac/papers/lvr-fee-model-2023.pdf)

MEV Capturing AMM
- [proposal](https://ethresear.ch/t/mev-capturing-amm-mcamm/13336)

Time to Bribe: Measuring Block Construction Markets
- [paper](https://eprint.iacr.org/2023/760.pdf)

A Framework for Building Searchers
- [article](https://mirror.xyz/0x00000a2A02540A0D92e209F9f5F7e104745e06Ba/hB-XeiOfkV5neiwX34lBD0uLHlWdefbGX6oBz1B4o7w)

Someone's Mega-resource on MEV
- [notion](https://thedailyape.notion.site/MEV-8713cb4c2df24f8483a02135d657a221)

Running MEV-Relay at Scale 
- [notion](https://flashbots.notion.site/Running-mev-boost-relay-at-scale-4040ccd5186c425d9a860cbb29bbfe09)

Latency Arms Race 
- [post](https://ethresear.ch/t/latency-arms-race-concerns-in-blockspace-markets/14957)

FBAs (frequent batch auctions) are a nerd snipe 
- [tweet](https://twitter.com/0x94305/status/1597019084667117569?s=20)

JaredFromSubway.eth's Access Lists
- [etherscan](https://etherscan.io/tx/0xd0e3759e51642568364776b4f389805323b2f3dd17a07ef2c53d3ffd6bb022d4#accesslist)

