--- 
title: Quantum
description: Why did the quantum computer get kicked out of school? Because every time the teacher turned around, it was in a superposition of playing games and doing homework!
---

## Resources

- [Quantum Hamiltonian-Based Models & the Variational Quantum Thermalizer Algorithm](https://arxiv.org/pdf/1910.02071.pdf)
- [Limitations of optimization algorithms on noisy quantum devices](https://www.nature.com/articles/s41567-021-01356-3)
- [Variational Quantum Thermalization](https://deep-1645.medium.com/variational-quantum-thermalization-and-the-future-of-quantum-thermodynamics-75ee9916ec3c)
- [Simulating Quantum Computers Using OpenCL](https://arxiv.org/pdf/1805.00988.pdf)
- [Upgrading qsim, Google Quantum AI's Open Source Quantum Simulator](https://opensource.googleblog.com/2021/11/Upgrading%20qsim%20Google%20Quantum%20AIs%20Open%20Source%20Quantum%20Simulator.html)
- [Closed Timelike Curves Make Quantum and Classical Computing Equivalent](https://arxiv.org/abs/0808.2669)
- [Running Quantum Software on a Classical Computer](https://www.sciencedaily.com/releases/2021/08/210803121404.htm)
- [Variational Quantum Thermalization and the Future of Quantum Thermodynamics](https://deep-1645.medium.com/variational-quantum-thermalization-and-the-future-of-quantum-thermodynamics-75ee9916ec3c)
- [Evidence for the utility of quantum computing before fault tolerance](https://www.nature.com/articles/s41586-023-06096-3)
- [Quantum Computation and Quantum Information](http://mmrc.amss.cas.cn/tlb/201702/W020170224608149940643.pdf)
- [Computational Supremacy in Quantum Simulation](https://arxiv.org/abs/2403.00910)

## Digital Analog

Digital-analog quantum computing is a computational paradigm which employs an analog Hamiltonian resource together with single-qubit gates to reach universality.

- [Digital-analog quantum computation with arbitrary two-body Hamiltonians](https://journals.aps.org/prresearch/abstract/10.1103/PhysRevResearch.6.013280)

## Foundational

- 1994 Daniel Simon, [On the Power of Quantum Computation](https://ieeexplore.ieee.org/document/365701)

**Shor's Algorithm**

- 1994, [Algorithms for Quantum Computation: Discrete Logarithms and Factoring](https://ieeexplore.ieee.org/document/365700)

2023, Regev's Algorithm - An improvement on Shor's

- [Thirty Years Later, a Speed Boost for Quantum Factoring](https://www.quantamagazine.org/thirty-years-later-a-speed-boost-for-quantum-factoring-20231017)
- [An Efficient Quantum Factoring Algorithm](https://arxiv.org/abs/2308.06572)

2023, A memory improvement on Regev's

- [Optimizing Space in Regev's Factoring Algorithm](https://arxiv.org/abs/2310.00899)

## Logical Gate Speed

### Photonic Quantum Computer

- [What is the logical gate speed of a photonic quantum computer?](https://quantumfrontiers.com/2023/06/21/what-is-the-logical-gate-speed-of-a-photonic-quantum-computer/)

**Summary**

The blog post, written by Terry Rudolph from PsiQuantum & Imperial College London, discusses the logical gate speed of a photonic quantum computer. The author argues that photonic quantum computers can perform computations orders of magnitude faster than superconducting qubit machines, even if every physical timescale of the photonic machine was slower. This is due to the unique properties of photonics, such as the ability to store/delay photons in long lengths of optical fiber with very low error rates, and the potential for active-volume architectures that can perform non-trivial computational gates more efficiently.

**Notes**

**1. Photonic Quantum Computers:** Photonic quantum computers use light (photons) to carry out quantum computations. They have the potential to perform computations faster than superconducting qubit machines due to their unique properties.

**2. Logical Gate Speed:** The logical gate speed of a quantum computer is determined by the rate at which it can perform quantum logic gates. In photonic quantum computers, this is influenced by the rate of entangled photon production and the speed of optical switches.

**3. Interleaving:** Photonic quantum computers can use a technique called interleaving, where many resource states are produced by a single resource state generator. This is possible due to the ability to store/delay photons in long lengths of optical fiber with very low error rates.

**4. Active-Volume Architectures:** Active-volume architectures in photonic quantum computers can eliminate the majority of resource consumption expended on idling qubits by performing non-trivial computational gates. This is possible due to the ability to perform a limited number of non-nearest neighbor fusions between photons.

**5. Resource State Generation:** The speed and scale of resource state generation is a critical factor in determining the logical gate speed of a photonic quantum computer. High repetition rates have been achieved in the production of single photons via a probabilistic parametric process.

**6. Future of Quantum Computing:** The author believes that the long-term future of quantum computing is ultimately photonic due to the potential for high-speed resource state generation and the unique properties of photonics.

**7. Applications:** The author provides an example of breaking elliptic curve cryptosystems on a quantum computer using Shor’s algorithm. He shows that a photonic quantum computer with an active-volume architecture can perform the computation significantly faster than a superconducting qubit machine.

**8. Conclusion:** The author concludes that the logical gate speed of a photonic quantum computer is not solely determined by the physical timescales of the machine. Instead, it is influenced by the unique properties of photonics and the efficient parallelization achieved through long-range connections in the photonic active-volume device.