---
title: Ethereum Consensus 
---

## Consensus Design

- [Ethereum Consensus Spec](https://github.com/ethereum/consensus-specs)
- [Casper the Friendly Finality Gadget](https://arxiv.org/abs/1710.09437)
- [Combining GHOST and Casper](https://arxiv.org/abs/2003.03052)
    - [elopio's annotations](https://elopio.keybase.pub/papers/2020-combining_ghost_and_casper.pdf)
- [Beacon Chain Casper Mini-Spec](https://ethresear.ch/t/beacon-chain-casper-mini-spec/2760/17)
- [zkCasper: SNARK based scheme for verifying the Ethereum's Casper FFG consensus proofs](https://research.polytope.technology/zkcasper)
- [Beacon Chain Casper Mini-Spec](https://ethresear.ch/t/beacon-chain-casper-mini-spec/2760/17)
- [Ethereum Inactivity Leak](https://eth2book.info/capella/part2/incentives/inactivity/)

## Consensus Attacks

- [Long Range Attacks on PoS](https://www.youtube.com/watch?v=-uxHoEfxXC4)
- [Two Attacks on Proof-of-Stake GHOST/Ethereum](https://arxiv.org/pdf/2203.01315.pdf)
- [Three Attacks on Proof-of-Stake Ethereum](https://arxiv.org/abs/2110.10086)
- [Balancing Attack on Gasper](https://ethresear.ch/t/a-balancing-attack-on-gasper-the-current-candidate-for-eth2s-beacon-chain/8079)
- [Mitigating Balancing Attacks on LMD GHOST](https://notes.ethereum.org/@vbuterin/lmd_ghost_mitigation)
- [Discouragement Attacks](https://eth2book.info/capella/part2/incentives/rewards/#discouragement-attacks)
- [Vitalik on Discouragement](https://github.com/ethereum/research/blob/master/papers/discouragement/discouragement.pdf)

## Proof of Stake

- [100 Days After the Merge](https://www.galaxy.com/research/insights/100-days-after-the-merge/)
- [Withdrawals after Shanghai](https://dataalways.substack.com/p/partial-withdrawals-after-the-shanghai)
- [Official Merge Announcement](https://blog.ethereum.org/2022/08/24/mainnet-merge-announcement/)
- [Exploring Inequality in Proof of Stake](https://ethereum.github.io/beaconrunner/notebooks/naiveurn.html) by Barnabe Monnot (RIG/EF)
- [What Happens After Finality in eth2](https://hackmd.io/@prysmaticlabs/finality) by Raul Jordan (Prysmatic)
- [Rocketpool Post-Merge research](https://github.com/rocket-pool/rocketpool-research/tree/master/Post%20Merge)
- [(Un-)Timeliness in PoS Ethereum](https://notes.ethereum.org/@casparschwa/ByHu1XZUq) by Caspar Schwarz-Schilling (RIG/EF)

## Ethereum Consensus Issues: May 12, 2023

- [tweet one](https://twitter.com/potuz1/status/1657031082749861891?s=20)
- [tweet two](https://twitter.com/TaylerUSA/status/1656840323392208899)