---
title: Real World Assets
---

## Checker, Jack Chong

- [Checker Deck, 2023](checker-deck.pdf)
- [Checker Deck 2, 2023](checker-deck.pdf)

The sell-side of RWAs are pushing the frontier right now. JPM, Softgen, etc benefit by saving ~35% of issuance cost.

The market needs a push on the buy-side.

"I want exposure to x"

"You have to set up x wallet, bridge to y chain..."

Need to abstract the complexity of the technology.

### Team

Justin McMahan

- 15yr Morgan Stanley Prime Brokerage, 
- Tower Research: set up middle and back office (exchange, data connectivity, SEC reporting).
- Abra: Series C high network OTC desk

Mike

- head of trade ops Abra
- Taconic, set up technology and processes

### Market

There is no standard for tokenized assets. Treasury tokens, for example, can be diffierent in

- underlying blockchain
- asset lifecycle (issuance payment, maturity, etc.)

There is no right or wrong solution, different issuers will do things differently. Sell side will optimize for themselves.

### Example

SocGen, french bank, has a subsidiary called forge.

Did a deal with maker, borrowed DAI.

French banks are good at selling complex derivative issuances. By automating the entire process on the blockchain, they save moeny.

They have $100mm of complex derivatives they want to sell on chain. They have a buyer, BNP european bank. They like the product, they want to buy in. BNP asset manager has tradfi systems, they are not equipped to trade tokenized asset. How do you book the information on the system?

### Product

- Connectivity to all sell-side islands, and provide single API to buy-side. 
- Relay trade to sell-side, post transaction logs for reporting, etc.

### Go-to-market

Digital Asset DAML is incentivized to sell as many financial products as possible. Technologically, they are good at selling. 

working with design partners (sell-side): close with
- SocGen
- Forge
- Zodia Custody
- Coinbase management
- Standard Chartered subsidiary

they build integrations to buy-side tech stack. trading systems starting with
- Eze, back office
- FIS

TradFi funds looking for technology solutions ask JPM, GS, MS
"this is the accountign software you should use, this is the etc you should use"

they have monthly catch ups with hedge fund prime brokerage

They are not custodian. Custodian


### Questions

- to a certain extent, underlying blockchain is imnportant

- SocGen example, would they issue on cosmos, eth mainnet, or their own blockchain for enterprise customers?
    - either Eth mainnet, permissioned or permissionless
    - or canton network
    - R3 Corda does interbank, CBDC, cash transfers

- What does the product look like. 
    - will you custody people's funds?
    - will you abstract other custody solutoions?


## Resources

- [Digital Asset DAML](https://www.digitalasset.com/)
    - used to have their own chain
    - CoFounder: blythe masters, left to start her own PE shop

- [Canton Network](https://www.canton.network/)
    - this is Digital Asset DAML's blockchain
    - UBS, Microsoft, Cumberland, etc
    - Versana targets syndicated loan markets

- [R3 Corda]


Long Tail
- Goldfinch
- 


Custody

- coinbase custody
- JPM, MS



Lead offer expiring next thursday, 
- acquinow committed
- a couple angels
    - LP in polychain
    - fund manager, ex circle
    - abu dhabi catch up

Raising 2mm SAFE on 10mm cap
