---
title: Pursuit of the 2nd Amendment
---

## NYC Gun Community

- [Tiro a Seguro: NYC Black Tie Underground Shooting Range](https://guestofaguest.com/new-york/nyc/an-underground-black-tie-shooting-range-in-nyc-welcome-to-tiro-a-segno?slide=5)

## NYC Pistol Premise Application Process and Timeline

- **08/26/2022** NYPD License Division Portal Account Created

Delay here is on my end, don't recall exactly when I submitted the application, but certainly was well after this date.

- **10/17/2023** Notice for In-Person Payment Required to Complete Application: Our records indicate that you have initiated an application for a Gun Custodian handgun license, and that you have requested to pay the application fee in-person. Your initiated application is not considered complete until payment of the application fee is made.

- **10/17/2023** Payment received: The New York City Police Department License Division has received your application for Premise Residence handgun license. Payment of your application fee was also received.

- **10/18/2023** Fingerprint appointment scheduled (and missing documentation notice): Thank you for submitting your firearm license application to the NYC Police Department Licensing Division.
A review of your application revealed that YOU ARE MISSING MANDATORY DOCUMENTS. The missing documents are itemized in the attached PDF. Please UPLOAD MISSING DOCUMENTS BEFORE YOUR SCHEDULED APPOINTMENT. If you need assistance finding forms or uploading your documents, please follow the “Upload Instructions” attached to this email.
The next step is to come in for fingerprinting. Your appointment has been scheduled for: TUESDAY, NOVEMBER 21, 2023

- **11/16/2023** Confidentiality request decision: Your Confidentiality Request is Approved. [Confidentiality Information here](https://licensing.nypdonline.org/FOILRequestDetail/?AspxAutoDetectCookieSupport=1)

- **11/20/2023** Fingerprint Appointment Rescheduled: Good afternoon, Applicant, Due to a promotion ceremony that will be held at One police plaza tomorrow. Unfortunately, we will have to reschedule, your next appointment date will be Wednesday November 22nd, 2023, 

## Firearm Setup

- FN 509 (compact or midsize?) tactical
- obsidian rugged silencer
- subsonic 9mm ammo