---
title: "Fundamental?"
description: "The Quantum Theory of Fields: Effective or Fundamental?"
page-layout: full
---

The Quantum Theory of Fields: Effective or Fundamental?

- [video](https://www.youtube.com/watch?v=1mQ0Yu2x9vE)
- [corresponding article](https://cerncourier.com/a/steven-weinberg-master-builder-of-the-standard-model/)
- Quantum Field Theory was born just pertaining to the electromagnetic field.
- When expanding this theory, it seemed it couldn't be trusted at high energies. (Decline)
- Late 1940s, there was a new optimizing with the invention of a relatavistic perturbation theory, where the infinities could be absorbed into a redefinition of parameters like mass and charge of the electron. People thought this was sweeping problems under the rug, but it also may have been a way of selecting good theories (renormalizable theories).
- For example, theere's nothing in the symmetries of quantum electrodynamics which rules out putting a term in the field equations (or Lagrangian), which could make the magnetic moment of the electron anything you want. This would make the mass of the electron -1, which means the theory is not renormalizable, and thus shows invalid.
- Late 1960s and early 70s, the standard model came to fruition - this was the renaissance of Quantum Field theory. But there were still doubts whether this was a fundamental theory or an effective one.
- Quantum Field Theory & Einsteinian Physics may be low energy approximations of a more fundamental theory.