---
title: Cognition
description: All things cognitive health
page-layout: full
---

## Resources

- [Chimera states in brain networks: empirical neural vs. modular fractal connectivity](https://arxiv.org/abs/1710.08219)
- [Neurological Activity of Lion’s Mane (Hericium erinaceus)](https://restorativemedicine.org/journal/neurological-activity-lions-mane-hericium-erinaceus/)

### Olfactory enrichment

Olfactory enrichment (aroma therapy) at night produces improvements in both cognitive and neural functioning.

- [Overnight olfactory enrichment using an odorant diffuser improves memory and modifies the uncinate fasciculus in older adults](https://www.frontiersin.org/articles/10.3389/fnins.2023.1200448/full)

**Results:** A statistically significant 226% improvement was observed in the enriched group compared to the control group on the Rey Auditory Verbal Learning Test and improved functioning was observed in the left uncinate fasciculus, as assessed by mean diffusivity.

**Conclusion:** Minimal olfactory enrichment administered at night produces improvements in both cognitive and neural functioning. Thus, olfactory enrichment may provide an effective and low-effort pathway to improved brain health.

{{< include _external-neurons.qmd >}}