---
title: Computer Science
---

## Resources

- [Teach Yourself Computer Science](https://teachyourselfcs.com/)
- [From the Transistor to the Web Browser: Understanding the Modern Computer Stack from First Principles](https://github.com/geohot/fromthetransistor)
- [Leslie Lamport's works](https://lamport.azurewebsites.net/pubs/pubs.html?from=https://research.microsoft.com/users/lamport/pubs/pubs.html&type=path)

## Computer Science

### Distributed Computing

- ["Distributed Computing Through Combinatorial Topology" - Maurice Herlihy & Sergio Rajsbaum](https://www.google.com/search?q=%22Distributed+Computing+Through+Combinatorial+Topology%22+-+Maurice+Herlihy+%26+Sergio+Rajsbaum)

### Algorithms

- ["Combinatorial Optimization: Theory and Algorithms" - Bernhard Korte & Jens Vygen](https://www.google.com/search?q=%22Combinatorial+Optimization%3A+Theory+and+Algorithms%22+-+Bernhard+Korte+%26+Jens+Vygen)
- ["The Design of Approximation Algorithms" - David P. Williamson](https://www.google.com/search?q=%22The+Design+of+Approximation+Algorithms%22+-+David+P.+Williamson)

### Optimization

- ["Neuro-Dynamic Programming" - Dimitri P. Bertsekas & John N. Tsitsiklis](https://www.google.com/search?q=%22Neuro-Dynamic+Programming%22+-+Dimitri+P.+Bertsekas+%26+John+N.+Tsitsiklis)
- ["Abstract Dynamic Programming" - Dimitri P. Bertsekas](https://www.google.com/search?q=%22Abstract+Dynamic+Programming%22+-+Dimitri+P.+Bertsekas)
- ["Stochastic Approximation Algorithms and Applications" - Harold Joseph Kushner & George Yin](https://www.google.com/search?q=%22Stochastic+Approximation+Algorithms+and+Applications%22+-+Harold+Joseph+Kushner+%26+George+Yin)

## Dynamical Systems

- ["Catastrophe Theory" - V. I Arnold](https://www.google.com/search?q=%22Catastrophe+Theory%22+-+V.+I+Arnold)
- ["Stability Theory by Liapunov's Second Method" - Taro Yoshizawa](https://www.google.com/search?q=%22Stability+Theory+by+Liapunov%27s+Second+Method%22+-+Taro+Yoshizawa)
- ["The Dynamical System Generated by the 3n+1 Function" - Günther J. Wirsching](https://www.google.com/search?q=%22The+Dynamical+System+Generated+by+the+3n%2B1+Function%22+-+G%C3%BCnther+J.+Wirsching)

