---
title: "Nuclear"
description: "Fusion, Fission, and more"
---

## Nuclear

- [Stockpile Stewardship and Management Plan (SSMP)](https://www.energy.gov/nnsa/articles/stockpile-stewardship-and-management-plan-ssmp)

### 

is an academic development framework for a small, standard, pressurized water reactor. Our goal is to accelerate deployment of the world's most vital solution to climate change: Nuclear Energy.

- [Open-100](https://www.open-100.com/)
- [Mining valuable minerals from seawater: a critical review](https://pubs.rsc.org/en/content/articlehtml/2017/ew/c6ew00268d)
- [Indian scientists extract record uranium from seawater that could power nuclear plants](https://www.indiatoday.in/science/story/indian-researchers-extract-record-uranium-from-seawater-that-powers-nuclear-plants-1986196-2022-08-10)

## Fission

TODO

## Fusion 

#### December 5, 2023 (announced Dec. 13)

- [Press Conference: Secretary Granholm & DOE leaders Announced Fusion Breakthrough by DOE National Lab](https://www.youtube.com/watch?v=K2ktAL4rGuY)
- [LLNL Release](https://www.llnl.gov/news/igniting-future-hundreds-gather-celebrate-historic-fusion-achievement)
- [LLNL Video](https://www.youtube.com/watch?v=71gqaFoix1w)

The U.S. Department of Energy (DOE) and DOE’s National Nuclear Security Administration (NNSA) today (Dec. 13) announced the achievement of fusion ignition at Lawrence Livermore National Laboratory (LLNL) — a major scientific breakthrough decades in the making that will pave the way for advancements in national defense and the future of clean power. On Dec. 5, a team at LLNL’s National Ignition Facility (NIF) conducted the first controlled fusion experiment in history to reach this milestone, also known as scientific energy breakeven, meaning it produced more energy from fusion than the laser energy used to drive it. 

#### August 6, 2023 

[US scientists repeat fusion ignition breakthrough for 2nd time](https://www.reuters.com/business/energy/us-scientists-repeat-fusion-power-breakthrough-ft-2023-08-06/)