---
title: CIA
---

## Resources

- [Legacy of Ashes]()
- [Ted Kennedy FBI Files](https://ia800206.us.archive.org/5/items/ted-kennedy-fbifiles/TedKennedyFBIFiles.pdf)

### Ted Kennedy FBI Files

- During tenure of Helms, plan put into motion with gave CIA as much funds as necessary without knowledge of congress.

**Master Plan**

- 5 person team: Gen. Landsdale, William Colby, George Bush, Richard Armitage, Lt.Col. Ferrera.
- setup 2nd airline (first was flying tigers), named "overseas national airlines"
- Operation "Eagle II", enter drug smuggling business; became "Japanese/Singapore/New Zealand/Kentucky" connection
- Ferrera saved Baron Phillipe duDaphne from the Nazis during 01 mission of the OSS in WWII. Also faked Nazi credentials for the Rothschilds which enabled them to escape occupied France in 1943 - Baron Guy Rothschild was head of banking family at the time. 
- Mr. Marion Horn Jr. aka JR Horn from Kentucky.
- "Eagle II" changed to "Golden Triangle"
- Armitage ammassed over 100 billion