--- 
title: Security
---

## Resources

- [hackertest.net](http://www.hackertest.net/)
- [Security Reference Guide](https://s0cm0nkey.gitbook.io/s0cm0nkeys-security-reference-guide/blue-defense/device-hardening/windows-hardening-commands)

## Tools

- [Subdomain finder (e.g. ___.example.com)](https://www.geeksforgeeks.org/subfinder-tool-in-linux/)
    - [in use](https://twitter.com/hacker_/status/1575466236426670080?s=20&t=XaTcIuMck-s-sOQlsv_5sQ)
- [Scout2: AWS Security Tool](https://www.kitploit.com/2018/07/scout2-security-auditing-tool-for-aws.html?m=0)

Privacy Protect
- [github](https://github.com/therockstorm/privacy-protect)
- [website](https://www.privacyprotect.dev/)
- [original article](https://mprimi.github.io/portable-secret/)

Sim Swap Protectins
- [Efani](https://www.efani.com/how-it-works)

## Articles

- [EthClipper: A Clipboard Meddling Attack on Hardware Wallets with Address Verification Evasion](https://arxiv.org/pdf/2108.14004.pdf)
- [Only Safe Way to Store Crypto](https://officercia.mirror.xyz/p1ieZdxQWH4yHCNOXNPHyT8So1cY0X_wMGKwdmavi7s)
- [Tempest: Spying on information systems through leaking emanations](https://en.wikipedia.org/wiki/Tempest_(codename))

### Apple 

- [Post Quantum iMessage](https://security.apple.com/blog/imessage-pq3/)
- [Private Cloud Compute: A new frontier for AI privacy in the cloud](https://security.apple.com/blog/private-cloud-compute/)
M Series Sidechannel Attack
- [Unpatchable vulnerability in Apple chip leaks secret encryption keys](https://arstechnica.com/security/2024/03/hackers-can-extract-secret-encryption-keys-from-apples-mac-chips/)
- [paper](https://gofetch.fail/files/gofetch.pdf)
- [background video](https://www.youtube.com/watch?v=ARuU2s63Yhs)
- [background paper](https://ieeexplore.ieee.org/document/9833570)
- Relevant: [arm64 for apple platforms](https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms#Enable-DIT-for-constant-time-cryptographic-operations)


## Events

### i-SOON

- [Internal Chinese government document leak](https://x.com/BushidoToken/status/1759376010804392441?s=20)
- [github](https://github.com/I-S00N/I-S00N/)