--- 
title: Mysteries
description: Remaining Mysteries in Physics
---

## Intersting

Any oscillator — a pendulum, a spring, a firefly, a human heart cell — wants to match up with its neighbors. Mathematicians recently showed that [synchronization is inevitable in expander graphs](https://www.quantamagazine.org/new-proof-shows-that-expander-graphs-synchronize-20230724/), a type of network found in many areas of science.

## The Nature of Dark Matter

- Dark energy: 69%
- Dark matter: 26%
- Ordinary matter: 5%

Dark matter/energy appears to constitute 85% of the universe's matter content (e=mc^2). This substance does not admit, absorb, or reflect light. It's presence is inferred from gravitational effects on visible matter.

## Quantum Gravity

There is no reconciliation between quantum mechanics and general relativity. The former describes the universe at the smallest scales, while the latter describes the universe at the largest scales. The two theories are seemingly incompatible, and this problem has become the focal point in the search for a "theory of everything".

## The Measurement Problem in Quantum Mechanics

Quantum mechanics predicts outcomes only probabilisticly, and superpositions decohere upon measurement. The process of measurement is described differently from other physical processes. This raises deep questions about the nature of reality and consciousness in the physical world.

## Matter Antimatter Asymmetry

The Big Bang should have produced equal amounts of matter and antimatter, which would have then annihilated each other. However, the universe is made almost entirely of matter. This asymmetry is not explained by the Standard Model.

## Neutrino Masses and Mixing Angles

Neutrinos are elementary particles that only weakly interact with matter. Experiments have shown that neutrinos have mass and can change their type as they travel, but the origin of their mass and precise values of the mixing angles are unknown. Mixing angles are the parameters that describe the transformation of neutrinos from one type to another.

## Strong Charge-Parity Problem

Charge-parity (CP) symmetry states that the laws of physics should remain the same if a particle is replaced by its antiparticle (charge conjugation) and then its spacial coordinates are inverted (parity inversion). However, in storng interaction (one of the four fundamental fources), this symmetry isnt violated as much as the current theory predicts. This is known as the strong CP problem.

> The strong force holds together things that have the same charge - this is stronger than the electromagnetic force, and is why atoms with protons (and more importantly quarks) don't fly apart.

## Cosmic Inflation

We believe the universe is acceleratingly expanding, but we don't know why. 

## The Problem of Time

In QM, time is a background parameter, and the flow of time is universal and absolute. In GR, time is one aspect of spacetime and is relative and dynamical. There is no compatability between these two.