---
title: Seed Oils
---

## Seed Oils & Fatty Acids

- [Seed Oil](https://twitter.com/jeffnobbs/status/1618653988110606338)
- [Linoleic Acid is very high in Seed Oils](https://academic.oup.com/advances/article/4/3/311/4644566?login=true.)
- [Soybean oil lowers circulating cholesterol levels and coronary heart disease risk, and has no effect on markers of inflammation and oxidation](https://www.sciencedirect.com/sdfe/reader/pii/S0899900721002057/pdf)
- [Health risk assessment of As and Zn in canola and soybean oils consumed in Kermanshah, Iran](http://jaehr.muk.ac.ir/article_40222_bfe660a4db187dc5d091da437519d25a.pdf)
- [History of Seed Oils](https://twitter.com/_AustinHerbert/status/1650660870253584387?s=20)
- [Changes in Consumption of Omega-3 and Omega-6 Fatty Acids in US 20th Century](https://pubmed.ncbi.nlm.nih.gov/21367944/)
- [Soybean Oil](https://www.ourpaleolife.com/soybean-oil/)
- [Soybean Oil x Autism](https://www.sciencedaily.com/releases/2020/01/200117080827.htm#:~:text=Summary%3A,disease%2C%20anxiety%2C%20and%20depression.)
- [Soybean Oil has a ton of Linoleic Acid](https://www.hsph.harvard.edu/nutritionsource/2014/11/05/dietary-linoleic-acid-and-risk-of-coronary-heart-disease/#:~:text=Linoleic%20acid%20is%20the%20predominant,well%20as%20nuts%20and%20seeds.)


[Use of dietary linoleic acid for secondary prevention of coronary heart disease and death: evaluation of recovered data from the Sydney Diet Heart Study and updated meta-analysis](https://pubmed.ncbi.nlm.nih.gov/23386268/)

> **Conclusion:** Advice to substitute polyunsaturated fats for saturated fats is a key component of worldwide dietary guidelines for coronary heart disease risk reduction. However, clinical benefits of the most abundant polyunsaturated fatty acid, omega 6 linoleic acid, have not been established. In this cohort, substituting dietary linoleic acid in place of saturated fats increased the rates of death from all causes, coronary heart disease, and cardiovascular disease. An updated meta-analysis of linoleic acid intervention trials showed no evidence of cardiovascular benefit. These findings could have important implications for worldwide dietary advice to substitute omega 6 linoleic acid, or polyunsaturated fats in general, for saturated fats.