---
title: Nutrition
---

## General

- [Magnesium Dificiency](https://twitter.com/sadalsvvd/status/1626395989404704768)
- [Green Tea Nutrient](https://twitter.com/drkohilathas/status/1646466159254929408?s=20)
- [Oregano Oil, Natural Antibiotic](https://twitter.com/iluminatibot/status/1650264370319069185?s=20)
- [Neurological Activity of Lion’s Mane (Hericium erinaceus)](https://restorativemedicine.org/journal/neurological-activity-lions-mane-hericium-erinaceus/)

## Seed Oils

- [Seed Oil](https://twitter.com/jeffnobbs/status/1618653988110606338)
- [Linoleic Acid is very high in Seed Oils](https://academic.oup.com/advances/article/4/3/311/4644566?login=true.)
- [Soybean oil lowers circulating cholesterol levels and coronary heart disease risk, and has no effect on markers of inflammation and oxidation](https://www.sciencedirect.com/sdfe/reader/pii/S0899900721002057/pdf)
- [Health risk assessment of As and Zn in canola and soybean oils consumed in Kermanshah, Iran](http://jaehr.muk.ac.ir/article_40222_bfe660a4db187dc5d091da437519d25a.pdf)
- [History of Seed Oils](https://twitter.com/_AustinHerbert/status/1650660870253584387?s=20)
- [Changes in Consumption of Omega-3 and Omega-6 Fatty Acids in US 20th Century](https://pubmed.ncbi.nlm.nih.gov/21367944/)
- [Soybean Oil](https://www.ourpaleolife.com/soybean-oil/)
- [Soybean Oil x Autism](https://www.sciencedaily.com/releases/2020/01/200117080827.htm#:~:text=Summary%3A,disease%2C%20anxiety%2C%20and%20depression.)
- [Soybean Oil has a ton of Linoleic Acid](https://www.hsph.harvard.edu/nutritionsource/2014/11/05/dietary-linoleic-acid-and-risk-of-coronary-heart-disease/#:~:text=Linoleic%20acid%20is%20the%20predominant,well%20as%20nuts%20and%20seeds.)


## Portabello Mushrooms

Consumption of the Agaricus species mushrooms has increased considerably in Japan as the Japanese have become accustomed to Western cooking. The Agaricus species mushroom contains hydrazine derivatives known as Agaritine.

### Risks

#### From Paul Stamets

> Portabellos have a problem. All mushrooms should be cooked, and portabellos, in particular, should be cooked at high temperatures.

> There is an unfortunate group of compounds called agaritines. Agaritines are hydrazines that are heat unstable, so the good news is, you should cook them, and if you cook them well, then those mushrooms are not a problem. If you don’t cook them well, then these hydrazines are potentially problematic.

> Now, nature’s a numbers game: so, there are beneficial compounds, that, in some balance, may outweigh the negative effects of the hydrazines, the agaratines in these mushrooms, but that jury is still out so to speak.

### Academic Papers

[Agaritine from Agaricus blazei Murrill induces apoptosis in the leukemic cell line U937](https://www.researchgate.net/profile/Taei-Matsui/publication/50303608_Agaritine_from_Agaricus_blazei_Murrill_induces_apoptosis_in_the_leukemic_cell_line_U937/links/5ad06c08a6fdcc878411cd96/Agaritine-from-Agaricus-blazei-Murrill-induces-apoptosis-in-the-leukemic-cell-line-U937.pdf)

- Agaritine, a compound found in the medicinal mushroom Agaricus blazei Murrill, induces apoptosis (programmed cell death) in the leukemic cell line U937.
- Agaritine treatment caused a dose-dependent increase in apoptosis in U937 cells, as measured by the release of cytochrome c from mitochondria and the activation of caspases.
- Agaritine also induced the expression of pro-apoptotic proteins, such as Bax and Fas, and inhibited the expression of anti-apoptotic proteins, such as Bcl-2.
- These findings suggest that agaritine may have potential as a therapeutic agent for the treatment of leukemia.
- Agaritine treatment caused a significant increase in the number of apoptotic cells in U937 cultures, as measured by flow cytometry.
- Agaritine also induced the characteristic morphological changes of apoptosis, such as nuclear condensation and fragmentation.
- Western blot analysis showed that agaritine treatment increased the expression of Bax and Fas, and decreased the expression of Bcl-2.
- These findings suggest that agaritine may trigger apoptosis in U937 cells by activating caspases and upregulating pro-apoptotic proteins.
- The authors of the paper concluded that agaritine may have potential as a therapeutic agent for the treatment of leukemia. However, further studies are needed to confirm these findings and to determine the optimal dose and schedule of agaritine treatment.


[Quantities of agaritine in mushrooms (Agaricus bisporus) and the carcinogenicity of mushroom methanol extracts on the mouse bladder epithelium](https://europepmc.org/article/med/2132000)


- Agaritine is a carcinogenic compound found in mushrooms, including Agaricus bisporus (white button mushrooms).
- The authors of the paper measured the levels of agaritine in Agaricus bisporus mushrooms and found that the levels varied depending on the growing conditions.
- The authors also found that methanol extracts of Agaricus bisporus mushrooms were carcinogenic to the mouse bladder epithelium.
- These findings suggest that agaritine may be a risk factor for bladder cancer in humans.
- The authors measured the levels of agaritine in Agaricus bisporus mushrooms grown in different conditions, including open fields, greenhouses, and dark rooms.
- The levels of agaritine were highest in mushrooms grown in dark rooms, followed by mushrooms grown in greenhouses, and then mushrooms grown in open fields.
- The authors also found that methanol extracts of Agaricus bisporus mushrooms were carcinogenic to the mouse bladder epithelium.
- This was determined by the induction of tumors in the mouse bladder after treatment with the methanol extracts.
The authors concluded that agaritine may be a risk factor for bladder cancer in humans.


[Synthetic and Naturally Occurring Hydrazines as Possible Cancer Causative Agents](https://aacrjournals.org/cancerres/article/35/12/3693/480307/Synthetic-and-Naturally-Occurring-Hydrazines-as)

- Hydrazines are a class of compounds that have been shown to be carcinogenic in animals.
- Several synthetic hydrazines have been shown to cause cancer in humans, including 1,2-diethylhydrazine, 1,2-dinitrohydrazine, and 1,2-dibromohydrazine.
Hydrazines are also found naturally in some foods, including mushrooms, tobacco, and fish.
- There is some evidence that naturally occurring hydrazines may also be carcinogenic, but more research is needed to confirm this.
- The authors of the paper conclude that hydrazines are a potential risk factor for cancer, and that further research is needed to determine the extent of this risk.
- The authors reviewed the literature on hydrazines and cancer, and identified 19 synthetic hydrazines that have been shown to be carcinogenic in animals.
- The authors also identified several naturally occurring hydrazines that have been found in foods, including agaritine, gyromitrin, and BMAA.
- The authors concluded that hydrazines are a potential risk factor for cancer, and that further research is needed to determine the extent of this risk.
It is important to note that this paper was published in 1975, and there has been some research on hydrazines and cancer since then. However, the authors' conclusions are still valid, and further research is still needed to determine the extent of the risk of cancer from hydrazines.

[Genotoxicity of agaritine in the lacI transgenic mouse mutation assay: evaluation of the health risk of mushroom consumption](https://shdw-drive.genesysgo.net/G6zSEXeDjyBVUjJ87pxzg2EkPXvvTk9tBvZUhcZqw6PB/AgaritineGenotoxicity.pdf)

- Google Bard would not summarize this paper as it did for every other one (???)

> Using a previously derived quantitative correlation between mutagenicity in the lacI test and carcinogenic potency, the carcinogenicity of agaritine in mushrooms was estimated: the average Swiss mushroom consumption of 4 g/day would be expected to contribute a lifetime cumulative cancer risk of about two cases per 100,000 lives.

[Attempted tumor induction with agaritine in mice.](https://europepmc.org/article/med/7201775)