---
title: Deep State
---


## Resources

- Conspirator's Hierarchy: The Story of the Committee of 300 by Dr. John Coleman. Dr. John Coleman was an Intelligence Officer for over 45 years and his book of truth is based on 20 years of relentless research. 
- [The Committee of 300: An interesting take](https://twitter.com/SpartaJustice/status/1687208627696754689?s=20)

## Events

- Futility was a book about a ship named the titan sunk after hitting an iceberg with not enough lifeboats on board. Author died by poisoning 
- London attacks 2005; bbc radio 5 "at half past 9 this morning we were running an exercise based on simultaneous bombs..."
- boston marathon; operation urban shield

## Name Changing

[link](https://x.com/AtRealBen/status/1778822707020439556)

- Jonathan Stuart Leibowitz -> Jon Stewart
- Robert Allen Zimmerman -> Bob Dylan
- John Kohn -> John Kerry
- Michael Danielovitch -> Michael Douglas
- Jay Scott Greenspan -> Jason Alexander
- Chaim Witz -> Gene Simmons
- Gyorgy Schwartz -> George Soros
- Lawrence Harvey Zeiger -> Larry King
- Ralph Lifshitz -> Ralph Lauren
- Neta-Lee Hershlag -> Natalie Portman