---
title: Quantonation
---

> Following up on conversations about Quantonation yesterday. We currently have ~$100M under management in our first fund: a global, early stage fund investing in physics based startups, especially in quantum technologies where we are the main focused fund worldwide with a portfolio of 24 startups from pre-seed to Series B stages. Fund 1 closed in 2021 and now sits at ~2X+ multiple on deployed capital (~77M) with 2 early (smaller) exits. We have just begun first close for Fund 2, a $200M early stage fund similarly focused on quantum and deep physics technologies worldwide. More details are in the attached deck.

[Quantonation](https://www.quantonation.com/) is a VC Fund dedicated to quantum technologies.

- [Deck](media/quantonation2-us.pdf)

Companies

- [Quconnect](https://www.qunnect.inc/): Building hardware to transform telecommunications infrastructure into scalable quantum networks.
- [QPhox](https://qphox.eu/): Building a quantum modem device to connect quantum computers across a quantum network.
- [Nord Quantique](https://www.nordquantique.ca/): Building error-correcting quantum processors
- [Pasqal](https://www.pasqal.com/): Building real world quantum applications expected in the near-term.
