---
title: Quantitative Finance
---

## Resources

- [Free Trading Resources Notion Doc](https://milksandmatcha.notion.site/Free-Trading-Resources-v2-4456ae906000487181f3486dbd0dd631)

## Reads

- [the perfect way to smooth your noisy data](https://towardsdatascience.com/the-perfect-way-to-smooth-your-noisy-data-4f3fe6b44440)
- [Pattern mining for stock prediction with dynamic time warping](https://medium.com/@crisvelasquez/pattern-mining-for-stock-prediction-with-dynamic-time-warping-3f8df5fb4c5b)
- [Charting market rhythms: The rolling Hurst Exponent in Python](https://medium.com/@crisvelasquez/quantifying-stock-trends-the-rolling-hurst-exponent-in-python-d7108fc0e837)
- [Identifying key market interest with volume ratio in python](https://medium.com/@crisvelasquez/identifying-key-market-interest-with-the-volume-ratio-in-python-1f9904705711)
- [dynamic risk managament using rolling stock price metrics in python](https://medium.com/@crisvelasquez/dynamic-risk-management-using-rolling-stock-price-metrics-in-python-5d6ffcbf5ba)
- [maximizing profits with spy options trading using genetic algorithm based 1 minute trend detection](https://wire.insiderfinance.io/maximizing-profits-with-spy-options-trading-using-genetic-algorithm-based-1-minute-trend-detection-f20b602e9b96)


### Advanced Theory

- [Spoofing and Price Manipulation in Order Driven Markets](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3431139)
- [End-To-End Resource Analysis for Quantum Interior-Point Methods and Portfolio Optimization](https://journals.aps.org/prxquantum/abstract/10.1103/PRXQuantum.4.040325)


## Renaissance Technologies

- The Man Who Solved the Market: Good Book
- [A Maximization Technique Occuring in the Statistical Anlysis of Probabilistic Functions of Markov Chains](https://www.biostat.wisc.edu/~kbroman/teaching/statgen/2004/refs/baum.pdf)
- Unable to Find (Classified by the Institute of Defense Analyses): "probabilistic models for and prediction of stock market behavior 1964"
- [The Code Breaker: Bloomberg 2008 Article](https://math.berkeley.edu/~berlek/pubs/bloomberg.pdf)
