---
title: Environment
---

## Climate (Change)

- [NASA Evidence for Climate Change](https://climate.nasa.gov/evidence/)
- [IPCC baseline scenarios have over-projected CO2 emissions and economic growth](https://iopscience.iop.org/article/10.1088/1748-9326/abcdd2/pdf)
- [Hyporthermic Nature of Fungi ("Why Mushrooms are Cold")](https://www.pnas.org/doi/abs/10.1073/pnas.2221996120)
- [Testosterone histories from tusks reveal woolly mammoth musth episodes](https://twitter.com/pplpleasr1)
- [Antartica Gained Ice, Not Lost It](https://notrickszone.com/2023/06/05/scientists-caught-inflating-antarctic-ice-losses-3000-more-than-observations/)
- [Anartica Low Ice Winter](https://www.iflscience.com/antarcticas-low-ice-winter-should-only-happen-once-every-13-billion-years-69986)
- [Sea Water Heat Map](https://coralreefwatch.noaa.gov/product/5km/index_5km_hs.php)
- [The Climate Change Alternative We Ignore (to Our Peril)](https://theethicalskeptic.com/tag/core-exothermic-cycle/#:~:text=The%20Exothermic%20Core%20Theory%20of,speed%20up%20in%20Earth's%20rotation.)
- [Gold Mining and the Environment](https://www.brilliantearth.com/gold-mining-environment/)


## Geoengineering

- [Can Controversial Geoengineering Fix Climate Crisis](https://www.theguardian.com/environment/2022/dec/25/can-controversial-geoengineering-fix-climate-crisis)
- [Near-term climate risks and sunlight reflection modification: a roadmap approach for physical sciences research](https://link.springer.com/article/10.1007/s10584-022-03446-4)
- [Reflecting Sunlight: Recommendations for Solar Geoengineering Research and Research Governance - National Academies of Sciences, Engineering, and Medicine](https://nap.nationalacademies.org/read/25762/chapter/1#v)
- [Make Sunsets: Geoengineering Startup](https://makesunsets.com/)
- [Open Letter Against Solar Geoengineering](https://www.solargeoeng.org/non-use-agreement/open-letter/)
- [Stratospheric ozone changes under solar geoengineering: implications for UV exposure and air quality](https://acp.copernicus.org/articles/16/4191/2016/acp-16-4191-2016.pdf)
- [Geoengineering could Turn Skies White](https://www.scientificamerican.com/article/geoengineering-could-turn-skies-white/)
- [Weather as a Force Multiplier: Owning the Weather in 2025](https://www.geoengineeringwatch.org/documents/vol3ch15.pdf)
- [Washington's New World Order Weapons Have the Ability to Trigger Climate Change](https://archives.globalresearch.ca/articles/CHO201A.html)

## Animals

### Barbery Lions

- [Discovery Article: Barbary Lion Facts](https://www.discoveryuk.com/big-cats/barbary-lion-facts-habitat-and-diet/)

The Barbary lion is one of the most spectacular beasts ever to have walked the face of the Earth. Known as the Berber lion, the North African lion, the Egyptian lion and the Atlas lion, this is one of history’s most famous animals. 

In the vast deserts and mountains of the Barbary coast in North Africa, the Barbary lions once roamed freely. With their distinctly dark manes, they were thought to have been one of the largest lion species to have ever existed. These majestic creatures captured the imagination of many, and their historical significance reaches far back into antiquity.

Barbary lions were not only remarkable for their appearance but also for their role in history. These same lions were regularly captured by hunters for the brutal games held in the Roman colosseum. Known as "Damnatio ad bestias" in Latin, this practice was a form of capital punishment where condemned prisoners were executed by Barbary lions and other large cats. The lions' presence in such events added to their mythos and perpetuated their fame.

The decline of the Barbary lion population began with the expansion of the Arab empire from 632 to 1258, leading to the end of the Islamic Golden Age after the Siege of Baghdad by the Mongols. Survivors of that turbulent period claimed that "the waters of the Tigris ran black with ink from the enormous quantities of books flung into the river and red from the blood of the scientists and philosophers killed." Amidst the turmoil in the region and as empires crumbled and fell, the Barbary lions managed to persist until the arrival of European colonists in the 19th century.

During this time, big-game hunting gained popularity, and it proved to be devastating for the already dwindling lion population. As a result, sightings of Barbary lions became scarce, and not a single one was reported from 1901 to 1910. By the 1920s, most scientists believed that they had become extinct in the wild.

There were a few reported sightings in subsequent decades, offering glimmers of hope that some may have survived. In 1948, there was a reported sighting in Morocco, and in 1958, another sighting was claimed in a heavily forested area near the city of Sétif in Algeria. However, the forest was destroyed during the Algerian War in the same year, further exacerbating the challenges faced by these noble creatures.

Today, approximately 100 captive lions possess the genes of the Barbary lions, but none of them are pure descendants. While these lions carry a part of their ancestral legacy, the extinction of the Barbary lions in the wild serves as a stark reminder of the consequences of human actions on the delicate balance of nature. The story of the Barbary lion stands as a poignant testament to the importance of conservation efforts to protect and preserve the incredible diversity of life on our planet.

